; generated by ARM C/C++ Compiler, 5.02 [Build 28]
; commandline ArmCC [--split_sections --debug -c --asm --info=totals -o.\output\drvsys.o --depend=.\output\drvsys.d --cpu=Cortex-M0 --apcs=interwork -I..\CMSIS\CM0\DeviceSupport\Nuvoton\NUC123Series -I..\CMSIS\CM0\CoreSupport -I..\INC\DrvInc -I..\INC\SysInc -IC:\Keil\ARM\RV31\INC -IC:\Keil\ARM\CMSIS\Include -D__MICROLIB --omf_browse=.\output\drvsys.crf ..\DrvSrc\DrvSYS.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.DrvSYS_GetHCLKFreq||, CODE, READONLY, ALIGN=2

DrvSYS_GetHCLKFreq PROC
        PUSH     {r3-r7,lr}
        LDR      r5,|L1.124|
        LDR      r0,[r5,#0x10]
        LDR      r2,|L1.128|
        LSLS     r4,r0,#29
        LSRS     r4,r4,#29
        BEQ      |L1.44|
        LDR      r3,|L1.132|
        CMP      r4,#2
        BEQ      |L1.48|
        CMP      r4,#1
        BEQ      |L1.48|
        CMP      r4,#3
        BEQ      |L1.118|
        MOV      r0,r3
|L1.30|
        LDR      r1,[r5,#0x18]
        LSLS     r1,r1,#28
        LSRS     r1,r1,#28
        ADDS     r1,r1,#1
        BL       __aeabi_uidivmod
        POP      {r3-r7,pc}
|L1.44|
        MOV      r0,r2
        B        |L1.30|
|L1.48|
        ADR      r0,|L1.136|
        LDR      r0,[r0,#0]
        STR      r0,[sp,#0]
        LDR      r1,[r5,#0x20]
        MOVS     r0,#0
        MOVS     r6,#5
        LSLS     r6,r6,#16
        TST      r1,r6
        BNE      |L1.110|
        LSLS     r0,r1,#12
        BPL      |L1.72|
        MOV      r2,r3
|L1.72|
        MOV      r0,r2
        LSLS     r2,r1,#14
        BMI      |L1.110|
        LSLS     r2,r1,#16
        LSRS     r2,r2,#30
        MOV      r3,sp
        LDRB     r3,[r3,r2]
        LSLS     r2,r1,#23
        LSLS     r1,r1,#18
        LSRS     r2,r2,#23
        LSRS     r1,r1,#27
        ADDS     r2,r2,#2
        ADDS     r1,r1,#2
        LSRS     r0,r0,#2
        MULS     r1,r3,r1
        MULS     r0,r2,r0
        BL       __aeabi_uidivmod
        LSLS     r0,r0,#2
|L1.110|
        CMP      r4,#1
        BNE      |L1.30|
        LSRS     r0,r0,#1
        B        |L1.30|
|L1.118|
        LDR      r0,|L1.140|
        B        |L1.30|
        ENDP

        DCW      0x0000
|L1.124|
        DCD      0x50000200
|L1.128|
        DCD      0x00b71b00
|L1.132|
        DCD      0x01518000
|L1.136|
        DCB      1,2,2,4
|L1.140|
        DCD      0x00002710

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        EXPORT DrvSYS_GetHCLKFreq [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT __aeabi_uidivmod [CODE]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,3
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
