; generated by ARM C/C++ Compiler, 5.02 [Build 28]
; commandline ArmCC [--min_array_alignment=4 --split_sections --debug -c --asm --info=totals -o.\output\mypdma.o --depend=.\output\mypdma.d --cpu=Cortex-M0 --apcs=interwork -I..\CMSIS\CM0\DeviceSupport\Nuvoton\NUC123Series -I..\CMSIS\CM0\CoreSupport -I..\INC\DrvInc -I..\INC\SysInc -IC:\Keil\ARM\RV31\INC -IC:\Keil\ARM\CMSIS\Include -D__MICROLIB --omf_browse=.\output\mypdma.crf ..\AppSrc\mypdma.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.DmaInit||, CODE, READONLY, ALIGN=2

DmaInit PROC
        PUSH     {r4,lr}
        MOVS     r0,#4
        MOVS     r1,#5
        LSLS     r1,r1,#28
        LDR      r2,[r1,#8]
        ORRS     r2,r2,r0
        STR      r2,[r1,#8]
        LDR      r2,[r1,#8]
        BICS     r2,r2,r0
        STR      r2,[r1,#8]
        LDR      r1,|L1.36|
        MOVS     r0,#2
        LDR      r2,[r1,#4]
        ORRS     r2,r2,r0
        STR      r2,[r1,#4]
        BL       i2sDmaInit
        POP      {r4,pc}
        ENDP

|L1.36|
        DCD      0x50000200

        AREA ||i.PDMA_GET_CH_INTR_STS||, CODE, READONLY, ALIGN=2

PDMA_GET_CH_INTR_STS PROC
        LDR      r1,|L2.16|
        LDR      r1,[r1,#0xc]
        MOVS     r2,#1
        LSLS     r2,r2,r0
        MOV      r0,r1
        ANDS     r0,r0,r2
        BX       lr
        ENDP

        DCW      0x0000
|L2.16|
        DCD      0x50008f00

        AREA ||i.PDMA_IRQHandler||, CODE, READONLY, ALIGN=2

PDMA_IRQHandler PROC
        PUSH     {r3-r7,lr}
        MOVS     r0,#1
        BL       PDMA_GET_CH_INTR_STS
        MOVS     r5,#0
        MOVS     r6,#1
        LDR      r7,|L3.176|
        CMP      r0,#0
        BEQ      |L3.96|
        LDR      r4,|L3.180|
        MOVS     r0,#2
        LDR      r1,[r4,#0x24]
        TST      r1,r0
        BEQ      |L3.70|
        STR      r0,[r4,#0x24]
        BL       triggerFilter
        LDR      r0,[r7,#0]  ; i2s_pdma_rxbuf_flag
        LDR      r1,|L3.184|
        CMP      r0,#0
        LDR      r0,|L3.188|
        BEQ      |L3.58|
        ADDS     r0,r0,#0xc0
        LSRS     r0,r0,#2
        LSLS     r0,r0,#2
        STR      r0,[r4,#8]
        STR      r6,[r1,#0]  ; filter_rxbuf_flag
        STR      r5,[r7,#0]  ; i2s_pdma_rxbuf_flag
        B        |L3.86|
|L3.58|
        LSRS     r0,r0,#2
        LSLS     r0,r0,#2
        STR      r0,[r4,#8]
        STR      r5,[r1,#0]  ; filter_rxbuf_flag
        STR      r6,[r7,#0]  ; i2s_pdma_rxbuf_flag
        B        |L3.86|
|L3.70|
        LDR      r0,[r4,#0x24]
        LSLS     r0,r0,#31
        LSRS     r0,r0,#31
        BEQ      |L3.86|
        MOVS     r0,#1
        STR      r0,[r4,#0x24]
        BL       i2sDmaInit
|L3.86|
        LDR      r0,[r4,#0]
        MOVS     r1,#1
        LSLS     r1,r1,#23
        ORRS     r0,r0,r1
        STR      r0,[r4,#0]
|L3.96|
        MOVS     r0,#2
        BL       PDMA_GET_CH_INTR_STS
        CMP      r0,#0
        BEQ      |L3.174|
        LDR      r4,|L3.192|
        MOVS     r0,#2
        LDR      r1,[r4,#0x24]
        TST      r1,r0
        BEQ      |L3.148|
        STR      r0,[r4,#0x24]
        LDR      r0,[r7,#4]  ; i2s_pdma_txbuf_flag
        CMP      r0,#0
        LDR      r0,|L3.196|
        BEQ      |L3.138|
        ADDS     r0,r0,#0xc0
        LSRS     r0,r0,#2
        LSLS     r0,r0,#2
        STR      r0,[r4,#4]
        STR      r5,[r7,#4]  ; i2s_pdma_txbuf_flag
        B        |L3.164|
|L3.138|
        LSRS     r0,r0,#2
        LSLS     r0,r0,#2
        STR      r0,[r4,#4]
        STR      r6,[r7,#4]  ; i2s_pdma_txbuf_flag
        B        |L3.164|
|L3.148|
        LDR      r0,[r4,#0x24]
        LSLS     r0,r0,#31
        LSRS     r0,r0,#31
        BEQ      |L3.164|
        MOVS     r0,#1
        STR      r0,[r4,#0x24]
        BL       i2sDmaInit
|L3.164|
        LDR      r0,[r4,#0]
        MOVS     r1,#1
        LSLS     r1,r1,#23
        ORRS     r0,r0,r1
        STR      r0,[r4,#0]
|L3.174|
        POP      {r3-r7,pc}
        ENDP

|L3.176|
        DCD      ||.data||
|L3.180|
        DCD      0x50008100
|L3.184|
        DCD      filter_rxbuf_flag
|L3.188|
        DCD      ||.bss||
|L3.192|
        DCD      0x50008200
|L3.196|
        DCD      ||.bss||+0x180

        AREA ||i.i2sDmaInit||, CODE, READONLY, ALIGN=2

i2sDmaInit PROC
        PUSH     {r4-r7,lr}
        SUB      sp,sp,#0x1c
        LDR      r0,|L4.136|
        STR      r0,[sp,#4]
        LDR      r0,|L4.140|
        MOVS     r6,#0x20
        STR      r0,[sp,#0xc]
        MOVS     r4,#0
        STR      r6,[sp,#0]
        MOVS     r0,#4
        MOVS     r7,#0xc0
        STR      r0,[sp,#0x14]
        STR      r4,[sp,#8]
        STR      r4,[sp,#0x10]
        MOV      r1,sp
        STR      r7,[sp,#0x18]
        LDR      r0,|L4.144|
        BL       DrvPDMA_Init
        LDR      r0,|L4.148|
        MOVS     r5,#1
        STR      r5,[r0,#0]  ; i2s_pdma_rxbuf_flag
        LDR      r0,|L4.152|
        STR      r0,[sp,#4]
        MOVS     r0,#0x80
        STR      r0,[sp,#8]
        LDR      r0,|L4.136|
        STR      r4,[sp,#0]
        SUBS     r0,r0,#4
        STR      r4,[sp,#0x10]
        STR      r0,[sp,#0xc]
        MOVS     r0,#8
        LDR      r4,|L4.156|
        STR      r0,[sp,#0x14]
        MOV      r1,sp
        STR      r7,[sp,#0x18]
        MOV      r0,r4
        BL       DrvPDMA_Init
        LDR      r0,|L4.148|
        LDR      r1,|L4.160|
        STR      r5,[r0,#4]  ; i2s_pdma_txbuf_flag
        LDR      r0,[r1,#0x10]
        LSRS     r0,r0,#4
        LSLS     r0,r0,#4
        ORRS     r0,r0,r5
        STR      r0,[r1,#0x10]
        LDR      r0,[r1,#0x10]
        MOVS     r2,#0xf0
        BICS     r0,r0,r2
        ORRS     r0,r0,r6
        STR      r0,[r1,#0x10]
        MOVS     r1,#3
        LDR      r0,|L4.144|
        BL       DrvPDMA_EnableInt
        MOVS     r1,#3
        MOV      r0,r4
        BL       DrvPDMA_EnableInt
        LDR      r1,|L4.164|
        LDR      r0,[r1,#0]
        MOVS     r2,#0xff
        LSLS     r2,r2,#16
        BICS     r0,r0,r2
        STR      r0,[r1,#0]
        ADD      sp,sp,#0x1c
        POP      {r4-r7,pc}
        ENDP

|L4.136|
        DCD      0x401a0014
|L4.140|
        DCD      ||.bss||
|L4.144|
        DCD      0x50008100
|L4.148|
        DCD      ||.data||
|L4.152|
        DCD      ||.bss||+0x180
|L4.156|
        DCD      0x50008200
|L4.160|
        DCD      0x50008f00
|L4.164|
        DCD      0xe000e418

        AREA ||i.spi2I2sDmaInit||, CODE, READONLY, ALIGN=1

spi2I2sDmaInit PROC
        BX       lr
        ENDP


        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.bss||, DATA, NOINIT, ALIGN=2

i2s_rxbuf
        %        384
i2s_txbuf
        %        384

        AREA ||.data||, DATA, ALIGN=2

i2s_pdma_rxbuf_flag
        DCD      0x00000001
i2s_pdma_txbuf_flag
        DCD      0x00000001

        EXPORT DmaInit [CODE]
        EXPORT PDMA_IRQHandler [CODE]
        EXPORT i2sDmaInit [CODE]
        EXPORT spi2I2sDmaInit [CODE]
        EXPORT i2s_rxbuf [DATA,SIZE=384]
        EXPORT i2s_txbuf [DATA,SIZE=384]
        EXPORT i2s_pdma_rxbuf_flag [DATA,SIZE=4]
        EXPORT i2s_pdma_txbuf_flag [DATA,SIZE=4]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT DrvPDMA_Init [CODE]
        IMPORT DrvPDMA_EnableInt [CODE]
        IMPORT triggerFilter [CODE]
        IMPORT filter_rxbuf_flag [DATA]

        KEEP PDMA_GET_CH_INTR_STS

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,3
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
