; generated by ARM C/C++ Compiler, 5.02 [Build 28]
; commandline ArmCC [--min_array_alignment=4 --split_sections --debug -c --asm --info=totals -o.\output\power.o --depend=.\output\power.d --cpu=Cortex-M0 --apcs=interwork -I..\CMSIS\CM0\DeviceSupport\Nuvoton\NUC123Series -I..\CMSIS\CM0\CoreSupport -I..\INC\DrvInc -I..\INC\SysInc -IC:\Keil\ARM\RV31\INC -IC:\Keil\ARM\CMSIS\Include -D__MICROLIB --omf_browse=.\output\power.crf ..\AppSrc\power.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.DECT_DC||, CODE, READONLY, ALIGN=2

DECT_DC PROC
        LDR      r0,|L1.16|
        LDR      r0,[r0,#0]
        CMP      r0,#0
        BEQ      |L1.12|
        MOVS     r0,#0
        BX       lr
|L1.12|
        MOVS     r0,#1
        BX       lr
        ENDP

|L1.16|
        DCD      0x5000423c

        AREA ||i.GPAB_IRQHandler||, CODE, READONLY, ALIGN=2

GPAB_IRQHandler PROC
        PUSH     {r4-r6,lr}
        LDR      r4,|L2.64|
        LDR      r0,[r4,#0x20]
        CMP      r0,#0x40
        BEQ      |L2.58|
        MOVS     r6,#1
        LSLS     r0,r6,#8
        STR      r0,[r4,#0x20]
        LDR      r5,|L2.64|
        LSLS     r0,r0,#7
        SUBS     r5,r5,#0x40
        STR      r0,[r5,#0x20]
        ASRS     r0,r0,#5
        STR      r0,[r4,#0x20]
        MOVS     r1,#8
        MOV      r0,r4
        BL       GPIO_DisableInt
        MOVS     r1,#0xf
        MOV      r0,r5
        BL       GPIO_DisableInt
        MOVS     r1,#0xa
        MOV      r0,r4
        BL       GPIO_DisableInt
        LDR      r0,|L2.68|
        STR      r6,[r0,#0xc]  ; gpio_int
        POP      {r4-r6,pc}
|L2.58|
        BL       IR_IRQHandler
        POP      {r4-r6,pc}
        ENDP

|L2.64|
        DCD      0x50004040
|L2.68|
        DCD      ||area_number.27||

        AREA ||i.GPIO_DisableInt||, CODE, READONLY, ALIGN=2

GPIO_DisableInt PROC
        LDR      r2,[r0,#0x18]
        MOVS     r3,#1
        LSLS     r3,r3,r1
        BICS     r2,r2,r3
        STR      r2,[r0,#0x18]
        LDR      r2,[r0,#0x1c]
        LDR      r3,|L3.24|
        LSLS     r3,r3,r1
        BICS     r2,r2,r3
        STR      r2,[r0,#0x1c]
        BX       lr
        ENDP

        DCW      0x0000
|L3.24|
        DCD      0x00010001

        AREA ||i.GPIO_EnableInt||, CODE, READONLY, ALIGN=2

GPIO_EnableInt PROC
        PUSH     {r4,lr}
        LDR      r3,[r0,#0x18]
        MOVS     r4,#1
        LSLS     r4,r4,r1
        BICS     r3,r3,r4
        LSRS     r4,r2,#31
        LSLS     r4,r4,r1
        ORRS     r3,r3,r4
        STR      r3,[r0,#0x18]
        LDR      r3,[r0,#0x1c]
        LDR      r4,|L4.40|
        LSLS     r4,r4,r1
        LSLS     r2,r2,#1
        LSRS     r2,r2,#1
        BICS     r3,r3,r4
        LSLS     r2,r2,r1
        ORRS     r3,r3,r2
        STR      r3,[r0,#0x1c]
        POP      {r4,pc}
        ENDP

        DCW      0x0000
|L4.40|
        DCD      0x00010001

        AREA ||i.GPIO_SET_MODE||, CODE, READONLY, ALIGN=1

GPIO_SET_MODE PROC
        PUSH     {r4,lr}
        LDR      r3,[r0,#0]
        LSLS     r1,r1,#1
        MOVS     r4,#3
        LSLS     r4,r4,r1
        BICS     r3,r3,r4
        LSLS     r2,r2,r1
        ORRS     r3,r3,r2
        STR      r3,[r0,#0]
        POP      {r4,pc}
        ENDP


        AREA ||i.I2S_DISABLE_MCK||, CODE, READONLY, ALIGN=2

I2S_DISABLE_MCK PROC
        LDR      r0,|L6.16|
        LDR      r1,[r0,#0]
        MOVS     r2,#1
        LSLS     r2,r2,#15
        BICS     r1,r1,r2
        STR      r1,[r0,#0]
        BX       lr
        ENDP

        DCW      0x0000
|L6.16|
        DCD      0x401a0000

        AREA ||i.PWRWU_IRQHandler||, CODE, READONLY, ALIGN=2

PWRWU_IRQHandler PROC
        PUSH     {r4,lr}
        BL       SYS_UnlockReg
        MOVS     r0,#2
        BL       ledColorSet
        MOVS     r0,#0x7d
        LSLS     r0,r0,#4
        BL       sysDelayMs
        LDR      r1,|L7.28|
        MOVS     r0,#0
        STR      r0,[r1,#0]
        POP      {r4,pc}
        ENDP

|L7.28|
        DCD      0x50000100

        AREA ||i.SYS_UnlockReg||, CODE, READONLY, ALIGN=2

SYS_UnlockReg PROC
        LDR      r0,|L8.16|
        MOVS     r1,#0x59
        STR      r1,[r0,#0]
        MOVS     r1,#0x16
        STR      r1,[r0,#0]
        MOVS     r1,#0x88
        STR      r1,[r0,#0]
        BX       lr
        ENDP

|L8.16|
        DCD      0x50000100

        AREA ||i.WDTInit||, CODE, READONLY, ALIGN=2

WDTInit PROC
        PUSH     {r4,lr}
        MOVS     r2,#1
        MOVS     r1,#3
        MOVS     r0,#5
        BL       DrvWDT_Init
        BL       SYS_UnlockReg
        LDR      r4,|L9.68|
        LDR      r0,[r4,#0]
        MOVS     r1,#0x80
        ORRS     r0,r0,r1
        STR      r0,[r4,#0]
        BL       WDT_CLEAR_RESET_FLAG
        LDR      r0,[r4,#0]
        MOVS     r1,#0x10
        BICS     r0,r0,r1
        STR      r0,[r4,#0]
        LDR      r0,[r4,#0]
        MOVS     r1,#2
        ORRS     r0,r0,r1
        STR      r0,[r4,#0]
        LDR      r0,[r4,#0]
        MOVS     r1,#1
        ORRS     r0,r0,r1
        STR      r0,[r4,#0]
        BL       DrvWDT_EnableInt
        LDR      r1,|L9.72|
        MOVS     r0,#0
        STR      r0,[r1,#0]
        POP      {r4,pc}
        ENDP

        DCW      0x0000
|L9.68|
        DCD      0x40004000
|L9.72|
        DCD      0x50000100

        AREA ||i.WDT_CLEAR_RESET_FLAG||, CODE, READONLY, ALIGN=2

WDT_CLEAR_RESET_FLAG PROC
        LDR      r0,|L10.12|
        LDR      r1,[r0,#0]
        MOVS     r2,#4
        ORRS     r1,r1,r2
        STR      r1,[r0,#0]
        BX       lr
        ENDP

|L10.12|
        DCD      0x40004000

        AREA ||i.WDT_IRQHandler||, CODE, READONLY, ALIGN=2

WDT_IRQHandler PROC
        PUSH     {r4,lr}
        BL       SYS_UnlockReg
        LDR      r0,|L11.24|
        LDR      r1,[r0,#0]
        MOVS     r2,#8
        ORRS     r1,r1,r2
        STR      r1,[r0,#0]
        LDR      r1,|L11.28|
        MOVS     r0,#0
        STR      r0,[r1,#0]
        POP      {r4,pc}
        ENDP

|L11.24|
        DCD      0x40004000
|L11.28|
        DCD      0x50000100

        AREA ||i.closeMcuCtrlPin||, CODE, READONLY, ALIGN=2

closeMcuCtrlPin PROC
        PUSH     {r4,lr}
        LDR      r4,|L12.80|
        MOVS     r2,#0
        MOVS     r1,#0xe
        MOV      r0,r4
        BL       GPIO_SET_MODE
        MOVS     r2,#0
        MOVS     r1,#5
        MOV      r0,r4
        BL       GPIO_SET_MODE
        MOVS     r2,#0
        MOVS     r1,#4
        MOV      r0,r4
        BL       GPIO_SET_MODE
        LDR      r4,|L12.84|
        MOVS     r2,#0
        MOVS     r1,#3
        MOV      r0,r4
        BL       GPIO_SET_MODE
        MOVS     r2,#0
        MOVS     r1,#2
        MOV      r0,r4
        BL       GPIO_SET_MODE
        LDR      r0,|L12.88|
        LDR      r1,[r0,#4]
        MOVS     r2,#0xc
        BICS     r1,r1,r2
        STR      r1,[r0,#4]
        LDR      r1,[r0,#0x14]
        MOVS     r2,#0xf
        LSLS     r2,r2,#24
        BICS     r1,r1,r2
        STR      r1,[r0,#0x14]
        POP      {r4,pc}
        ENDP

        DCW      0x0000
|L12.80|
        DCD      0x50004040
|L12.84|
        DCD      0x50004140
|L12.88|
        DCD      0x50000040

        AREA ||i.dealPowerKey||, CODE, READONLY, ALIGN=2

dealPowerKey PROC
        PUSH     {r3-r7,lr}
        MOVS     r4,#0
        MOV      r2,r4
        MOVS     r1,#0xa
        LDR      r0,|L13.156|
        BL       GPIO_SET_MODE
        LDR      r7,|L13.160|
        MOV      r0,r7
        BL       sysDelayUs
        BL       DECT_DC
        LDR      r1,|L13.164|
        LDR      r2,|L13.164|
        MOVS     r5,#1
        LDR      r6,|L13.168|
        SUBS     r1,r1,#0x30
        CMP      r0,#0
        BNE      |L13.46|
        LDR      r0,[r2,#0]
        CMP      r0,#0
        BEQ      |L13.76|
|L13.46|
        LDR      r0,[r2,#0]
        CMP      r0,#0
        BEQ      |L13.56|
        LDR      r0,|L13.172|
        STRB     r5,[r0,#0]
|L13.56|
        STR      r5,[r1,#0]
        MOV      r0,r7
        BL       sysDelayUs
        BL       DECT_DC
        CMP      r0,#0
        BEQ      |L13.144|
|L13.72|
        STR      r5,[r6,#0]  ; dc_time_stamp
        B        |L13.144|
|L13.76|
        LDR      r0,|L13.168|
        MOVS     r7,#0
        STR      r7,[r0,#0]  ; dc_time_stamp
        MOVS     r0,#5
        LSLS     r0,r0,#28
        LDR      r0,[r0,#4]
        MOVS     r2,#0x20
        TST      r0,r2
        BEQ      |L13.96|
        MOVS     r4,#0x50
|L13.96|
        MOV      r6,r1
|L13.98|
        LDR      r0,|L13.164|
        SUBS     r0,r0,#8
        LDR      r1,[r0,#0]
        CMP      r1,#0
        BEQ      |L13.128|
        MOVS     r0,#5
        BL       sysDelayMs
        BL       DECT_DC
        CMP      r0,#0
        BEQ      |L13.138|
        LDR      r0,|L13.168|
        STR      r5,[r0,#0]  ; dc_time_stamp
        B        |L13.72|
|L13.128|
        STR      r7,[r6,#0]
        MOVS     r4,#0
|L13.132|
        LDR      r1,[r0,#0]
        CMP      r1,#0
        BEQ      |L13.132|
|L13.138|
        ADDS     r4,r4,#1
        CMP      r4,#0x64
        BCC      |L13.98|
|L13.144|
        BL       adcReadKey
        BL       adcReadKey
        POP      {r3-r7,pc}
        ENDP

        DCW      0x0000
|L13.156|
        DCD      0x50004040
|L13.160|
        DCD      0x000186a0
|L13.164|
        DCD      0x50004268
|L13.168|
        DCD      dc_time_stamp
|L13.172|
        DCD      ||area_number.27||

        AREA ||i.doPowerOff||, CODE, READONLY, ALIGN=2

doPowerOff PROC
        PUSH     {r3-r7,lr}
        MOVS     r6,#0
        MOV      r5,r6
        MOV      r4,r6
        BL       DrvWDT_DisableInt
        LDR      r0,|L14.124|
        MOVS     r1,#0
        STR      r1,[r0,#0]
        LDR      r7,|L14.124|
        ADDS     r7,r7,#0x28
|L14.22|
        MOVS     r0,#0x14
        BL       sysDelayMs
        CMP      r4,#0
        BNE      |L14.38|
        LDR      r0,[r7,#0]
        CMP      r0,#0
        BNE      |L14.46|
|L14.38|
        ADDS     r6,r6,#1
        CMP      r6,#3
        BNE      |L14.46|
        MOVS     r4,#1
|L14.46|
        BL       DECT_DC
        CMP      r0,#0
        BEQ      |L14.68|
        LDR      r1,|L14.124|
        MOVS     r0,#1
        STR      r0,[r1,#0]
        MOVS     r0,#0x32
        BL       sysDelayMs
        POP      {r3-r7,pc}
|L14.68|
        CMP      r4,#1
        BNE      |L14.120|
        LDR      r0,[r7,#0]
        CMP      r0,#0
        BEQ      |L14.120|
        ADDS     r5,r5,#1
        CMP      r5,#0xa
        BNE      |L14.22|
        MOVS     r0,#0
        BL       ledColorSet
        LDR      r1,|L14.124|
        MOVS     r0,#1
        STR      r0,[r1,#0]
        MOVS     r0,#0x4b
        LSLS     r0,r0,#3
        BL       sysDelayMs
        BL       SYS_UnlockReg
        LDR      r1,|L14.132|
        LDR      r0,|L14.128|
        STR      r0,[r1,#0xc]
        DSB      #0x0
|L14.118|
        B        |L14.118|
|L14.120|
        MOVS     r5,#0
        B        |L14.22|
        ENDP

|L14.124|
        DCD      0x50004238
|L14.128|
        DCD      0x05fa0004
|L14.132|
        DCD      0xe000ed00

        AREA ||i.enterStandby||, CODE, READONLY, ALIGN=2

enterStandby PROC
        PUSH     {r3-r7,lr}
        ADR      r0,|L15.296|
        LDR      r0,[r0,#0]
        LDR      r6,|L15.300|
        STR      r0,[sp,#0]
        MOVS     r4,#1
        STRB     r4,[r6,#1]
        MOVS     r0,#0
        LDR      r5,|L15.304|
        STRB     r0,[r6,#0]
        STRB     r4,[r5,#0]
        LDRB     r0,[r6,#3]  ; factory_mode_flag
        CMP      r0,#0
        BEQ      |L15.38|
        LDR      r1,|L15.308|
        MOVS     r0,#5
        STRB     r0,[r1,#0]
        BL       testOutputSpeakers
|L15.38|
        LDR      r7,|L15.312|
        LDRB     r0,[r7,#0]  ; SB_flag
        CMP      r0,#0
        BEQ      |L15.88|
        BL       Dwhp83CuMuDetect
        CMP      r0,#0
        BEQ      |L15.74|
        LDR      r0,|L15.316|
        LDR      r0,[r0,#0]  ; Dwhp83_CuMu
        LDR      r1,|L15.320|
        CMP      r0,r1
        BNE      |L15.74|
        BL       DWHP83toEXT_MCU
        MOVS     r0,#0x64
        BL       sysDelayMs
|L15.74|
        LDRB     r0,[r7,#0]  ; SB_flag
        CMP      r0,#0
        BEQ      |L15.88|
        LDR      r0,|L15.324|
        LDRB     r1,[r0,#0]  ; dev_input
        CMP      r1,#1
        BEQ      |L15.112|
|L15.88|
        MOVS     r2,#3
        MOVS     r1,#0xc6
        MOV      r0,sp
        BL       writeDwhp83
|L15.98|
        MOVS     r0,#0x64
        BL       sysDelayMs
        LDRB     r0,[r7,#0]  ; SB_flag
        CMP      r0,#0
        BEQ      |L15.122|
        B        |L15.144|
|L15.112|
        MOVS     r1,#3
        STRB     r1,[r0,#0]
        BL       set_soundbar_coco
        B        |L15.98|
|L15.122|
        BL       Dwhp83CuMuDetect
        CMP      r0,#0
        BEQ      |L15.144|
        LDR      r0,|L15.316|
        LDR      r0,[r0,#0]  ; Dwhp83_CuMu
        LDR      r1,|L15.328|
        CMP      r0,r1
        BNE      |L15.144|
        BL       Dwhp83Slave
|L15.144|
        LDR      r1,|L15.332|
        LDRB     r0,[r1,#0]  ; amp_volume
        STRB     r0,[r6,#4]
        CMP      r0,#0x19
        BLS      |L15.158|
        MOVS     r0,#0x19
        B        |L15.164|
|L15.158|
        CMP      r0,#9
        BCS      |L15.166|
        MOVS     r0,#9
|L15.164|
        STRB     r0,[r6,#4]
|L15.166|
        UXTB     r0,r0
        STR      r0,[r1,#0]  ; amp_volume
        BL       setConfig
        MOVS     r0,#0x64
        BL       sysDelayMs
        LDR      r1,|L15.336|
        MOVS     r0,#2
        STRB     r0,[r1,#0]
        LDR      r0,|L15.340|
        STRB     r4,[r0,#0]
        MOVS     r0,#1
        BL       ledColorSet
        MOVS     r6,#0
        STRB     r6,[r5,#0]
        BL       DWHP83Mute
        BL       DECT_DC
        CMP      r0,#0
        BNE      |L15.234|
        MOVS     r0,#0x32
        BL       sysDelayMs
        BL       DWHP83UnMute
        MOVS     r0,#0x32
        BL       sysDelayMs
        MOVS     r0,#0
        BL       playMusic
|L15.234|
        STRB     r4,[r5,#0]
        BL       btShutDown
        MOVS     r0,#0xff
        ADDS     r0,r0,#0xf5
        BL       sysDelayMs
        MOVS     r0,#0x7d
        LSLS     r0,r0,#3
        BL       sysDelayMs
        MOVS     r4,#0x1e
|L15.258|
        UXTB     r0,r4
        BL       seW58SetVolume
        BL       seW58sendCmd
        MOVS     r0,#5
        BL       sysDelayMs
        SUBS     r4,r4,#1
        BPL      |L15.258|
        BL       mute
        MOVS     r0,#0x64
        BL       sysDelayMs
        STRB     r6,[r5,#0]
        BL       powerOff
        POP      {r3-r7,pc}
        ENDP

|L15.296|
        DCB      16,16,16,0
|L15.300|
        DCD      ||area_number.27||
|L15.304|
        DCD      bt_amp_start_flag
|L15.308|
        DCD      test_channel
|L15.312|
        DCD      SB_flag
|L15.316|
        DCD      Dwhp83_CuMu
|L15.320|
        DCD      0x0000aa55
|L15.324|
        DCD      dev_input
|L15.328|
        DCD      0x000055aa
|L15.332|
        DCD      amp_volume
|L15.336|
        DCD      dev_state
|L15.340|
        DCD      state_color

        AREA ||i.openMcuCtrlPin||, CODE, READONLY, ALIGN=2

openMcuCtrlPin PROC
        PUSH     {r4-r6,lr}
        LDR      r0,|L16.256|
        MOVS     r4,#0
        STR      r4,[r0,#0]
        LDR      r5,|L16.260|
        MOVS     r2,#1
        MOVS     r1,#9
        MOV      r0,r5
        BL       GPIO_SET_MODE
        MOVS     r2,#1
        MOVS     r1,#0xe
        MOV      r0,r5
        BL       GPIO_SET_MODE
        LDR      r6,|L16.260|
        MOVS     r2,#1
        SUBS     r6,r6,#0x40
        MOVS     r1,#0xe
        MOV      r0,r6
        BL       GPIO_SET_MODE
        LDR      r0,|L16.260|
        MOVS     r2,#1
        MOVS     r1,#0xd
        ADDS     r0,r0,#0x40
        BL       GPIO_SET_MODE
        LDR      r0,|L16.256|
        SUBS     r0,r0,#0x30
        STR      r4,[r0,#0]
        MOVS     r2,#1
        MOVS     r1,#0xd
        MOV      r0,r6
        BL       GPIO_SET_MODE
        LDR      r0,|L16.256|
        SUBS     r0,r0,#0x10
        STR      r4,[r0,#0]
        MOVS     r2,#1
        MOVS     r1,#5
        MOV      r0,r5
        BL       GPIO_SET_MODE
        MOVS     r2,#1
        MOVS     r1,#4
        MOV      r0,r5
        BL       GPIO_SET_MODE
        LDR      r4,|L16.264|
        MOVS     r2,#2
        MOVS     r1,#3
        MOV      r0,r4
        BL       GPIO_SET_MODE
        MOVS     r2,#2
        MOV      r1,r2
        MOV      r0,r4
        BL       GPIO_SET_MODE
        MOVS     r2,#2
        MOVS     r1,#0xb
        MOV      r0,r6
        BL       GPIO_SET_MODE
        MOVS     r2,#2
        MOVS     r1,#0xa
        MOV      r0,r6
        BL       GPIO_SET_MODE
        LDR      r1,|L16.268|
        LDR      r0,[r1,#4]
        MOVS     r2,#0xc
        ORRS     r0,r0,r2
        STR      r0,[r1,#4]
        LDR      r0,[r1,#0x14]
        MOVS     r2,#0xf
        LSLS     r2,r2,#24
        BICS     r0,r0,r2
        LSLS     r2,r4,#19
        ADDS     r0,r0,r2
        STR      r0,[r1,#0x14]
        MOVS     r2,#0
        MOVS     r1,#0xf
        MOV      r0,r6
        BL       GPIO_SET_MODE
        MOVS     r2,#0
        MOVS     r1,#8
        MOV      r0,r5
        BL       GPIO_SET_MODE
        LDR      r0,|L16.256|
        MOVS     r1,#1
        ADDS     r0,r0,#0x60
        STR      r1,[r0,#0]
        ADDS     r0,r0,#4
        STR      r1,[r0,#0]
        ADDS     r0,r0,#4
        STR      r1,[r0,#0]
        LDR      r4,|L16.260|
        MOV      r2,r1
        ADDS     r4,r4,#0x80
        MOV      r0,r4
        BL       GPIO_SET_MODE
        MOVS     r2,#1
        MOVS     r1,#2
        MOV      r0,r4
        BL       GPIO_SET_MODE
        MOVS     r2,#1
        MOVS     r1,#3
        MOV      r0,r4
        BL       GPIO_SET_MODE
        MOVS     r2,#0
        MOVS     r1,#0xa
        MOV      r0,r5
        BL       GPIO_SET_MODE
        MOVS     r2,#0
        MOVS     r1,#7
        MOV      r0,r5
        BL       GPIO_SET_MODE
        POP      {r4-r6,pc}
        ENDP

        DCW      0x0000
|L16.256|
        DCD      0x50004264
|L16.260|
        DCD      0x50004040
|L16.264|
        DCD      0x50004140
|L16.268|
        DCD      0x50000040

        AREA ||i.outStandby||, CODE, READONLY, ALIGN=2

outStandby PROC
        PUSH     {r3-r7,lr}
        LDR      r5,|L17.408|
        MOVS     r4,#0
        LDR      r0,|L17.412|
        STRB     r4,[r5,#1]
        MOVS     r6,#1
        STRB     r6,[r0,#0]
        BL       resumeI2c
        LDR      r0,|L17.416|
        STRB     r6,[r5,#2]
        LDRB     r1,[r0,#0]  ; dev_state
        CMP      r1,#0
        BEQ      |L17.32|
        MOVS     r1,#1
        STRB     r1,[r0,#0]
|L17.32|
        LDR      r1,|L17.420|
        MOVS     r0,#0x2d
        STR      r0,[r1,#0]  ; cc_blue_p
        LDR      r1,|L17.424|
        MOVS     r0,#0x78
        STR      r0,[r1,#0]  ; BAT_STATE_DECT_DELAY_COUNT
        LDRB     r0,[r5,#5]  ; sleep_flag
        LDR      r7,|L17.428|
        CMP      r0,#0
        BNE      |L17.74|
        LDRB     r0,[r5,#0]  ; NFC_flag
        CMP      r0,#0
        BEQ      |L17.60|
        STRB     r4,[r7,#0]
|L17.60|
        LDR      r0,|L17.432|
        LDRB     r1,[r7,#0]  ; dev_input
        LDRB     r0,[r0,r1]
        LDR      r1,|L17.436|
        STRB     r0,[r1,#0]
        BL       ledColorSet
|L17.74|
        LDR      r0,|L17.408|
        STRB     r4,[r0,#5]
        BL       powerOn
        BL       getConfig
        LDR      r5,|L17.440|
        LDRB     r0,[r5,#0]  ; SB_flag
        CMP      r0,#0
        BEQ      |L17.148|
        BL       set_soundbar_coco
|L17.98|
        MOVS     r0,#0x14
        BL       sysDelayMs
        BL       Dwhp83CuMuDetect
        LDR      r0,|L17.440|
        LDR      r5,|L17.444|
        LDRB     r0,[r0,#0]  ; SB_flag
        LDR      r6,|L17.448|
        STR      r4,[r5,#0]  ; Dwhp83_flag
        LDR      r1,[r6,#0]  ; Dwhp83_CuMu
        CMP      r0,#0
        BEQ      |L17.154|
        LDR      r0,|L17.452|
        CMP      r1,r0
        BNE      |L17.164|
        BL       Dwhp83Master
        MOVS     r0,#0x7d
        LSLS     r0,r0,#4
        BL       sysDelayMs
        BL       SUB_volume_unmute
        B        |L17.172|
|L17.148|
        BL       set_local_coco
        B        |L17.98|
|L17.154|
        LDR      r0,|L17.456|
        CMP      r1,r0
        BNE      |L17.164|
        BL       Dwhp83Slave
|L17.164|
        MOVS     r0,#0x7d
        LSLS     r0,r0,#3
        BL       sysDelayMs
|L17.172|
        LDR      r0,|L17.408|
        LDRB     r0,[r0,#3]  ; factory_mode_flag
        CMP      r0,#0
        BEQ      |L17.186|
        MOVS     r0,#2
        STRB     r0,[r7,#0]
        B        |L17.196|
|L17.186|
        LDR      r0,|L17.408|
        LDRB     r0,[r0,#0]  ; NFC_flag
        CMP      r0,#0
        BEQ      |L17.196|
        STRB     r4,[r7,#0]
|L17.196|
        BL       spiFlashInit
        LDR      r7,|L17.412|
        STRB     r4,[r7,#0]
        BL       DECT_DC
        CMP      r0,#0
        BEQ      |L17.226|
        LDR      r0,|L17.408|
        LDRB     r0,[r0,#3]  ; factory_mode_flag
        CMP      r0,#0
        BEQ      |L17.226|
        MOVS     r0,#0
        BL       playMusic
|L17.226|
        BL       unMute
        MOVS     r0,#1
        STRB     r0,[r7,#0]
        BL       WDTInit
        BL       cs8422InitAllConf
        LDR      r0,|L17.460|
        STRB     r4,[r7,#0]
        LDRB     r0,[r0,#0]  ; bt_hfp_flag
        CMP      r0,#0
        BNE      |L17.262|
        BL       btDisableHFP
        MOVS     r0,#0x64
        BL       sysDelayMs
|L17.262|
        BL       adcReadKey
        BL       adcReadKey
        MOVS     r0,#3
        BL       readeeprom
        LDR      r7,|L17.464|
        STR      r0,[r7,#0]  ; amp_volume
        MOVS     r0,#5
        BL       sysDelayMs
        LDR      r0,[r7,#0]  ; amp_volume
        CMP      r0,#0x19
        BLS      |L17.296|
        MOVS     r0,#0x19
        B        |L17.302|
|L17.296|
        CMP      r0,#9
        BCS      |L17.304|
        MOVS     r0,#9
|L17.302|
        STR      r0,[r7,#0]  ; amp_volume
|L17.304|
        BL       mute
        LDR      r7,|L17.440|
        LDRB     r0,[r7,#0]  ; SB_flag
        CMP      r0,#0
        BEQ      |L17.326|
        BL       soundbar_coco_check
        CMP      r0,#0
        BEQ      |L17.340|
        B        |L17.352|
|L17.326|
        BL       local_coco_check
        CMP      r0,#0
        BNE      |L17.352|
        BL       set_local_coco
        B        |L17.344|
|L17.340|
        BL       set_soundbar_coco
|L17.344|
        MOVS     r0,#0x7d
        LSLS     r0,r0,#3
        BL       sysDelayMs
|L17.352|
        BL       Dwhp83CuMuDetect
        CMP      r0,#0
        BEQ      |L17.388|
        LDRB     r0,[r7,#0]  ; SB_flag
        STR      r4,[r5,#0]  ; Dwhp83_flag
        LDR      r1,[r6,#0]  ; Dwhp83_CuMu
        CMP      r0,#0
        BEQ      |L17.394|
        LDR      r0,|L17.452|
        CMP      r1,r0
        BNE      |L17.380|
        BL       Dwhp83Master
|L17.380|
        MOVS     r0,#0x7d
        LSLS     r0,r0,#3
        BL       sysDelayMs
|L17.388|
        BL       unMute
        POP      {r3-r7,pc}
|L17.394|
        LDR      r0,|L17.456|
        CMP      r1,r0
        BNE      |L17.380|
        BL       Dwhp83Slave
        B        |L17.380|
        ENDP

        DCW      0x0000
|L17.408|
        DCD      ||area_number.27||
|L17.412|
        DCD      bt_amp_start_flag
|L17.416|
        DCD      dev_state
|L17.420|
        DCD      cc_blue_p
|L17.424|
        DCD      BAT_STATE_DECT_DELAY_COUNT
|L17.428|
        DCD      dev_input
|L17.432|
        DCD      input_channel_color
|L17.436|
        DCD      state_color
|L17.440|
        DCD      SB_flag
|L17.444|
        DCD      Dwhp83_flag
|L17.448|
        DCD      Dwhp83_CuMu
|L17.452|
        DCD      0x0000aa55
|L17.456|
        DCD      0x000055aa
|L17.460|
        DCD      bt_hfp_flag
|L17.464|
        DCD      amp_volume

        AREA ||i.powerOff||, CODE, READONLY, ALIGN=2

powerOff PROC
        PUSH     {r4-r6,lr}
        MOVS     r0,#0xc8
        BL       sysDelayMs
        LDR      r0,|L18.240|
        MOVS     r5,#0
        STR      r5,[r0,#0]
        LDR      r1,|L18.244|
        MOVS     r0,#2
        STRB     r0,[r1,#0]
        LDR      r1,|L18.248|
        MOVS     r0,#1
        STRB     r0,[r1,#0]
        BL       ledColorSet
        LDR      r0,|L18.252|
        STRB     r5,[r0,#0]
        BL       stopFlashLed
        BL       ampPowerDown
        MOVS     r0,#0xff
        ADDS     r0,r0,#0xf5
        BL       sysDelayMs
        LDR      r4,|L18.256|
        MOVS     r0,#1
        LDR      r1,[r4,#8]
        LSLS     r0,r0,#29
        BICS     r1,r1,r0
        STR      r1,[r4,#8]
        BL       I2S_DISABLE_MCK
        MOVS     r0,#5
        LSLS     r0,r0,#28
        LDR      r1,[r0,#0x38]
        LSRS     r1,r1,#4
        LSLS     r1,r1,#4
        STR      r1,[r0,#0x38]
        LDR      r1,|L18.260|
        LDR      r2,[r1,#0x10]
        MOVS     r3,#0xff
        ADDS     r3,r3,#0xe1
        BICS     r2,r2,r3
        STR      r2,[r1,#0x10]
        LDR      r2,[r0,#0x30]
        LSLS     r3,r1,#9
        BICS     r2,r2,r3
        STR      r2,[r0,#0x30]
        LDR      r0,[r1,#0x10]
        ASRS     r2,r3,#6
        BICS     r0,r0,r2
        STR      r0,[r1,#0x10]
        LDR      r6,|L18.264|
        MOVS     r2,#0
        MOVS     r1,#0xc
        MOV      r0,r6
        BL       GPIO_SET_MODE
        MOVS     r2,#0
        MOV      r1,r2
        MOV      r0,r6
        BL       GPIO_SET_MODE
        MOVS     r2,#0
        MOVS     r1,#1
        MOV      r0,r6
        BL       GPIO_SET_MODE
        MOVS     r2,#0
        MOVS     r1,#2
        MOV      r0,r6
        BL       GPIO_SET_MODE
        MOVS     r2,#0
        MOVS     r1,#3
        MOV      r0,r6
        BL       GPIO_SET_MODE
        LDR      r0,|L18.240|
        ADDS     r0,r0,#0x80
        STR      r5,[r0,#0]
        MOVS     r0,#0xff
        ADDS     r0,r0,#0x2d
        BL       sysDelayMs
        MOVS     r0,#0xff
        LDR      r1,[r4,#8]
        ADDS     r0,#1
        BICS     r1,r1,r0
        STR      r1,[r4,#8]
        BL       closeMcuCtrlPin
        MOVS     r1,#0x3f
        LDR      r0,|L18.268|
        BL       DrvUART_DisableInt
        BL       initIRKeyPool
        LDR      r4,|L18.240|
        ADDS     r4,r4,#0x2c
        B        |L18.210|
|L18.204|
        MOVS     r0,#0x14
        BL       sysDelayMs
|L18.210|
        LDR      r0,[r4,#0]
        CMP      r0,#0
        BNE      |L18.204|
        BL       DECT_DC
        CMP      r0,#0
        BNE      |L18.228|
        BL       doPowerOff
|L18.228|
        LDR      r0,|L18.272|
        LDR      r1,|L18.276|
        LDRB     r0,[r0,#4]  ; volume_store
        STR      r0,[r1,#0]  ; amp_volume
        POP      {r4-r6,pc}
        ENDP

        DCW      0x0000
|L18.240|
        DCD      0x50004234
|L18.244|
        DCD      dev_state
|L18.248|
        DCD      state_color
|L18.252|
        DCD      flash_mode
|L18.256|
        DCD      0x50000200
|L18.260|
        DCD      0x50000040
|L18.264|
        DCD      0x50004080
|L18.268|
        DCD      0x40050000
|L18.272|
        DCD      ||area_number.27||
|L18.276|
        DCD      amp_volume

        AREA ||i.powerOn||, CODE, READONLY, ALIGN=2

powerOn PROC
        PUSH     {r3-r7,lr}
        MOVS     r0,#0x32
        BL       sysDelayMs
        LDR      r6,|L19.184|
        MOVS     r5,#0
        STR      r5,[r6,#0]
        MOVS     r4,#1
        ADDS     r0,r6,#4
        STR      r4,[r0,#0]
        LDR      r0,|L19.184|
        ADDS     r0,r0,#0x80
        STR      r4,[r0,#0]
        BL       openMcuCtrlPin
        MOVS     r0,#0x64
        BL       sysDelayMs
        LDR      r7,|L19.184|
        ADDS     r7,r7,#0x30
        STR      r5,[r7,#0]
        MOVS     r0,#0x64
        BL       sysDelayMs
        LDR      r0,|L19.188|
        BL       I2SClkInit
        BL       BTInit
        MOVS     r0,#0x64
        BL       sysDelayMs
        STR      r4,[r7,#0]
        BL       i2cSysInit
        MOVS     r0,#0x64
        BL       sysDelayMs
        STR      r4,[r6,#0]
        BL       i2sStart
        MOVS     r0,#0x64
        BL       sysDelayMs
        BL       mute
        MOVS     r1,#0x3f
        MOVS     r0,#0
        BL       ampSendEqs_38
        MOVS     r1,#0x3f
        MOVS     r0,#0
        BL       ampSendEqs_38b
        MOVS     r1,#0x3f
        MOVS     r0,#0
        BL       ampSendEqs_3A
        BL       ampInitAllConf
        MOVS     r0,#5
        BL       sysDelayMs
        BL       seW58DefaultVolume
        BL       seW58sendCmd
        MOVS     r0,#5
        BL       sysDelayMs
        MOVS     r0,#0
        BL       seW58SetBypass
        BL       seW58sendCmd
        MOVS     r0,#5
        BL       sysDelayMs
        LDR      r0,|L19.192|
        LDR      r0,[r0,#0]  ; amp_volume
        BL       ampSetVolume
        BL       pcm5121Init
        MOVS     r0,#0x64
        BL       sysDelayMs
        MOVS     r0,#0x7d
        LSLS     r0,r0,#3
        BL       sysDelayMs
        POP      {r3-r7,pc}
        ENDP

|L19.184|
        DCD      0x50004234
|L19.188|
        DCD      0x0000bb80
|L19.192|
        DCD      amp_volume

        AREA ||i.resetHook||, CODE, READONLY, ALIGN=2

resetHook PROC
        PUSH     {r4,lr}
        LDR      r0,|L20.48|
        LDR      r0,[r0,#0]
        MOVS     r1,#4
        TST      r0,r1
        BEQ      |L20.16|
        BL       WDT_CLEAR_RESET_FLAG
|L20.16|
        LDR      r1,|L20.52|
        MOVS     r0,#1
        STR      r0,[r1,#0]
        MOV      r2,r0
        MOVS     r1,#0xe
        LDR      r0,|L20.56|
        BL       GPIO_SET_MODE
        LDR      r0,|L20.56|
        MOVS     r2,#0
        MOVS     r1,#8
        ADDS     r0,r0,#0x40
        BL       GPIO_SET_MODE
        POP      {r4,pc}
        ENDP

        DCW      0x0000
|L20.48|
        DCD      0x40004000
|L20.52|
        DCD      0x50004238
|L20.56|
        DCD      0x50004000

        AREA ||i.sleep||, CODE, READONLY, ALIGN=2

sleep PROC
        PUSH     {r3-r7,lr}
        LDR      r0,|L21.552|
        MOVS     r4,#0
        STR      r4,[r0,#0]
        LDR      r0,|L21.552|
        ADDS     r0,r0,#0x7c
        STR      r4,[r0,#0]
        BL       closeMcuCtrlPin
|L21.18|
        LDR      r5,|L21.556|
        MOVS     r2,#0
        MOVS     r1,#8
        MOV      r0,r5
        BL       GPIO_SET_MODE
        LDR      r0,|L21.556|
        MOVS     r2,#0
        MOVS     r1,#0xf
        SUBS     r0,r0,#0x40
        BL       GPIO_SET_MODE
        MOVS     r2,#0
        MOVS     r1,#0xa
        MOV      r0,r5
        BL       GPIO_SET_MODE
        B        |L21.60|
|L21.54|
        MOVS     r0,#0x14
        BL       sysDelayMs
|L21.60|
        LDR      r0,|L21.552|
        ADDS     r0,r0,#0x28
        LDR      r0,[r0,#0]
        CMP      r0,#0
        BNE      |L21.54|
        LDR      r0,|L21.552|
        ADDS     r0,r0,#0x8c
        STR      r4,[r0,#0]
        LDR      r0,|L21.556|
        MOVS     r2,#1
        MOV      r1,r2
        ADDS     r0,r0,#0x80
        BL       GPIO_SET_MODE
        BL       SYS_UnlockReg
        LDR      r1,|L21.560|
        MOVS     r0,#4
        LDR      r6,|L21.564|
        STR      r0,[r1,#0x10]
        LDR      r0,[r6,#0x10]  ; pwrcon
        MOVS     r2,#0x10
        LDR      r1,[r0,#0]
        LSLS     r7,r2,#4
        BICS     r1,r1,r2
        ORRS     r1,r1,r7
        MOVS     r2,#0x20
        BICS     r1,r1,r2
        MOVS     r2,#0x89
        ORRS     r1,r1,r2
        STR      r1,[r0,#0]
        LDR      r0,|L21.568|
        STR      r4,[r0,#0]
        BL       DrvADC_DisableInt
        LDR      r0,|L21.572|
        LDR      r0,[r0,#0x10]
        MOVS     r1,#2
        BICS     r0,r0,r1
        LDR      r1,|L21.572|
        STR      r0,[r1,#0x10]
        LDR      r0,|L21.576|
        LDR      r0,[r0,#0]
        MOVS     r1,#2
        BICS     r0,r0,r1
        LDR      r1,|L21.576|
        STR      r0,[r1,#0]
        LDR      r1,|L21.580|
        MOVS     r0,#0x55
        STRB     r0,[r1,#0]
        MOVS     r1,#0x3f
        LDR      r0,|L21.584|
        BL       DrvUART_DisableInt
        LDR      r0,[r5,#0x14]
        ORRS     r0,r0,r7
        STR      r0,[r5,#0x14]
        LDR      r1,|L21.588|
        LSLS     r0,r7,#10
        STR      r0,[r1,#0]
        LDR      r2,|L21.592|
        LSLS     r0,r0,#11
        LDR      r1,[r2,#8]
        BICS     r1,r1,r0
        STR      r1,[r2,#8]
        LDR      r0,|L21.596|
        BL       DrvTIMER_DisableInt
        LDR      r0,|L21.552|
        ADDS     r0,r0,#0x8c
        STR      r4,[r0,#0]
        BL       I2S_DISABLE_MCK
        LDR      r7,|L21.600|
        MOVS     r1,#8
        MOV      r2,r7
        MOV      r0,r5
        BL       GPIO_EnableInt
        LDR      r0,|L21.556|
        MOV      r2,r7
        MOVS     r1,#0xf
        SUBS     r0,r0,#0x40
        BL       GPIO_EnableInt
        LDR      r2,|L21.604|
        MOVS     r1,#0xa
        MOV      r0,r5
        BL       GPIO_EnableInt
        LDR      r0,|L21.588|
        MOVS     r1,#0x10
        SUBS     r0,r0,#0x80
        STR      r1,[r0,#0]
        STR      r4,[r6,#0xc]  ; gpio_int
        MOV      r7,r5
        MOVS     r5,#1
        STR      r4,[r6,#8]  ; wdt_timer
|L21.256|
        LDR      r6,|L21.600|
        LDR      r0,|L21.556|
        MOV      r2,r6
        MOVS     r1,#0xf
        SUBS     r0,r0,#0x40
        BL       GPIO_EnableInt
        LDR      r2,|L21.604|
        MOVS     r1,#0xa
        MOV      r0,r7
        BL       GPIO_EnableInt
        MOV      r2,r6
        MOVS     r1,#8
        MOV      r0,r7
        BL       GPIO_EnableInt
        LDR      r6,|L21.564|
        STR      r4,[r6,#0x14]  ; recode_t
        WFI      
        LDR      r0,|L21.608|
        BL       sysDelayUs
        LDR      r0,|L21.612|
        LDR      r1,|L21.616|
        LDR      r0,[r0,#0]  ; ir_key_bits
        CMP      r0,r1
        BEQ      |L21.318|
        LSLS     r0,r0,#1
        CMP      r0,r1
        BNE      |L21.322|
|L21.318|
        STR      r5,[r6,#0x14]  ; recode_t
        STR      r5,[r6,#0xc]  ; gpio_int
|L21.322|
        LDR      r0,[r6,#0xc]  ; gpio_int
        CMP      r0,#1
        BEQ      |L21.380|
        BL       SYS_UnlockReg
        LDR      r0,|L21.560|
        MOVS     r1,#4
        STR      r1,[r0,#0x10]
        LDR      r0,[r6,#0x10]  ; pwrcon
        MOVS     r2,#0x10
        LDR      r1,[r0,#0]
        LSLS     r3,r2,#4
        BICS     r1,r1,r2
        ORRS     r1,r1,r3
        MOVS     r3,#0x20
        BICS     r1,r1,r3
        MOVS     r3,#0x88
        ORRS     r1,r1,r3
        ORRS     r1,r1,r5
        STR      r1,[r0,#0]
        LDR      r0,|L21.568|
        STR      r4,[r0,#0]
        LDR      r0,|L21.588|
        SUBS     r0,r0,#0x80
        STR      r2,[r0,#0]
        LDR      r0,|L21.552|
        ADDS     r0,r0,#0x8c
        STR      r4,[r0,#0]
        B        |L21.256|
|L21.380|
        BL       DrvWDT_DisableInt
        LDR      r1,|L21.552|
        MOVS     r0,#0x30
        SUBS     r1,r1,#0xb8
        STR      r0,[r1,#0]
        LDR      r0,|L21.572|
        LDR      r1,[r0,#0x10]
        MOVS     r2,#2
        ORRS     r1,r1,r2
        STR      r1,[r0,#0x10]
        LDR      r0,|L21.552|
        STR      r5,[r0,#0]
        LDR      r0,|L21.556|
        MOVS     r2,#1
        MOVS     r1,#0xe
        SUBS     r0,r0,#0x40
        BL       GPIO_SET_MODE
        MOVS     r0,#0x64
        BL       sysDelayMs
        LDR      r5,|L21.564|
        STR      r4,[r5,#0xc]  ; gpio_int
        BL       DECT_DC
        CMP      r0,#0
        BEQ      |L21.456|
        LDR      r0,|L21.552|
        ADDS     r0,r0,#0x28
        LDR      r0,[r0,#0]
        CMP      r0,#0
        BNE      |L21.468|
        LDR      r0,|L21.552|
        ADDS     r0,r0,#0x30
        LDR      r0,[r0,#0]
        CMP      r0,#0
        BNE      |L21.468|
|L21.456|
        LDR      r0,[r5,#0x14]  ; recode_t
        CMP      r0,#1
        BEQ      |L21.468|
        BL       doPowerOff
        B        |L21.18|
|L21.468|
        LDR      r0,|L21.552|
        ADDS     r0,r0,#0x30
        LDR      r0,[r0,#0]
        CMP      r0,#0
        BEQ      |L21.488|
        LDR      r1,|L21.620|
        MOVS     r0,#1
        STRB     r0,[r1,#0]
        LDR      r1,|L21.564|
        STRB     r0,[r1,#0]
|L21.488|
        MOVS     r1,#1
        LSLS     r1,r1,#29
        LDR      r0,|L21.596|
        BL       DrvTIMER_EnableInt
        BL       taskFlush
        BL       irKeyTaskInit
        BL       ledTaskInit
        BL       adckeyTaskInit
        BL       cs8422Init
        BL       seW58Init
        BL       DWPH83Init
        LDR      r1,|L21.628|
        LDR      r0,|L21.624|
        LDRB     r1,[r1,#0]  ; dev_input
        LDRB     r0,[r0,r1]
        LDR      r1,|L21.632|
        STRB     r0,[r1,#0]
        BL       ledColorSet
        LDR      r0,|L21.636|
        STR      r4,[r0,#0]  ; dc_time_stamp
        BL       outStandby
        POP      {r3-r7,pc}
        ENDP

|L21.552|
        DCD      0x50004238
|L21.556|
        DCD      0x50004040
|L21.560|
        DCD      0xe000ed00
|L21.564|
        DCD      ||area_number.27||
|L21.568|
        DCD      0x50000100
|L21.572|
        DCD      0xe000e000
|L21.576|
        DCD      0x40004000
|L21.580|
        DCD      last_key
|L21.584|
        DCD      0x40050000
|L21.588|
        DCD      0xe000e180
|L21.592|
        DCD      0x50000200
|L21.596|
        DCD      0x40010000
|L21.600|
        DCD      0x80010000
|L21.604|
        DCD      0x00010001
|L21.608|
        DCD      0x000186a0
|L21.612|
        DCD      ir_key_bits
|L21.616|
        DCD      0xf40bff00
|L21.620|
        DCD      bt_paring_flag
|L21.624|
        DCD      input_channel_color
|L21.628|
        DCD      dev_input
|L21.632|
        DCD      state_color
|L21.636|
        DCD      dc_time_stamp

        AREA ||i.sysResume||, CODE, READONLY, ALIGN=1

sysResume PROC
        BX       lr
        ENDP


        AREA ||i.sysStore||, CODE, READONLY, ALIGN=1

sysStore PROC
        BX       lr
        ENDP


        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.data||, DATA, ALIGN=0

wdt_handler
        DCB      0x00

        AREA ||area_number.27||, DATA, ALIGN=2

        EXPORTAS ||area_number.27||, ||.data||
NFC_flag
        DCB      0x00
enter_standby_flag
        DCB      0x00
power_first_on_flag
        DCB      0x00
factory_mode_flag
        DCB      0x00
volume_store
        DCB      0x18
sleep_flag
        DCB      0x00,0x00,0x00
wdt_timer
        DCD      0x00000000
gpio_int
        DCD      0x00000000
pwrcon
        DCD      0x50000200
recode_t
        DCD      0x00000000

        AREA ||area_number.28||, DATA, ALIGN=0

        EXPORTAS ||area_number.28||, ||.data||
battery_state
        DCB      0x00

        EXPORT GPAB_IRQHandler [CODE]
        EXPORT PWRWU_IRQHandler [CODE]
        EXPORT WDTInit [CODE]
        EXPORT WDT_IRQHandler [CODE]
        EXPORT dealPowerKey [CODE]
        EXPORT doPowerOff [CODE]
        EXPORT enterStandby [CODE]
        EXPORT outStandby [CODE]
        EXPORT powerOff [CODE]
        EXPORT powerOn [CODE]
        EXPORT resetHook [CODE]
        EXPORT sleep [CODE]
        EXPORT sysResume [CODE]
        EXPORT sysStore [CODE]
        EXPORT wdt_handler [DATA,SIZE=1]
        EXPORT NFC_flag [DATA,SIZE=1]
        EXPORT enter_standby_flag [DATA,SIZE=1]
        EXPORT power_first_on_flag [DATA,SIZE=1]
        EXPORT factory_mode_flag [DATA,SIZE=1]
        EXPORT volume_store [DATA,SIZE=1]
        EXPORT sleep_flag [DATA,SIZE=1]
        EXPORT wdt_timer [DATA,SIZE=4]
        EXPORT gpio_int [DATA,SIZE=4]
        EXPORT pwrcon [DATA,SIZE=4]
        EXPORT recode_t [DATA,SIZE=4]
        EXPORT battery_state [DATA,SIZE=1]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT sysDelayUs [CODE]
        IMPORT sysDelayMs [CODE]
        IMPORT adcReadKey [CODE]
        IMPORT dc_time_stamp [DATA]
        IMPORT DrvWDT_DisableInt [CODE]
        IMPORT ledColorSet [CODE]
        IMPORT DrvWDT_Init [CODE]
        IMPORT DrvWDT_EnableInt [CODE]
        IMPORT I2SClkInit [CODE]
        IMPORT BTInit [CODE]
        IMPORT i2cSysInit [CODE]
        IMPORT i2sStart [CODE]
        IMPORT mute [CODE]
        IMPORT ampSendEqs_38 [CODE]
        IMPORT ampSendEqs_38b [CODE]
        IMPORT ampSendEqs_3A [CODE]
        IMPORT ampInitAllConf [CODE]
        IMPORT seW58DefaultVolume [CODE]
        IMPORT seW58sendCmd [CODE]
        IMPORT seW58SetBypass [CODE]
        IMPORT ampSetVolume [CODE]
        IMPORT pcm5121Init [CODE]
        IMPORT amp_volume [DATA]
        IMPORT resumeI2c [CODE]
        IMPORT getConfig [CODE]
        IMPORT set_local_coco [CODE]
        IMPORT set_soundbar_coco [CODE]
        IMPORT Dwhp83CuMuDetect [CODE]
        IMPORT Dwhp83Master [CODE]
        IMPORT SUB_volume_unmute [CODE]
        IMPORT Dwhp83Slave [CODE]
        IMPORT spiFlashInit [CODE]
        IMPORT playMusic [CODE]
        IMPORT unMute [CODE]
        IMPORT cs8422InitAllConf [CODE]
        IMPORT btDisableHFP [CODE]
        IMPORT readeeprom [CODE]
        IMPORT local_coco_check [CODE]
        IMPORT soundbar_coco_check [CODE]
        IMPORT bt_amp_start_flag [DATA]
        IMPORT dev_state [DATA]
        IMPORT cc_blue_p [DATA]
        IMPORT BAT_STATE_DECT_DELAY_COUNT [DATA]
        IMPORT dev_input [DATA]
        IMPORT input_channel_color [DATA]
        IMPORT state_color [DATA]
        IMPORT SB_flag [DATA]
        IMPORT Dwhp83_flag [DATA]
        IMPORT Dwhp83_CuMu [DATA]
        IMPORT bt_hfp_flag [DATA]
        IMPORT DrvADC_DisableInt [CODE]
        IMPORT DrvUART_DisableInt [CODE]
        IMPORT DrvTIMER_DisableInt [CODE]
        IMPORT DrvTIMER_EnableInt [CODE]
        IMPORT taskFlush [CODE]
        IMPORT irKeyTaskInit [CODE]
        IMPORT ledTaskInit [CODE]
        IMPORT adckeyTaskInit [CODE]
        IMPORT cs8422Init [CODE]
        IMPORT seW58Init [CODE]
        IMPORT DWPH83Init [CODE]
        IMPORT last_key [DATA]
        IMPORT ir_key_bits [DATA]
        IMPORT bt_paring_flag [DATA]
        IMPORT stopFlashLed [CODE]
        IMPORT ampPowerDown [CODE]
        IMPORT initIRKeyPool [CODE]
        IMPORT flash_mode [DATA]
        IMPORT testOutputSpeakers [CODE]
        IMPORT DWHP83toEXT_MCU [CODE]
        IMPORT writeDwhp83 [CODE]
        IMPORT setConfig [CODE]
        IMPORT DWHP83Mute [CODE]
        IMPORT DWHP83UnMute [CODE]
        IMPORT btShutDown [CODE]
        IMPORT seW58SetVolume [CODE]
        IMPORT test_channel [DATA]
        IMPORT IR_IRQHandler [CODE]

        KEEP DECT_DC
        KEEP GPIO_DisableInt
        KEEP GPIO_EnableInt
        KEEP GPIO_SET_MODE
        KEEP I2S_DISABLE_MCK
        KEEP SYS_UnlockReg
        KEEP WDT_CLEAR_RESET_FLAG
        KEEP closeMcuCtrlPin
        KEEP openMcuCtrlPin

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,3
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
