/****************************************************************************
 * @file:		datalog.h
 * @version:		
 * @breif:		
 * @date: 		
 * 
 * @note 		
 *  Copyright (C) 2013-2015 Globla silicon . All rights reserved.
 * 
 ****************************************************************************/
#ifndef _datalog_h_
#define _datalog_h_

#define EPROM_FULL		(0xAA)
#define EPROM_EMPTY	(0XA5)
#define EPROM_USING		(0XA3)

typedef enum {
	un_used,
	Time_stamp_wrapped,
	Power_up_sequence_started,
	Power_down_sequence_started,
	Amplifier_mute,
	Amplifier_unmute,
	System_power_on,
	System_standby,
	system_power_off,
	NFC_touch_detected,
	NFC_removed,
	key_power_pressed,
	key_vol_add_pressed,
	key_vol_dec_pressed,
	key_source_pressed,
	key_source_long_pressed,
	key_u_pressed,
	key_v_pressed,
	key_w_pressed,
	key_x_pressed,
	key_y_pressed,
	key_z_pressed,
	RC_key1_pressed,
	RC_key2_pressed,
	RC_key3_pressed,
	RC_key4_pressed,
	RC_key5_pressed,
	RC_key6_pressed,
	RC_key7_pressed,
	RC_key8_pressed,
	RC_key9_pressed,
	RC_key10_pressed,
	RC_key11_pressed,
	RC_key12_pressed,
	RC_key13_pressed,
	RC_key14_pressed,
	RC_key15_pressed,
	RC_key16_pressed,
	RC_key17_pressed,
	RC_key18_pressed,
	RC_key19_pressed,
	RC_key20_pressed,
	RC_key21_pressed,
	RC_key22_pressed,
	RC_key23_pressed,
	RC_key24_pressed,
	RC_key25_pressed,
	RC_key26_pressed,
	RC_key27_pressed,
	RC_key28_pressed,
	RC_key29_pressed,
	RC_key30_pressed,
	RC_key31_pressed,
	RC_key32_pressed,
	call_in,
	call_out,
	call_pickup,
	call_hangup,
	bt_pairing,
	bt_paired,
	bt_power_down,
	bt_disconnect,
	demo_mode_pressed,
	Gesture_event1,
	Gesture_event2,
	Gesture_event3,
	Gesture_event4,
	Gesture_event5,
	Gesture_event6,
	Gesture_event7,
	amp_init_start,
	amp_init_ok,
	amp_i2c_werror,
	amp_i2c_rerror,
	Main_enclosure_over_temp_warning,
	Amplifier1_over_temp_warning,
	Amplifier2_over_temp_warning,
	Amplifier3_over_temp_warning,
	Amplifier1_thermal_shutdown,
	Amplifier2_thermal_shutdown,
	Amplifier3_thermal_shutdown,
	Amplifier1_overcurrent_shutdown,
	Amplifier2_overcurrent_shutdown,
	Amplifier3_overcurrent_shutdown,
	GSensor_event1,
	GSensor_event2,
	GSensor_event3,
	GSensor_event4,
	GSensor_event5,
	GSensor_event6,
	GSensor_event7,
	GSensor_event8,
	GSensor_event9,
	GSensor_event10,
	Overvoltage_on_DC_input,
	Battery_full,
	Battery_low,
	Battery_chargin,
	DC_inserted,
	DC_removed,
	Phone_call_detected,
	Phone_call_ended,
	SPDIF_source1_detected,
	SPDIF_source2_detected,
	SPDIF_source3_detected,
	SPDIF_source4_detected,
	BLUETOOTH_SOURE_IN,
	AUX_SOURCE_IN,
	LINEIN_SOURE_IN,
	Flash_audio_track1_started,
	Flash_audio_track2_started, 
	Flash_audio_track3_started,
	Flash_audio_track4_started,
	Flash_audio_track5_started,
	Flash_audio_track6_started,
	Flash_audio_track7_started,
	Flash_audio_track8_started,
	Flash_audio_track1_finished,
	Flash_audio_track2_finished,
	Flash_audio_track3_finished,
	Flash_audio_track4_finished,
	Flash_audio_track5_finished,
	Flash_audio_track6_finished,
	Flash_audio_track7_finished,
	Flash_audio_track8_finished,
	BT_in_pairing_mode,
	BT_forced_into_pairing_mode,
	BT_pairing_complete,
	No_audio_present_for10_mins,
	No_audio_present_for30_mins,
	Led_dark_color,
	Led_red_color,
	Led_green_color,
	Led_blue_color,
	Led_yellow_color,
	Led_purple_color,
	Led_white_color,
	Led_soe_color,
	Led_light_blue_color,
	Led_bluetooth_color,
	flash_error_page,
	watch_dog_reset,
}Log_Type;


extern Log_Type event;
extern void logInit(void);
extern void logEvent(Log_Type data);
extern void earseAllLog(void);

extern void logClose(void);
extern void printLog(u32 addr, u32 flag);
#endif

