; generated by ARM C/C++ Compiler, 5.03 [Build 76]
; commandline ArmCC [--debug -c --asm --info=totals -o.\output\cs8422.o --depend=.\output\cs8422.d --cpu=Cortex-M0 --apcs=interwork -O0 -I..\CMSIS\CM0\DeviceSupport\Nuvoton\NUC123Series -I..\CMSIS\CM0\CoreSupport -I..\INC\DrvInc -I..\INC\SysInc -IC:\Keil_v472\ARM\RV31\INC -IC:\Keil_v472\ARM\CMSIS\Include -D__MICROLIB --omf_browse=.\output\cs8422.crf ..\AppSrc\cs8422.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

cs8422SendCmd PROC
        PUSH     {r2-r6,lr}
        MOV      r4,r0
        MOV      r5,r1
        LDR      r0,|L1.732|
        MOVS     r1,#1
        MOVS     r3,#2
        MOVS     r2,#0
        STR      r1,[sp,#0]
        STR      r0,[sp,#4]
        MOVS     r1,#0x2e
        LDR      r0,|L1.736|
        BL       initI2cDataBlock
        LDR      r0,|L1.732|
        STRB     r4,[r0,#1]
        STRB     r5,[r0,#2]
        MOVS     r0,#0xa2
        LDR      r1,|L1.732|
        STRB     r0,[r1,#0]
        MOVS     r1,#0
        LDR      r0,|L1.736|
        BL       addI2cChain
        NOP      
|L1.48|
        LDR      r0,|L1.732|
        LDRB     r0,[r0,#0]  ; cs8422_status
        CMP      r0,#0xa2
        BEQ      |L1.48|
        POP      {r2-r6,pc}
        ENDP

cs8422SRCSourceSDIN PROC
        PUSH     {r4,lr}
        MOVS     r1,#0
        MOVS     r0,#0xa
        BL       cs8422SendCmd
        POP      {r4,pc}
        ENDP

cs8422SRCSourceAES3 PROC
        PUSH     {r4,lr}
        MOVS     r1,#2
        MOVS     r0,#0xa
        BL       cs8422SendCmd
        POP      {r4,pc}
        ENDP

cs8422AESRX2 PROC
        PUSH     {r4,lr}
        MOVS     r1,#0xd4
        MOVS     r0,#3
        BL       cs8422SendCmd
        POP      {r4,pc}
        ENDP

getMuAddr PROC
        PUSH     {r4,lr}
        NOP      
        NOP      
        BL       cs8422SRCSourceSDIN
        LDR      r0,|L1.740|
        BL       sysDelayMs
        LDR      r0,|L1.744|
        LDR      r0,[r0,#0]  ; sum_H
        LSLS     r0,r0,#8
        LSRS     r0,r0,#16
        LDR      r1,|L1.748|
        STRH     r0,[r1,#0]
        MOV      r0,r1
        LDRH     r0,[r0,#0]  ; mu_addr
        CMP      r0,#8
        BGE      |L1.142|
        MOV      r0,r1
        LDRB     r0,[r0,#0]  ; mu_addr
        ADDS     r0,r0,#3
        LSLS     r0,r0,#24
        LSRS     r0,r0,#16
        STRH     r0,[r1,#0]
|L1.142|
        POP      {r4,pc}
        ENDP

cs8422InitAllConf PROC
        PUSH     {r4,lr}
        MOVS     r1,#0
        MOVS     r0,#2
        BL       cs8422SendCmd
        MOVS     r1,#0xc4
        MOVS     r0,#3
        BL       cs8422SendCmd
        MOVS     r1,#4
        MOV      r0,r1
        BL       cs8422SendCmd
        MOVS     r1,#0x40
        MOVS     r0,#8
        BL       cs8422SendCmd
        MOVS     r1,#8
        MOVS     r0,#9
        BL       cs8422SendCmd
        MOVS     r1,#0
        MOVS     r0,#0xa
        BL       cs8422SendCmd
        MOVS     r1,#8
        MOVS     r0,#0xb
        BL       cs8422SendCmd
        MOVS     r1,#4
        MOVS     r0,#0xc
        BL       cs8422SendCmd
        BL       getMuAddr
        LDR      r0,|L1.752|
        LDRB     r0,[r0,#0]  ; dev_input
        CMP      r0,#0
        BNE      |L1.238|
        MOVS     r0,#0x14
        BL       sysDelayMs
        NOP      
        NOP      
        BL       cs8422SRCSourceSDIN
        B        |L1.348|
|L1.238|
        LDR      r0,|L1.752|
        LDRB     r0,[r0,#0]  ; dev_input
        CMP      r0,#2
        BNE      |L1.268|
        MOVS     r0,#0x14
        BL       sysDelayMs
        MOVS     r0,#0
        LDR      r1,|L1.756|
        STR      r0,[r1,#0]  ; BT_MATCH_FLAG
        NOP      
        NOP      
        BL       cs8422SRCSourceSDIN
        B        |L1.348|
|L1.268|
        LDR      r0,|L1.752|
        LDRB     r0,[r0,#0]  ; dev_input
        CMP      r0,#3
        BNE      |L1.298|
        MOVS     r0,#0x14
        BL       sysDelayMs
        MOVS     r0,#0
        LDR      r1,|L1.756|
        STR      r0,[r1,#0]  ; BT_MATCH_FLAG
        BL       cs8422AESRX2
        BL       cs8422SRCSourceAES3
        B        |L1.348|
|L1.298|
        LDR      r0,|L1.752|
        LDRB     r0,[r0,#0]  ; dev_input
        CMP      r0,#1
        BNE      |L1.348|
        MOVS     r0,#0x14
        BL       sysDelayMs
        MOVS     r0,#0
        LDR      r1,|L1.756|
        STR      r0,[r1,#0]  ; BT_MATCH_FLAG
        BL       Dwhp83CuMuDetect
        LDR      r0,|L1.760|
        LDR      r0,[r0,#0]  ; Dwhp83_CuMu
        LDR      r1,|L1.764|
        CMP      r0,r1
        BNE      |L1.336|
        BL       Dwhp83Slave
|L1.336|
        NOP      
        NOP      
        NOP      
        NOP      
        BL       cs8422SRCSourceSDIN
|L1.348|
        POP      {r4,pc}
        ENDP

DETECT_USER_MODULE PROC
        PUSH     {r4,lr}
        BL       Dwhp83CuMuDetect
        CMP      r0,#0
        BNE      |L1.362|
|L1.360|
        POP      {r4,pc}
|L1.362|
        MOVS     r0,#1
        B        |L1.360|
        ENDP

getNextInput PROC
        PUSH     {r4,lr}
        BL       DETECT_USER_MODULE
        CMP      r0,#0
        BEQ      |L1.448|
        LDR      r0,|L1.768|
        LDRB     r0,[r0,#0]  ; total_input_channel
        LDR      r1,|L1.772|
        STRB     r0,[r1,#0]
        MOVS     r0,#4
        LDR      r1,|L1.768|
        STR      r0,[r1,#0]  ; total_input_channel
        LDR      r0,|L1.752|
        LDRB     r0,[r0,#0]  ; dev_input
        CMP      r0,#0
        BEQ      |L1.412|
        CMP      r0,#1
        BEQ      |L1.420|
        CMP      r0,#2
        BEQ      |L1.428|
        CMP      r0,#3
        BNE      |L1.444|
        B        |L1.436|
|L1.412|
        MOVS     r0,#1
        LDR      r1,|L1.752|
        STRB     r0,[r1,#0]
|L1.418|
        POP      {r4,pc}
|L1.420|
        MOVS     r0,#2
        LDR      r1,|L1.752|
        STRB     r0,[r1,#0]
        B        |L1.418|
|L1.428|
        MOVS     r0,#3
        LDR      r1,|L1.752|
        STRB     r0,[r1,#0]
        B        |L1.418|
|L1.436|
        MOVS     r0,#0
        LDR      r1,|L1.752|
        STRB     r0,[r1,#0]
        B        |L1.418|
|L1.444|
        NOP      
        B        |L1.514|
|L1.448|
        LDR      r0,|L1.768|
        LDRB     r0,[r0,#0]  ; total_input_channel
        LDR      r1,|L1.772|
        STRB     r0,[r1,#0]
        MOVS     r0,#3
        LDR      r1,|L1.768|
        STR      r0,[r1,#0]  ; total_input_channel
        LDR      r0,|L1.752|
        LDRB     r0,[r0,#0]  ; dev_input
        CMP      r0,#0
        BEQ      |L1.480|
        CMP      r0,#2
        BEQ      |L1.488|
        CMP      r0,#3
        BNE      |L1.504|
        B        |L1.496|
|L1.480|
        MOVS     r0,#2
        LDR      r1,|L1.752|
        STRB     r0,[r1,#0]
        B        |L1.418|
|L1.488|
        MOVS     r0,#3
        LDR      r1,|L1.752|
        STRB     r0,[r1,#0]
        B        |L1.418|
|L1.496|
        MOVS     r0,#0
        LDR      r1,|L1.752|
        STRB     r0,[r1,#0]
        B        |L1.418|
|L1.504|
        MOVS     r0,#2
        LDR      r1,|L1.752|
        STRB     r0,[r1,#0]
        NOP      
        NOP      
|L1.514|
        MOVS     r0,#0
        B        |L1.418|
        ENDP

changeInputChannel PROC
        PUSH     {r4,lr}
        MOVS     r0,#0x32
        BL       sysDelayMs
        LDR      r0,|L1.752|
        LDRB     r0,[r0,#0]  ; dev_input
        CMP      r0,#0
        BNE      |L1.548|
        LDR      r1,|L1.776|
        STRB     r0,[r1,#0]
        NOP      
        NOP      
        BL       cs8422SRCSourceSDIN
        B        |L1.648|
|L1.548|
        LDR      r0,|L1.752|
        LDRB     r0,[r0,#0]  ; dev_input
        CMP      r0,#2
        BNE      |L1.572|
        MOVS     r0,#0
        LDR      r1,|L1.756|
        STR      r0,[r1,#0]  ; BT_MATCH_FLAG
        NOP      
        NOP      
        BL       cs8422SRCSourceSDIN
        B        |L1.648|
|L1.572|
        LDR      r0,|L1.752|
        LDRB     r0,[r0,#0]  ; dev_input
        CMP      r0,#3
        BNE      |L1.596|
        MOVS     r0,#0
        LDR      r1,|L1.756|
        STR      r0,[r1,#0]  ; BT_MATCH_FLAG
        BL       cs8422AESRX2
        BL       cs8422SRCSourceAES3
        B        |L1.648|
|L1.596|
        LDR      r0,|L1.752|
        LDRB     r0,[r0,#0]  ; dev_input
        CMP      r0,#1
        BNE      |L1.648|
        MOVS     r0,#0
        LDR      r1,|L1.756|
        STR      r0,[r1,#0]  ; BT_MATCH_FLAG
        BL       Dwhp83CuMuDetect
        LDR      r0,|L1.760|
        LDR      r0,[r0,#0]  ; Dwhp83_CuMu
        LDR      r1,|L1.764|
        CMP      r0,r1
        BNE      |L1.636|
        LDR      r0,|L1.780|
        LDRB     r0,[r0,#0]  ; SB_flag
        CMP      r0,#0
        BNE      |L1.636|
        BL       Dwhp83Slave
|L1.636|
        NOP      
        NOP      
        NOP      
        NOP      
        BL       cs8422SRCSourceSDIN
|L1.648|
        BL       unMute
        BL       changeInputVolumeUp
        BL       DWHP83UnMute
        POP      {r4,pc}
        ENDP

InputChannelCheck PROC
        PUSH     {r4,lr}
        LDR      r0,|L1.736|
        LDR      r0,[r0,#8]  ; cs8422_i2c_block
        LDRB     r0,[r0,#0]
        CMP      r0,#0xa0
        BNE      |L1.676|
|L1.674|
        POP      {r4,pc}
|L1.676|
        LDR      r0,|L1.736|
        LDR      r0,[r0,#8]  ; cs8422_i2c_block
        LDRB     r0,[r0,#0]
        CMP      r0,#0xa2
        BNE      |L1.702|
        LDR      r3,|L1.784|
        MOVS     r2,#0
        MOVS     r1,#2
        LDR      r0,|L1.788|
        LDRB     r0,[r0,#0]  ; sew58_id_CIC
        BL       startATask
        B        |L1.674|
|L1.702|
        BL       changeInputChannel
        NOP      
        B        |L1.674|
        ENDP

cs8422Init PROC
        PUSH     {r4,lr}
        BL       getATask
        LDR      r1,|L1.792|
        STRB     r0,[r1,#0]
        BL       getATask
        LDR      r1,|L1.788|
        STRB     r0,[r1,#0]
        POP      {r4,pc}
        ENDP

        DCW      0x0000
|L1.732|
        DCD      cs8422_status
|L1.736|
        DCD      cs8422_i2c_block
|L1.740|
        DCD      0x000005dc
|L1.744|
        DCD      sum_H
|L1.748|
        DCD      mu_addr
|L1.752|
        DCD      dev_input
|L1.756|
        DCD      BT_MATCH_FLAG
|L1.760|
        DCD      Dwhp83_CuMu
|L1.764|
        DCD      0x000055aa
|L1.768|
        DCD      total_input_channel
|L1.772|
        DCD      last_user_module
|L1.776|
        DCD      NFC_flag
|L1.780|
        DCD      SB_flag
|L1.784|
        DCD      InputChannelCheck
|L1.788|
        DCD      sew58_id_CIC
|L1.792|
        DCD      cs8422_id

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.bss||, DATA, NOINIT, ALIGN=2

cs8422_i2c_block
        %        16

        AREA ||.data||, DATA, ALIGN=0

cs8422_id
        DCB      0xff
sew58_id_CIC
        DCB      0xff
last_user_module
        DCB      0x04
cs8422_input
        DCB      0x00
cs8422_status
        DCB      0x00,0x00,0x00

        EXPORT cs8422SendCmd [CODE]
        EXPORT cs8422SRCSourceSDIN [CODE]
        EXPORT cs8422SRCSourceAES3 [CODE]
        EXPORT cs8422AESRX2 [CODE]
        EXPORT getMuAddr [CODE]
        EXPORT cs8422InitAllConf [CODE]
        EXPORT DETECT_USER_MODULE [CODE]
        EXPORT getNextInput [CODE]
        EXPORT changeInputChannel [CODE]
        EXPORT InputChannelCheck [CODE]
        EXPORT cs8422Init [CODE]
        EXPORT cs8422_id [DATA,SIZE=1]
        EXPORT sew58_id_CIC [DATA,SIZE=1]
        EXPORT last_user_module [DATA,SIZE=1]
        EXPORT cs8422_input [DATA,SIZE=1]
        EXPORT cs8422_status [DATA,SIZE=3]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT initI2cDataBlock [CODE]
        IMPORT addI2cChain [CODE]
        IMPORT sysDelayMs [CODE]
        IMPORT sum_H [DATA]
        IMPORT mu_addr [DATA]
        IMPORT Dwhp83CuMuDetect [CODE]
        IMPORT Dwhp83Slave [CODE]
        IMPORT dev_input [DATA]
        IMPORT BT_MATCH_FLAG [DATA]
        IMPORT Dwhp83_CuMu [DATA]
        IMPORT total_input_channel [DATA]
        IMPORT unMute [CODE]
        IMPORT changeInputVolumeUp [CODE]
        IMPORT DWHP83UnMute [CODE]
        IMPORT NFC_flag [DATA]
        IMPORT SB_flag [DATA]
        IMPORT startATask [CODE]
        IMPORT getATask [CODE]

        KEEP cs8422_i2c_block

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
