; generated by ARM C/C++ Compiler, 5.03 [Build 76]
; commandline ArmCC [--debug -c --asm --info=totals -o.\output\drvpwm.o --depend=.\output\drvpwm.d --cpu=Cortex-M0 --apcs=interwork -O0 -I..\CMSIS\CM0\DeviceSupport\Nuvoton\NUC123Series -I..\CMSIS\CM0\CoreSupport -I..\INC\DrvInc -I..\INC\SysInc -IC:\Keil_v472\ARM\RV31\INC -IC:\Keil_v472\ARM\CMSIS\Include -D__MICROLIB --omf_browse=.\output\drvpwm.crf ..\DrvSrc\DrvPWM.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

DrvPWM_EnableInt PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        LDR      r0,|L1.996|
        LDR      r0,[r0,#0]
        MOVS     r1,#1
        LSLS     r1,r1,r4
        ORRS     r0,r0,r1
        LDR      r1,|L1.996|
        STR      r0,[r1,#0]
        MOVS     r0,#6
        BL       NVIC_EnableIRQ
        POP      {r4,pc}
        ENDP

DrvPWM_DisableInt PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        LDR      r0,|L1.996|
        LDR      r0,[r0,#0]
        MOVS     r1,#1
        LSLS     r1,r1,r4
        BICS     r0,r0,r1
        LDR      r1,|L1.996|
        STR      r0,[r1,#0]
        MOV      r0,r1
        LDR      r0,[r0,#0]
        LDR      r1,|L1.1000|
        TST      r0,r1
        BNE      |L1.78|
        LDR      r0,|L1.996|
        LDR      r0,[r0,#0x10]
        LDR      r1,|L1.1004|
        TST      r0,r1
        BNE      |L1.78|
        LDR      r0,|L1.996|
        LDR      r0,[r0,#0x14]
        TST      r0,r1
        BNE      |L1.78|
        MOVS     r0,#6
        BL       NVIC_DisableIRQ
|L1.78|
        POP      {r4,pc}
        ENDP

DrvPWM_EnableCaptureInt PROC
        PUSH     {r3-r7,lr}
        MOV      r4,r0
        MOV      r5,r1
        MOV      r7,r5
        CMP      r4,#2
        BGE      |L1.98|
        LDR      r0,|L1.996|
        ADDS     r0,r0,#0x10
        B        |L1.102|
|L1.98|
        LDR      r0,|L1.996|
        ADDS     r0,r0,#0x14
|L1.102|
        MOV      r6,r0
        LSLS     r0,r4,#31
        LSRS     r0,r0,#31
        BEQ      |L1.112|
        LSLS     r7,r5,#16
|L1.112|
        LDR      r0,[r6,#0]
        ORRS     r0,r0,r7
        STR      r0,[r6,#0]
        MOVS     r0,#6
        BL       NVIC_EnableIRQ
        POP      {r3-r7,pc}
        ENDP

DrvPWM_DisableCaptureInt PROC
        PUSH     {r3-r7,lr}
        MOV      r4,r0
        MOV      r5,r1
        MOV      r7,r5
        CMP      r4,#2
        BGE      |L1.144|
        LDR      r0,|L1.996|
        ADDS     r0,r0,#0x10
        B        |L1.148|
|L1.144|
        LDR      r0,|L1.996|
        ADDS     r0,r0,#0x14
|L1.148|
        MOV      r6,r0
        MOVS     r0,#2
        TST      r4,r0
        BEQ      |L1.158|
        LSLS     r7,r5,#16
|L1.158|
        LDR      r0,[r6,#0]
        BICS     r0,r0,r7
        STR      r0,[r6,#0]
        LDR      r0,|L1.996|
        LDR      r0,[r0,#0]
        LDR      r1,|L1.1000|
        TST      r0,r1
        BNE      |L1.198|
        LDR      r0,|L1.996|
        LDR      r0,[r0,#0x10]
        LDR      r1,|L1.1004|
        TST      r0,r1
        BNE      |L1.198|
        LDR      r0,|L1.996|
        LDR      r0,[r0,#0x10]
        TST      r0,r1
        BNE      |L1.198|
        MOVS     r0,#6
        BL       NVIC_DisableIRQ
|L1.198|
        POP      {r3-r7,pc}
        ENDP

DrvPWM_Init PROC
        CMP      r0,#0
        BEQ      |L1.218|
        CMP      r0,#1
        BEQ      |L1.250|
        CMP      r0,#2
        BEQ      |L1.284|
        CMP      r0,#3
        BNE      |L1.348|
        B        |L1.316|
|L1.218|
        LDR      r1,|L1.1008|
        LDR      r1,[r1,#8]
        MOVS     r2,#1
        LSLS     r2,r2,#20
        ORRS     r1,r1,r2
        LDR      r2,|L1.1008|
        STR      r1,[r2,#8]
        LDR      r1,|L1.996|
        SUBS     r1,r1,#0x40
        LDR      r1,[r1,#8]
        MOVS     r2,#1
        ORRS     r1,r1,r2
        LDR      r2,|L1.996|
        SUBS     r2,r2,#0x40
        STR      r1,[r2,#8]
        B        |L1.348|
|L1.250|
        LDR      r1,|L1.1008|
        LDR      r1,[r1,#8]
        MOVS     r2,#1
        LSLS     r2,r2,#20
        ORRS     r1,r1,r2
        LDR      r2,|L1.1008|
        STR      r1,[r2,#8]
        LDR      r1,|L1.996|
        SUBS     r1,r1,#0x40
        LDR      r1,[r1,#8]
        MOVS     r2,#0xff
        ADDS     r2,#1
        ORRS     r1,r1,r2
        LDR      r2,|L1.996|
        SUBS     r2,r2,#0x40
        STR      r1,[r2,#8]
        B        |L1.348|
|L1.284|
        LDR      r1,|L1.1008|
        LDR      r1,[r1,#8]
        MOVS     r2,#1
        LSLS     r2,r2,#21
        ORRS     r1,r1,r2
        LDR      r2,|L1.1008|
        STR      r1,[r2,#8]
        LDR      r1,|L1.996|
        SUBS     r1,r1,#0x40
        LDR      r1,[r1,#8]
        LSLS     r2,r2,#7
        ORRS     r1,r1,r2
        LDR      r2,|L1.996|
        SUBS     r2,r2,#0x40
        STR      r1,[r2,#8]
        B        |L1.348|
|L1.316|
        LDR      r1,|L1.1008|
        LDR      r1,[r1,#8]
        MOVS     r2,#1
        LSLS     r2,r2,#21
        ORRS     r1,r1,r2
        LDR      r2,|L1.1008|
        STR      r1,[r2,#8]
        LDR      r1,|L1.996|
        SUBS     r1,r1,#0x40
        LDR      r1,[r1,#8]
        LSLS     r2,r2,#15
        ORRS     r1,r1,r2
        LDR      r2,|L1.996|
        SUBS     r2,r2,#0x40
        STR      r1,[r2,#8]
        NOP      
|L1.348|
        NOP      
        BX       lr
        ENDP

DrvPWM_DeInit PROC
        CMP      r0,#0
        BEQ      |L1.370|
        CMP      r0,#1
        BEQ      |L1.402|
        CMP      r0,#2
        BEQ      |L1.436|
        CMP      r0,#3
        BNE      |L1.500|
        B        |L1.468|
|L1.370|
        LDR      r1,|L1.1008|
        LDR      r1,[r1,#8]
        MOVS     r2,#1
        LSLS     r2,r2,#20
        BICS     r1,r1,r2
        LDR      r2,|L1.1008|
        STR      r1,[r2,#8]
        LDR      r1,|L1.996|
        SUBS     r1,r1,#0x40
        LDR      r1,[r1,#8]
        LSRS     r1,r1,#1
        LSLS     r1,r1,#1
        LDR      r2,|L1.996|
        SUBS     r2,r2,#0x40
        STR      r1,[r2,#8]
        B        |L1.500|
|L1.402|
        LDR      r1,|L1.1008|
        LDR      r1,[r1,#8]
        MOVS     r2,#1
        LSLS     r2,r2,#20
        BICS     r1,r1,r2
        LDR      r2,|L1.1008|
        STR      r1,[r2,#8]
        LDR      r1,|L1.996|
        SUBS     r1,r1,#0x40
        LDR      r1,[r1,#8]
        MOVS     r2,#0xff
        ADDS     r2,#1
        BICS     r1,r1,r2
        LDR      r2,|L1.996|
        SUBS     r2,r2,#0x40
        STR      r1,[r2,#8]
        B        |L1.500|
|L1.436|
        LDR      r1,|L1.1008|
        LDR      r1,[r1,#8]
        MOVS     r2,#1
        LSLS     r2,r2,#21
        BICS     r1,r1,r2
        LDR      r2,|L1.1008|
        STR      r1,[r2,#8]
        LDR      r1,|L1.996|
        SUBS     r1,r1,#0x40
        LDR      r1,[r1,#8]
        LSLS     r2,r2,#7
        BICS     r1,r1,r2
        LDR      r2,|L1.996|
        SUBS     r2,r2,#0x40
        STR      r1,[r2,#8]
        B        |L1.500|
|L1.468|
        LDR      r1,|L1.1008|
        LDR      r1,[r1,#8]
        MOVS     r2,#1
        LSLS     r2,r2,#21
        BICS     r1,r1,r2
        LDR      r2,|L1.1008|
        STR      r1,[r2,#8]
        LDR      r1,|L1.996|
        SUBS     r1,r1,#0x40
        LDR      r1,[r1,#8]
        LSLS     r2,r2,#15
        BICS     r1,r1,r2
        LDR      r2,|L1.996|
        SUBS     r2,r2,#0x40
        STR      r1,[r2,#8]
        NOP      
|L1.500|
        NOP      
        BX       lr
        ENDP

DrvPWM_EnableDeadZone PROC
        MOVS     r2,#2
        TST      r0,r2
        BEQ      |L1.546|
        LDR      r2,|L1.996|
        SUBS     r2,r2,#0x40
        LDR      r2,[r2,#0]
        LSLS     r2,r2,#8
        LSRS     r2,r2,#8
        LSLS     r3,r1,#24
        ORRS     r2,r2,r3
        LDR      r3,|L1.996|
        SUBS     r3,r3,#0x40
        STR      r2,[r3,#0]
        MOV      r2,r3
        LDR      r2,[r2,#8]
        MOVS     r3,#0x20
        ORRS     r2,r2,r3
        LDR      r3,|L1.996|
        SUBS     r3,r3,#0x40
        STR      r2,[r3,#8]
        B        |L1.582|
|L1.546|
        LDR      r2,|L1.996|
        SUBS     r2,r2,#0x40
        LDR      r2,[r2,#0]
        MOVS     r3,#0xff
        LSLS     r3,r3,#16
        BICS     r2,r2,r3
        LSLS     r3,r1,#16
        ORRS     r2,r2,r3
        LDR      r3,|L1.996|
        SUBS     r3,r3,#0x40
        STR      r2,[r3,#0]
        MOV      r2,r3
        LDR      r2,[r2,#8]
        MOVS     r3,#0x10
        ORRS     r2,r2,r3
        LDR      r3,|L1.996|
        SUBS     r3,r3,#0x40
        STR      r2,[r3,#8]
|L1.582|
        BX       lr
        ENDP

DrvPWM_DisableDeadZone PROC
        MOVS     r1,#2
        TST      r0,r1
        BEQ      |L1.608|
        LDR      r1,|L1.996|
        SUBS     r1,r1,#0x40
        LDR      r1,[r1,#8]
        MOVS     r2,#0x20
        BICS     r1,r1,r2
        LDR      r2,|L1.996|
        SUBS     r2,r2,#0x40
        STR      r1,[r2,#8]
        B        |L1.624|
|L1.608|
        LDR      r1,|L1.996|
        SUBS     r1,r1,#0x40
        LDR      r1,[r1,#8]
        MOVS     r2,#0x10
        BICS     r1,r1,r2
        LDR      r2,|L1.996|
        SUBS     r2,r2,#0x40
        STR      r1,[r2,#8]
|L1.624|
        BX       lr
        ENDP

DrvPWM_CaptureEnable PROC
        CMP      r0,#0
        BEQ      |L1.644|
        CMP      r0,#1
        BEQ      |L1.658|
        CMP      r0,#2
        BEQ      |L1.674|
        CMP      r0,#3
        BNE      |L1.704|
        B        |L1.688|
|L1.644|
        LDR      r1,|L1.996|
        LDR      r1,[r1,#0x10]
        MOVS     r2,#8
        ORRS     r1,r1,r2
        LDR      r2,|L1.996|
        STR      r1,[r2,#0x10]
        B        |L1.704|
|L1.658|
        LDR      r1,|L1.996|
        LDR      r1,[r1,#0x10]
        MOVS     r2,#1
        LSLS     r2,r2,#19
        ORRS     r1,r1,r2
        LDR      r2,|L1.996|
        STR      r1,[r2,#0x10]
        B        |L1.704|
|L1.674|
        LDR      r1,|L1.996|
        LDR      r1,[r1,#0x14]
        MOVS     r2,#8
        ORRS     r1,r1,r2
        LDR      r2,|L1.996|
        STR      r1,[r2,#0x14]
        B        |L1.704|
|L1.688|
        LDR      r1,|L1.996|
        LDR      r1,[r1,#0x14]
        MOVS     r2,#1
        LSLS     r2,r2,#19
        ORRS     r1,r1,r2
        LDR      r2,|L1.996|
        STR      r1,[r2,#0x14]
        NOP      
|L1.704|
        NOP      
        BX       lr
        ENDP

DrvPWM_CaptureDisable PROC
        CMP      r0,#0
        BEQ      |L1.726|
        CMP      r0,#1
        BEQ      |L1.740|
        CMP      r0,#2
        BEQ      |L1.756|
        CMP      r0,#3
        BNE      |L1.786|
        B        |L1.770|
|L1.726|
        LDR      r1,|L1.996|
        LDR      r1,[r1,#0x10]
        MOVS     r2,#8
        BICS     r1,r1,r2
        LDR      r2,|L1.996|
        STR      r1,[r2,#0x10]
        B        |L1.786|
|L1.740|
        LDR      r1,|L1.996|
        LDR      r1,[r1,#0x10]
        MOVS     r2,#1
        LSLS     r2,r2,#19
        BICS     r1,r1,r2
        LDR      r2,|L1.996|
        STR      r1,[r2,#0x10]
        B        |L1.786|
|L1.756|
        LDR      r1,|L1.996|
        LDR      r1,[r1,#0x14]
        MOVS     r2,#8
        BICS     r1,r1,r2
        LDR      r2,|L1.996|
        STR      r1,[r2,#0x14]
        B        |L1.786|
|L1.770|
        LDR      r1,|L1.996|
        LDR      r1,[r1,#0x14]
        MOVS     r2,#1
        LSLS     r2,r2,#19
        BICS     r1,r1,r2
        LDR      r2,|L1.996|
        STR      r1,[r2,#0x14]
        NOP      
|L1.786|
        NOP      
        BX       lr
        ENDP

DrvPWM_SetClk PROC
        PUSH     {r4,r5,lr}
        MOVS     r2,#0
        LDR      r3,|L1.996|
        SUBS     r3,r3,#0x40
        LDR      r3,[r3,#0]
        ASRS     r4,r0,#1
        LSLS     r5,r4,#3
        MOVS     r4,#0xff
        LSLS     r4,r4,r5
        BICS     r3,r3,r4
        LDR      r4,|L1.996|
        SUBS     r4,r4,#0x40
        STR      r3,[r4,#0]
        LDRB     r3,[r1,#4]
        SUBS     r3,r3,#1
        ASRS     r4,r0,#1
        LSLS     r4,r4,#3
        LSLS     r3,r3,r4
        LDR      r4,|L1.996|
        SUBS     r4,r4,#0x40
        LDR      r4,[r4,#0]
        ORRS     r3,r3,r4
        LDR      r4,|L1.996|
        SUBS     r4,r4,#0x40
        STR      r3,[r4,#0]
        MOV      r3,r4
        LDR      r3,[r3,#4]
        LSLS     r5,r0,#2
        MOVS     r4,#7
        LSLS     r4,r4,r5
        BICS     r3,r3,r4
        LDR      r4,|L1.996|
        SUBS     r4,r4,#0x40
        STR      r3,[r4,#4]
        LDRB     r3,[r1,#5]
        LSLS     r4,r0,#2
        LSLS     r3,r3,r4
        LDR      r4,|L1.996|
        SUBS     r4,r4,#0x40
        LDR      r4,[r4,#4]
        ORRS     r3,r3,r4
        LDR      r4,|L1.996|
        SUBS     r4,r4,#0x40
        STR      r3,[r4,#4]
        LDRB     r3,[r1,#6]
        CMP      r3,#0
        BEQ      |L1.886|
        MOVS     r2,#8
|L1.886|
        LDRB     r3,[r1,#7]
        CMP      r3,#0
        BEQ      |L1.896|
        MOVS     r3,#6
        ORRS     r2,r2,r3
|L1.896|
        LDR      r3,|L1.996|
        SUBS     r3,r3,#0x40
        LDR      r3,[r3,#8]
        LSLS     r5,r0,#3
        MOVS     r4,#0xe
        LSLS     r4,r4,r5
        BICS     r3,r3,r4
        LDR      r4,|L1.996|
        SUBS     r4,r4,#0x40
        STR      r3,[r4,#8]
        MOV      r3,r4
        LDR      r3,[r3,#8]
        LSLS     r5,r0,#3
        MOV      r4,r2
        LSLS     r4,r4,r5
        ORRS     r3,r3,r4
        LDR      r4,|L1.996|
        SUBS     r4,r4,#0x40
        STR      r3,[r4,#8]
        CMP      r0,#0
        BEQ      |L1.952|
        CMP      r0,#1
        BEQ      |L1.966|
        CMP      r0,#2
        BEQ      |L1.980|
        CMP      r0,#3
        BNE      |L1.1024|
        B        |L1.1012|
|L1.952|
        LDRH     r3,[r1,#0]
        LDR      r4,|L1.996|
        SUBS     r4,r4,#0x40
        STR      r3,[r4,#0xc]
        LDRH     r3,[r1,#2]
        STR      r3,[r4,#0x10]
        B        |L1.1024|
|L1.966|
        LDRH     r3,[r1,#0]
        LDR      r4,|L1.996|
        SUBS     r4,r4,#0x40
        STR      r3,[r4,#0x18]
        LDRH     r3,[r1,#2]
        STR      r3,[r4,#0x1c]
        B        |L1.1024|
|L1.980|
        LDRH     r3,[r1,#0]
        LDR      r4,|L1.996|
        SUBS     r4,r4,#0x40
        STR      r3,[r4,#0x24]
        LDRH     r3,[r1,#2]
        STR      r3,[r4,#0x28]
        B        |L1.1024|
        DCW      0x0000
|L1.996|
        DCD      0x40040040
|L1.1000|
        DCD      0x00000f0f
|L1.1004|
        DCD      0x00060006
|L1.1008|
        DCD      0x50000200
|L1.1012|
        LDRH     r3,[r1,#0]
        LDR      r4,|L1.1164|
        STR      r3,[r4,#0x30]
        LDRH     r3,[r1,#2]
        STR      r3,[r4,#0x34]
        NOP      
|L1.1024|
        NOP      
        POP      {r4,r5,pc}
        ENDP

DrvPWM_ConfigCaptureIntput PROC
        PUSH     {r4,r5,lr}
        MOV      r2,r1
        CMP      r0,#2
        BGE      |L1.1042|
        LDR      r3,|L1.1164|
        ADDS     r3,r3,#0x50
        B        |L1.1046|
|L1.1042|
        LDR      r3,|L1.1164|
        ADDS     r3,r3,#0x54
|L1.1046|
        MOV      r1,r3
        CMP      r2,#0
        BEQ      |L1.1068|
        LDR      r3,[r1,#0]
        LSLS     r4,r0,#31
        LSRS     r5,r4,#27
        MOVS     r4,#8
        LSLS     r4,r4,r5
        ORRS     r3,r3,r4
        STR      r3,[r1,#0]
        B        |L1.1082|
|L1.1068|
        LDR      r4,[r1,#0]
        LSLS     r3,r0,#31
        LSRS     r5,r3,#27
        MOVS     r3,#8
        LSLS     r3,r3,r5
        BICS     r4,r4,r3
        STR      r4,[r1,#0]
|L1.1082|
        POP      {r4,r5,pc}
        ENDP

DrvPWM_EnablePdma PROC
        LDR      r1,|L1.1164|
        ADDS     r1,r1,#0xc0
        LDR      r1,[r1,#0]
        LSLS     r2,r0,#30
        LSRS     r3,r2,#27
        MOVS     r2,#1
        LSLS     r2,r2,r3
        ORRS     r1,r1,r2
        LDR      r2,|L1.1164|
        ADDS     r2,r2,#0xc0
        STR      r1,[r2,#0]
        BX       lr
        ENDP

DrvPWM_DisablePdma PROC
        LDR      r1,|L1.1164|
        ADDS     r1,r1,#0xc0
        LDR      r1,[r1,#0]
        LSLS     r2,r0,#30
        LSRS     r3,r2,#27
        MOVS     r2,#1
        LSLS     r2,r2,r3
        BICS     r1,r1,r2
        LDR      r2,|L1.1164|
        ADDS     r2,r2,#0xc0
        STR      r1,[r2,#0]
        BX       lr
        ENDP

NVIC_EnableIRQ PROC
        LSLS     r2,r0,#27
        LSRS     r2,r2,#27
        MOVS     r1,#1
        LSLS     r1,r1,r2
        LDR      r2,|L1.1168|
        STR      r1,[r2,#0]
        BX       lr
        ENDP

NVIC_DisableIRQ PROC
        LSLS     r2,r0,#27
        LSRS     r2,r2,#27
        MOVS     r1,#1
        LSLS     r1,r1,r2
        LDR      r2,|L1.1168|
        ADDS     r2,r2,#0x80
        STR      r1,[r2,#0]
        BX       lr
        ENDP

        DCW      0x0000
|L1.1164|
        DCD      0x40040000
|L1.1168|
        DCD      0xe000e100

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        EXPORT DrvPWM_EnableInt [CODE]
        EXPORT DrvPWM_DisableInt [CODE]
        EXPORT DrvPWM_EnableCaptureInt [CODE]
        EXPORT DrvPWM_DisableCaptureInt [CODE]
        EXPORT DrvPWM_Init [CODE]
        EXPORT DrvPWM_DeInit [CODE]
        EXPORT DrvPWM_EnableDeadZone [CODE]
        EXPORT DrvPWM_DisableDeadZone [CODE]
        EXPORT DrvPWM_CaptureEnable [CODE]
        EXPORT DrvPWM_CaptureDisable [CODE]
        EXPORT DrvPWM_SetClk [CODE]
        EXPORT DrvPWM_ConfigCaptureIntput [CODE]
        EXPORT DrvPWM_EnablePdma [CODE]
        EXPORT DrvPWM_DisablePdma [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        KEEP NVIC_EnableIRQ
        KEEP NVIC_DisableIRQ

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
