; generated by ARM C/C++ Compiler, 5.02 [Build 28]
; commandline ArmCC [--min_array_alignment=4 --split_sections --debug -c --asm --info=totals -o.\output\filter.o --depend=.\output\filter.d --cpu=Cortex-M0 --apcs=interwork -I..\CMSIS\CM0\DeviceSupport\Nuvoton\NUC123Series -I..\CMSIS\CM0\CoreSupport -I..\INC\DrvInc -I..\INC\SysInc -IC:\Keil\ARM\RV31\INC -IC:\Keil\ARM\CMSIS\Include -D__MICROLIB --omf_browse=.\output\filter.crf ..\AppSrc\filter.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.I2S_IRQHandler||, CODE, READONLY, ALIGN=2

I2S_IRQHandler PROC
        LDR      r1,|L1.16|
        LDR      r0,[r1,#0xc]
        LDR      r2,|L1.20|
        STR      r0,[r2,#0x1c]  ; sum
        STR      r0,[r2,#0x20]  ; i2s_status
        LDR      r0,[r1,#0x14]
        LDR      r0,[r1,#0x14]
        BX       lr
        ENDP

|L1.16|
        DCD      0x401a0000
|L1.20|
        DCD      ||area_number.12||

        AREA ||i.filter||, CODE, READONLY, ALIGN=1

filter PROC
        BX       lr
        ENDP


        AREA ||i.filterInit||, CODE, READONLY, ALIGN=2

filterInit PROC
        MOVS     r0,#0
        LDR      r2,|L3.24|
        MOVS     r3,#0xf
        MOV      r1,r0
        LSLS     r3,r3,#6
|L3.10|
        STRB     r1,[r2,r0]
        ADDS     r0,r0,#1
        CMP      r0,r3
        BCC      |L3.10|
        LDR      r0,|L3.28|
        STR      r1,[r0,#0x10]  ; fsum
        BX       lr
        ENDP

|L3.24|
        DCD      ||area_number.9||
|L3.28|
        DCD      ||area_number.12||

        AREA ||i.filter_50||, CODE, READONLY, ALIGN=2

filter_50 PROC
        PUSH     {r4,r5,lr}
        LDR      r3,|L4.44|
        MOVS     r2,#0xf
        LDR      r1,[r3,#0xc]  ; index
        LSLS     r2,r2,#6
        CMP      r1,r2
        BCC      |L4.18|
        MOVS     r1,#0
        STR      r1,[r3,#0xc]  ; index
|L4.18|
        LDR      r1,[r3,#0x10]  ; fsum
        LDR      r4,|L4.48|
        ADDS     r2,r1,r0
        LDR      r1,[r3,#0xc]  ; index
        LDRB     r5,[r4,r1]
        SUBS     r2,r2,r5
        STR      r2,[r3,#0x10]  ; fsum
        STRB     r0,[r4,r1]
        ADDS     r1,r1,#1
        LSLS     r0,r2,#10
        LSRS     r0,r0,#24
        STR      r1,[r3,#0xc]  ; index
        POP      {r4,r5,pc}
        ENDP

|L4.44|
        DCD      ||area_number.12||
|L4.48|
        DCD      ||area_number.9||

        AREA ||i.limiter||, CODE, READONLY, ALIGN=2

limiter PROC
        MOVS     r1,#1
        LSLS     r1,r1,#11
        LSLS     r2,r1,#3
        CMP      r0,#0
        BLE      |L5.40|
        CMP      r0,r1
        BLT      |L5.62|
        CMP      r0,r2
        BGE      |L5.28|
        SUBS     r0,r0,r1
        MOVS     r2,#0xa4
        MULS     r0,r2,r0
        ASRS     r0,r0,#7
        B        |L5.76|
|L5.28|
        SUBS     r0,r0,r2
        MOVS     r1,#0x64
        MULS     r0,r1,r0
        ASRS     r0,r0,#7
        LDR      r1,|L5.80|
        B        |L5.76|
|L5.40|
        LDR      r3,|L5.84|
        CMP      r0,r3
        BGT      |L5.62|
        LSLS     r3,r3,#3
        CMP      r0,r3
        BLE      |L5.64|
        ADDS     r0,r0,r1
        MOVS     r2,#0xa4
        MULS     r0,r2,r0
        ASRS     r0,r0,#7
        SUBS     r0,r0,r1
|L5.62|
        BX       lr
|L5.64|
        ADDS     r0,r0,r2
        MOVS     r1,#0x64
        MULS     r0,r1,r0
        LDR      r1,|L5.80|
        ASRS     r0,r0,#7
        RSBS     r1,r1,#0
|L5.76|
        ADDS     r0,r0,r1
        BX       lr
        ENDP

|L5.80|
        DCD      0x00004fc0
|L5.84|
        DCD      0xfffff800

        AREA ||i.triggerFilter||, CODE, READONLY, ALIGN=2

triggerFilter PROC
        LDR      r0,|L6.36|
        LDR      r1,[r0,#0]  ; i2s_pdma_rxbuf_flag
        LDR      r0,|L6.40|
        CMP      r1,#0
        LDR      r1,|L6.44|
        BEQ      |L6.24|
        STR      r1,[r0,#4]  ; filter_srcbuf
        LDR      r1,|L6.48|
|L6.16|
        STR      r1,[r0,#8]  ; filter_destbuf
        MOVS     r1,#1
        STR      r1,[r0,#0]  ; filter_trigger
        BX       lr
|L6.24|
        ADDS     r1,r1,#0xc0
        STR      r1,[r0,#4]  ; filter_srcbuf
        LDR      r1,|L6.48|
        ADDS     r1,r1,#0xc0
        B        |L6.16|
        ENDP

        DCW      0x0000
|L6.36|
        DCD      i2s_pdma_rxbuf_flag
|L6.40|
        DCD      ||area_number.12||
|L6.44|
        DCD      i2s_rxbuf
|L6.48|
        DCD      i2s_txbuf

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.bss||, DATA, NOINIT, ALIGN=2

t_a
        %        32

        AREA ||area_number.9||, DATA, NOINIT, ALIGN=2

        EXPORTAS ||area_number.9||, ||.bss||
fsamples
        %        960

        AREA ||.data||, DATA, ALIGN=2

firsr_trigger
        DCD      0x00000000

        AREA ||area_number.12||, DATA, ALIGN=2

        EXPORTAS ||area_number.12||, ||.data||
filter_trigger
        DCD      0x00000000
filter_srcbuf
        DCD      i2s_rxbuf
filter_destbuf
        DCD      i2s_txbuf
index
        DCD      0x00000000
fsum
        DCD      0x00000000
sum_LL
        DCD      0x00000000
sum_RL
        DCD      0x00000000
||sum||
        DCD      0x00000000
i2s_status
        DCD      0x00000000

        AREA ||area_number.13||, DATA, ALIGN=2

        EXPORTAS ||area_number.13||, ||.data||
filter_bypass
        DCD      0x00000000

        AREA ||area_number.14||, DATA, ALIGN=2

        EXPORTAS ||area_number.14||, ||.data||
x1_hpL
        DCD      0x00000000

        AREA ||area_number.15||, DATA, ALIGN=2

        EXPORTAS ||area_number.15||, ||.data||
x1_hpH
        DCD      0x00000000

        AREA ||area_number.16||, DATA, ALIGN=2

        EXPORTAS ||area_number.16||, ||.data||
acc1_L
        DCD      0x00000000

        AREA ||area_number.17||, DATA, ALIGN=2

        EXPORTAS ||area_number.17||, ||.data||
acc1_H
        DCD      0x00000000

        AREA ||area_number.18||, DATA, ALIGN=2

        EXPORTAS ||area_number.18||, ||.data||
y1_hpL
        DCD      0x00000000

        AREA ||area_number.19||, DATA, ALIGN=2

        EXPORTAS ||area_number.19||, ||.data||
y1_hpH
        DCD      0x00000000

        AREA ||area_number.20||, DATA, ALIGN=2

        EXPORTAS ||area_number.20||, ||.data||
x2_hpL
        DCD      0x00000000

        AREA ||area_number.21||, DATA, ALIGN=2

        EXPORTAS ||area_number.21||, ||.data||
x2_hpH
        DCD      0x00000000

        AREA ||area_number.22||, DATA, ALIGN=2

        EXPORTAS ||area_number.22||, ||.data||
acc2_L
        DCD      0x00000000

        AREA ||area_number.23||, DATA, ALIGN=2

        EXPORTAS ||area_number.23||, ||.data||
acc2_H
        DCD      0x00000000

        AREA ||area_number.24||, DATA, ALIGN=2

        EXPORTAS ||area_number.24||, ||.data||
y2_hpL
        DCD      0x00000000

        AREA ||area_number.25||, DATA, ALIGN=2

        EXPORTAS ||area_number.25||, ||.data||
y2_hpH
        DCD      0x00000000

        AREA ||area_number.26||, DATA, ALIGN=2

        EXPORTAS ||area_number.26||, ||.data||
K1_HP
        DCD      0x00000068

        AREA ||area_number.27||, DATA, ALIGN=2

        EXPORTAS ||area_number.27||, ||.data||
K2_HP
        DCD      0x00000068

        AREA ||area_number.28||, DATA, ALIGN=2

        EXPORTAS ||area_number.28||, ||.data||
F_R_K11
        DCD      0x00007fff

        AREA ||area_number.29||, DATA, ALIGN=2

        EXPORTAS ||area_number.29||, ||.data||
F_R_K12
        DCD      0x00000000

        AREA ||area_number.30||, DATA, ALIGN=2

        EXPORTAS ||area_number.30||, ||.data||
F_R_K13
        DCD      0x00000000

        AREA ||area_number.31||, DATA, ALIGN=2

        EXPORTAS ||area_number.31||, ||.data||
F_R_K14
        DCD      0x00000000

        AREA ||area_number.32||, DATA, ALIGN=2

        EXPORTAS ||area_number.32||, ||.data||
F_R_K15
        DCD      0x00000000

        AREA ||area_number.33||, DATA, ALIGN=2

        EXPORTAS ||area_number.33||, ||.data||
F_R_K21
        DCD      0x00007fff

        AREA ||area_number.34||, DATA, ALIGN=2

        EXPORTAS ||area_number.34||, ||.data||
F_R_K22
        DCD      0x00000000

        AREA ||area_number.35||, DATA, ALIGN=2

        EXPORTAS ||area_number.35||, ||.data||
F_R_K23
        DCD      0x00000000

        AREA ||area_number.36||, DATA, ALIGN=2

        EXPORTAS ||area_number.36||, ||.data||
F_R_K24
        DCD      0x00000000

        AREA ||area_number.37||, DATA, ALIGN=2

        EXPORTAS ||area_number.37||, ||.data||
F_R_K25
        DCD      0x00000000

        AREA ||area_number.38||, DATA, ALIGN=2

        EXPORTAS ||area_number.38||, ||.data||
F_R_K31
        DCD      0x00007fff

        AREA ||area_number.39||, DATA, ALIGN=2

        EXPORTAS ||area_number.39||, ||.data||
F_R_K32
        DCD      0x00000000

        AREA ||area_number.40||, DATA, ALIGN=2

        EXPORTAS ||area_number.40||, ||.data||
F_R_K33
        DCD      0x00000000

        AREA ||area_number.41||, DATA, ALIGN=2

        EXPORTAS ||area_number.41||, ||.data||
F_R_K34
        DCD      0x00000000

        AREA ||area_number.42||, DATA, ALIGN=2

        EXPORTAS ||area_number.42||, ||.data||
F_R_K35
        DCD      0x00000000

        AREA ||area_number.43||, DATA, ALIGN=2

        EXPORTAS ||area_number.43||, ||.data||
F_R_K41
        DCD      0x00007fff

        AREA ||area_number.44||, DATA, ALIGN=2

        EXPORTAS ||area_number.44||, ||.data||
F_R_K42
        DCD      0x00000000

        AREA ||area_number.45||, DATA, ALIGN=2

        EXPORTAS ||area_number.45||, ||.data||
F_R_K43
        DCD      0x00000000

        AREA ||area_number.46||, DATA, ALIGN=2

        EXPORTAS ||area_number.46||, ||.data||
F_R_K44
        DCD      0x00000000

        AREA ||area_number.47||, DATA, ALIGN=2

        EXPORTAS ||area_number.47||, ||.data||
F_R_K45
        DCD      0x00000000

        AREA ||area_number.48||, DATA, ALIGN=2

        EXPORTAS ||area_number.48||, ||.data||
F_R_K51
        DCD      0x00007fff

        AREA ||area_number.49||, DATA, ALIGN=2

        EXPORTAS ||area_number.49||, ||.data||
F_R_K52
        DCD      0x00000000

        AREA ||area_number.50||, DATA, ALIGN=2

        EXPORTAS ||area_number.50||, ||.data||
F_R_K53
        DCD      0x00000000

        AREA ||area_number.51||, DATA, ALIGN=2

        EXPORTAS ||area_number.51||, ||.data||
F_R_K54
        DCD      0x00000000

        AREA ||area_number.52||, DATA, ALIGN=2

        EXPORTAS ||area_number.52||, ||.data||
F_R_K55
        DCD      0x00000000

        AREA ||area_number.53||, DATA, ALIGN=2

        EXPORTAS ||area_number.53||, ||.data||
F_L_K11
        DCD      0x003fc371

        AREA ||area_number.54||, DATA, ALIGN=2

        EXPORTAS ||area_number.54||, ||.data||
F_L_K12
        DCD      0xff80791d

        AREA ||area_number.55||, DATA, ALIGN=2

        EXPORTAS ||area_number.55||, ||.data||
F_L_K13
        DCD      0x003fc371

        AREA ||area_number.56||, DATA, ALIGN=2

        EXPORTAS ||area_number.56||, ||.data||
F_L_K14
        DCD      0x007f86a9

        AREA ||area_number.57||, DATA, ALIGN=2

        EXPORTAS ||area_number.57||, ||.data||
F_L_K15
        DCD      0xffc078e3

        AREA ||area_number.58||, DATA, ALIGN=2

        EXPORTAS ||area_number.58||, ||.data||
F_L_K21
        DCD      0x83223f13

        AREA ||area_number.59||, DATA, ALIGN=2

        EXPORTAS ||area_number.59||, ||.data||
F_L_K22
        DCD      0x7cde3ede

        AREA ||area_number.60||, DATA, ALIGN=2

        EXPORTAS ||area_number.60||, ||.data||
F_L_K23
        DCD      0x3fcac20f

        AREA ||area_number.61||, DATA, ALIGN=2

        EXPORTAS ||area_number.61||, ||.data||
F_L_K24
        DCD      0x3f60811b

        AREA ||area_number.62||, DATA, ALIGN=2

        EXPORTAS ||area_number.62||, ||.data||
F_L_K25
        DCD      0xc0d57ee5

        AREA ||area_number.63||, DATA, ALIGN=2

        EXPORTAS ||area_number.63||, ||.data||
F_L_K31
        DCD      0x7fff0000

        AREA ||area_number.64||, DATA, ALIGN=2

        EXPORTAS ||area_number.64||, ||.data||
F_L_K32
        DCD      0x00000000

        AREA ||area_number.65||, DATA, ALIGN=2

        EXPORTAS ||area_number.65||, ||.data||
F_L_K33
        DCD      0x0000c20f

        AREA ||area_number.66||, DATA, ALIGN=2

        EXPORTAS ||area_number.66||, ||.data||
F_L_K34
        DCD      0x3f60811b

        AREA ||area_number.67||, DATA, ALIGN=2

        EXPORTAS ||area_number.67||, ||.data||
F_L_K35
        DCD      0xc0d57ee5

        AREA ||area_number.68||, DATA, ALIGN=2

        EXPORTAS ||area_number.68||, ||.data||
F_L_K4_SHIFT
        DCD      0x0000000e

        AREA ||area_number.69||, DATA, ALIGN=2

        EXPORTAS ||area_number.69||, ||.data||
F_L_K41
        DCD      0x83223f13

        AREA ||area_number.70||, DATA, ALIGN=2

        EXPORTAS ||area_number.70||, ||.data||
F_L_K42
        DCD      0x7cde3ede

        AREA ||area_number.71||, DATA, ALIGN=2

        EXPORTAS ||area_number.71||, ||.data||
F_L_K43
        DCD      0x3fcac20f

        AREA ||area_number.72||, DATA, ALIGN=2

        EXPORTAS ||area_number.72||, ||.data||
F_L_K44
        DCD      0x3f60811b

        AREA ||area_number.73||, DATA, ALIGN=2

        EXPORTAS ||area_number.73||, ||.data||
F_L_K45
        DCD      0xc0d57ee5

        AREA ||area_number.74||, DATA, ALIGN=2

        EXPORTAS ||area_number.74||, ||.data||
F_L_K5_SHIFT
        DCD      0x0000000f

        AREA ||area_number.75||, DATA, ALIGN=2

        EXPORTAS ||area_number.75||, ||.data||
F_L_K51
        DCD      0x00007fff

        AREA ||area_number.76||, DATA, ALIGN=2

        EXPORTAS ||area_number.76||, ||.data||
F_L_K52
        DCD      0x00000000

        AREA ||area_number.77||, DATA, ALIGN=2

        EXPORTAS ||area_number.77||, ||.data||
F_L_K53
        DCD      0x00000000

        AREA ||area_number.78||, DATA, ALIGN=2

        EXPORTAS ||area_number.78||, ||.data||
F_L_K54
        DCD      0x00000000

        AREA ||area_number.79||, DATA, ALIGN=2

        EXPORTAS ||area_number.79||, ||.data||
F_L_K55
        DCD      0x00000000

        AREA ||area_number.80||, DATA, ALIGN=2

        EXPORTAS ||area_number.80||, ||.data||
filter_rxbuf_flag
        DCD      0x00000000

        AREA ||area_number.81||, DATA, ALIGN=2

        EXPORTAS ||area_number.81||, ||.data||
y1_L3
        DCD      0x00000000

        AREA ||area_number.82||, DATA, ALIGN=2

        EXPORTAS ||area_number.82||, ||.data||
y1_L2
        DCD      0x00000000

        AREA ||area_number.83||, DATA, ALIGN=2

        EXPORTAS ||area_number.83||, ||.data||
y1_L1
        DCD      0x00000000

        AREA ||area_number.84||, DATA, ALIGN=2

        EXPORTAS ||area_number.84||, ||.data||
x1_L3
        DCD      0x00000000

        AREA ||area_number.85||, DATA, ALIGN=2

        EXPORTAS ||area_number.85||, ||.data||
x1_L2
        DCD      0x00000000

        AREA ||area_number.86||, DATA, ALIGN=2

        EXPORTAS ||area_number.86||, ||.data||
x1_L1
        DCD      0x00000000

        AREA ||area_number.87||, DATA, ALIGN=2

        EXPORTAS ||area_number.87||, ||.data||
y2_L3
        DCD      0x00000000

        AREA ||area_number.88||, DATA, ALIGN=2

        EXPORTAS ||area_number.88||, ||.data||
y2_L2
        DCD      0x00000000

        AREA ||area_number.89||, DATA, ALIGN=2

        EXPORTAS ||area_number.89||, ||.data||
y2_L1
        DCD      0x00000000

        AREA ||area_number.90||, DATA, ALIGN=2

        EXPORTAS ||area_number.90||, ||.data||
x2_L3
        DCD      0x00000000

        AREA ||area_number.91||, DATA, ALIGN=2

        EXPORTAS ||area_number.91||, ||.data||
x2_L2
        DCD      0x00000000

        AREA ||area_number.92||, DATA, ALIGN=2

        EXPORTAS ||area_number.92||, ||.data||
x2_L1
        DCD      0x00000000

        AREA ||area_number.93||, DATA, ALIGN=2

        EXPORTAS ||area_number.93||, ||.data||
y3_L3
        DCD      0x00000000

        AREA ||area_number.94||, DATA, ALIGN=2

        EXPORTAS ||area_number.94||, ||.data||
y3_L2
        DCD      0x00000000

        AREA ||area_number.95||, DATA, ALIGN=2

        EXPORTAS ||area_number.95||, ||.data||
y3_L1
        DCD      0x00000000

        AREA ||area_number.96||, DATA, ALIGN=2

        EXPORTAS ||area_number.96||, ||.data||
x3_L3
        DCD      0x00000000

        AREA ||area_number.97||, DATA, ALIGN=2

        EXPORTAS ||area_number.97||, ||.data||
x3_L2
        DCD      0x00000000

        AREA ||area_number.98||, DATA, ALIGN=2

        EXPORTAS ||area_number.98||, ||.data||
x3_L1
        DCD      0x00000000

        AREA ||area_number.99||, DATA, ALIGN=2

        EXPORTAS ||area_number.99||, ||.data||
y4_L3
        DCD      0x00000000

        AREA ||area_number.100||, DATA, ALIGN=2

        EXPORTAS ||area_number.100||, ||.data||
y4_L2
        DCD      0x00000000

        AREA ||area_number.101||, DATA, ALIGN=2

        EXPORTAS ||area_number.101||, ||.data||
y4_L1
        DCD      0x00000000

        AREA ||area_number.102||, DATA, ALIGN=2

        EXPORTAS ||area_number.102||, ||.data||
x4_L3
        DCD      0x00000000

        AREA ||area_number.103||, DATA, ALIGN=2

        EXPORTAS ||area_number.103||, ||.data||
x4_L2
        DCD      0x00000000

        AREA ||area_number.104||, DATA, ALIGN=2

        EXPORTAS ||area_number.104||, ||.data||
x4_L1
        DCD      0x00000000

        AREA ||area_number.105||, DATA, ALIGN=2

        EXPORTAS ||area_number.105||, ||.data||
y5_L3
        DCD      0x00000000

        AREA ||area_number.106||, DATA, ALIGN=2

        EXPORTAS ||area_number.106||, ||.data||
y5_L2
        DCD      0x00000000

        AREA ||area_number.107||, DATA, ALIGN=2

        EXPORTAS ||area_number.107||, ||.data||
y5_L1
        DCD      0x00000000

        AREA ||area_number.108||, DATA, ALIGN=2

        EXPORTAS ||area_number.108||, ||.data||
x5_L3
        DCD      0x00000000

        AREA ||area_number.109||, DATA, ALIGN=2

        EXPORTAS ||area_number.109||, ||.data||
x5_L2
        DCD      0x00000000

        AREA ||area_number.110||, DATA, ALIGN=2

        EXPORTAS ||area_number.110||, ||.data||
x5_L1
        DCD      0x00000000

        AREA ||area_number.111||, DATA, ALIGN=2

        EXPORTAS ||area_number.111||, ||.data||
y6_L3
        DCD      0x00000000

        AREA ||area_number.112||, DATA, ALIGN=2

        EXPORTAS ||area_number.112||, ||.data||
y6_L2
        DCD      0x00000000

        AREA ||area_number.113||, DATA, ALIGN=2

        EXPORTAS ||area_number.113||, ||.data||
y6_L1
        DCD      0x00000000

        AREA ||area_number.114||, DATA, ALIGN=2

        EXPORTAS ||area_number.114||, ||.data||
x6_L3
        DCD      0x00000000

        AREA ||area_number.115||, DATA, ALIGN=2

        EXPORTAS ||area_number.115||, ||.data||
x6_L2
        DCD      0x00000000

        AREA ||area_number.116||, DATA, ALIGN=2

        EXPORTAS ||area_number.116||, ||.data||
x6_L1
        DCD      0x00000000

        AREA ||area_number.117||, DATA, ALIGN=2

        EXPORTAS ||area_number.117||, ||.data||
y7_L3
        DCD      0x00000000

        AREA ||area_number.118||, DATA, ALIGN=2

        EXPORTAS ||area_number.118||, ||.data||
y7_L2
        DCD      0x00000000

        AREA ||area_number.119||, DATA, ALIGN=2

        EXPORTAS ||area_number.119||, ||.data||
y7_L1
        DCD      0x00000000

        AREA ||area_number.120||, DATA, ALIGN=2

        EXPORTAS ||area_number.120||, ||.data||
x7_L3
        DCD      0x00000000

        AREA ||area_number.121||, DATA, ALIGN=2

        EXPORTAS ||area_number.121||, ||.data||
x7_L2
        DCD      0x00000000

        AREA ||area_number.122||, DATA, ALIGN=2

        EXPORTAS ||area_number.122||, ||.data||
x7_L1
        DCD      0x00000000

        AREA ||area_number.123||, DATA, ALIGN=2

        EXPORTAS ||area_number.123||, ||.data||
y8_L3
        DCD      0x00000000

        AREA ||area_number.124||, DATA, ALIGN=2

        EXPORTAS ||area_number.124||, ||.data||
y8_L2
        DCD      0x00000000

        AREA ||area_number.125||, DATA, ALIGN=2

        EXPORTAS ||area_number.125||, ||.data||
y8_L1
        DCD      0x00000000

        AREA ||area_number.126||, DATA, ALIGN=2

        EXPORTAS ||area_number.126||, ||.data||
x8_L3
        DCD      0x00000000

        AREA ||area_number.127||, DATA, ALIGN=2

        EXPORTAS ||area_number.127||, ||.data||
x8_L2
        DCD      0x00000000

        AREA ||area_number.128||, DATA, ALIGN=2

        EXPORTAS ||area_number.128||, ||.data||
x8_L1
        DCD      0x00000000

        AREA ||area_number.129||, DATA, ALIGN=2

        EXPORTAS ||area_number.129||, ||.data||
y9_L3
        DCD      0x00000000

        AREA ||area_number.130||, DATA, ALIGN=2

        EXPORTAS ||area_number.130||, ||.data||
y9_L2
        DCD      0x00000000

        AREA ||area_number.131||, DATA, ALIGN=2

        EXPORTAS ||area_number.131||, ||.data||
y9_L1
        DCD      0x00000000

        AREA ||area_number.132||, DATA, ALIGN=2

        EXPORTAS ||area_number.132||, ||.data||
x9_L3
        DCD      0x00000000

        AREA ||area_number.133||, DATA, ALIGN=2

        EXPORTAS ||area_number.133||, ||.data||
x9_L2
        DCD      0x00000000

        AREA ||area_number.134||, DATA, ALIGN=2

        EXPORTAS ||area_number.134||, ||.data||
x9_L1
        DCD      0x00000000

        AREA ||area_number.135||, DATA, ALIGN=2

        EXPORTAS ||area_number.135||, ||.data||
y10_L3
        DCD      0x00000000

        AREA ||area_number.136||, DATA, ALIGN=2

        EXPORTAS ||area_number.136||, ||.data||
y10_L2
        DCD      0x00000000

        AREA ||area_number.137||, DATA, ALIGN=2

        EXPORTAS ||area_number.137||, ||.data||
y10_L1
        DCD      0x00000000

        AREA ||area_number.138||, DATA, ALIGN=2

        EXPORTAS ||area_number.138||, ||.data||
x10_L3
        DCD      0x00000000

        AREA ||area_number.139||, DATA, ALIGN=2

        EXPORTAS ||area_number.139||, ||.data||
x10_L2
        DCD      0x00000000

        AREA ||area_number.140||, DATA, ALIGN=2

        EXPORTAS ||area_number.140||, ||.data||
x10_L1
        DCD      0x00000000

        AREA ||area_number.141||, DATA, ALIGN=2

        EXPORTAS ||area_number.141||, ||.data||
y1_R3
        DCD      0x00000000

        AREA ||area_number.142||, DATA, ALIGN=2

        EXPORTAS ||area_number.142||, ||.data||
y1_R2
        DCD      0x00000000

        AREA ||area_number.143||, DATA, ALIGN=2

        EXPORTAS ||area_number.143||, ||.data||
y1_R1
        DCD      0x00000000

        AREA ||area_number.144||, DATA, ALIGN=2

        EXPORTAS ||area_number.144||, ||.data||
x1_R3
        DCD      0x00000000

        AREA ||area_number.145||, DATA, ALIGN=2

        EXPORTAS ||area_number.145||, ||.data||
x1_R2
        DCD      0x00000000

        AREA ||area_number.146||, DATA, ALIGN=2

        EXPORTAS ||area_number.146||, ||.data||
x1_R1
        DCD      0x00000000

        AREA ||area_number.147||, DATA, ALIGN=2

        EXPORTAS ||area_number.147||, ||.data||
y2_R3
        DCD      0x00000000

        AREA ||area_number.148||, DATA, ALIGN=2

        EXPORTAS ||area_number.148||, ||.data||
y2_R2
        DCD      0x00000000

        AREA ||area_number.149||, DATA, ALIGN=2

        EXPORTAS ||area_number.149||, ||.data||
y2_R1
        DCD      0x00000000

        AREA ||area_number.150||, DATA, ALIGN=2

        EXPORTAS ||area_number.150||, ||.data||
x2_R3
        DCD      0x00000000

        AREA ||area_number.151||, DATA, ALIGN=2

        EXPORTAS ||area_number.151||, ||.data||
x2_R2
        DCD      0x00000000

        AREA ||area_number.152||, DATA, ALIGN=2

        EXPORTAS ||area_number.152||, ||.data||
x2_R1
        DCD      0x00000000

        AREA ||area_number.153||, DATA, ALIGN=2

        EXPORTAS ||area_number.153||, ||.data||
y3_R3
        DCD      0x00000000

        AREA ||area_number.154||, DATA, ALIGN=2

        EXPORTAS ||area_number.154||, ||.data||
y3_R2
        DCD      0x00000000

        AREA ||area_number.155||, DATA, ALIGN=2

        EXPORTAS ||area_number.155||, ||.data||
y3_R1
        DCD      0x00000000

        AREA ||area_number.156||, DATA, ALIGN=2

        EXPORTAS ||area_number.156||, ||.data||
x3_R3
        DCD      0x00000000

        AREA ||area_number.157||, DATA, ALIGN=2

        EXPORTAS ||area_number.157||, ||.data||
x3_R2
        DCD      0x00000000

        AREA ||area_number.158||, DATA, ALIGN=2

        EXPORTAS ||area_number.158||, ||.data||
x3_R1
        DCD      0x00000000

        AREA ||area_number.159||, DATA, ALIGN=2

        EXPORTAS ||area_number.159||, ||.data||
y4_R3
        DCD      0x00000000

        AREA ||area_number.160||, DATA, ALIGN=2

        EXPORTAS ||area_number.160||, ||.data||
y4_R2
        DCD      0x00000000

        AREA ||area_number.161||, DATA, ALIGN=2

        EXPORTAS ||area_number.161||, ||.data||
y4_R1
        DCD      0x00000000

        AREA ||area_number.162||, DATA, ALIGN=2

        EXPORTAS ||area_number.162||, ||.data||
x4_R3
        DCD      0x00000000

        AREA ||area_number.163||, DATA, ALIGN=2

        EXPORTAS ||area_number.163||, ||.data||
x4_R2
        DCD      0x00000000

        AREA ||area_number.164||, DATA, ALIGN=2

        EXPORTAS ||area_number.164||, ||.data||
x4_R1
        DCD      0x00000000

        AREA ||area_number.165||, DATA, ALIGN=2

        EXPORTAS ||area_number.165||, ||.data||
y5_R3
        DCD      0x00000000

        AREA ||area_number.166||, DATA, ALIGN=2

        EXPORTAS ||area_number.166||, ||.data||
y5_R2
        DCD      0x00000000

        AREA ||area_number.167||, DATA, ALIGN=2

        EXPORTAS ||area_number.167||, ||.data||
y5_R1
        DCD      0x00000000

        AREA ||area_number.168||, DATA, ALIGN=2

        EXPORTAS ||area_number.168||, ||.data||
x5_R3
        DCD      0x00000000

        AREA ||area_number.169||, DATA, ALIGN=2

        EXPORTAS ||area_number.169||, ||.data||
x5_R2
        DCD      0x00000000

        AREA ||area_number.170||, DATA, ALIGN=2

        EXPORTAS ||area_number.170||, ||.data||
x5_R1
        DCD      0x00000000

        AREA ||area_number.171||, DATA, ALIGN=2

        EXPORTAS ||area_number.171||, ||.data||
y6_R3
        DCD      0x00000000

        AREA ||area_number.172||, DATA, ALIGN=2

        EXPORTAS ||area_number.172||, ||.data||
y6_R2
        DCD      0x00000000

        AREA ||area_number.173||, DATA, ALIGN=2

        EXPORTAS ||area_number.173||, ||.data||
y6_R1
        DCD      0x00000000

        AREA ||area_number.174||, DATA, ALIGN=2

        EXPORTAS ||area_number.174||, ||.data||
x6_R3
        DCD      0x00000000

        AREA ||area_number.175||, DATA, ALIGN=2

        EXPORTAS ||area_number.175||, ||.data||
x6_R2
        DCD      0x00000000

        AREA ||area_number.176||, DATA, ALIGN=2

        EXPORTAS ||area_number.176||, ||.data||
x6_R1
        DCD      0x00000000

        AREA ||area_number.177||, DATA, ALIGN=2

        EXPORTAS ||area_number.177||, ||.data||
y7_R3
        DCD      0x00000000

        AREA ||area_number.178||, DATA, ALIGN=2

        EXPORTAS ||area_number.178||, ||.data||
y7_R2
        DCD      0x00000000

        AREA ||area_number.179||, DATA, ALIGN=2

        EXPORTAS ||area_number.179||, ||.data||
y7_R1
        DCD      0x00000000

        AREA ||area_number.180||, DATA, ALIGN=2

        EXPORTAS ||area_number.180||, ||.data||
x7_R3
        DCD      0x00000000

        AREA ||area_number.181||, DATA, ALIGN=2

        EXPORTAS ||area_number.181||, ||.data||
x7_R2
        DCD      0x00000000

        AREA ||area_number.182||, DATA, ALIGN=2

        EXPORTAS ||area_number.182||, ||.data||
x7_R1
        DCD      0x00000000

        AREA ||area_number.183||, DATA, ALIGN=2

        EXPORTAS ||area_number.183||, ||.data||
y8_R3
        DCD      0x00000000

        AREA ||area_number.184||, DATA, ALIGN=2

        EXPORTAS ||area_number.184||, ||.data||
y8_R2
        DCD      0x00000000

        AREA ||area_number.185||, DATA, ALIGN=2

        EXPORTAS ||area_number.185||, ||.data||
y8_R1
        DCD      0x00000000

        AREA ||area_number.186||, DATA, ALIGN=2

        EXPORTAS ||area_number.186||, ||.data||
x8_R3
        DCD      0x00000000

        AREA ||area_number.187||, DATA, ALIGN=2

        EXPORTAS ||area_number.187||, ||.data||
x8_R2
        DCD      0x00000000

        AREA ||area_number.188||, DATA, ALIGN=2

        EXPORTAS ||area_number.188||, ||.data||
x8_R1
        DCD      0x00000000

        AREA ||area_number.189||, DATA, ALIGN=2

        EXPORTAS ||area_number.189||, ||.data||
y9_R3
        DCD      0x00000000

        AREA ||area_number.190||, DATA, ALIGN=2

        EXPORTAS ||area_number.190||, ||.data||
y9_R2
        DCD      0x00000000

        AREA ||area_number.191||, DATA, ALIGN=2

        EXPORTAS ||area_number.191||, ||.data||
y9_R1
        DCD      0x00000000

        AREA ||area_number.192||, DATA, ALIGN=2

        EXPORTAS ||area_number.192||, ||.data||
x9_R3
        DCD      0x00000000

        AREA ||area_number.193||, DATA, ALIGN=2

        EXPORTAS ||area_number.193||, ||.data||
x9_R2
        DCD      0x00000000

        AREA ||area_number.194||, DATA, ALIGN=2

        EXPORTAS ||area_number.194||, ||.data||
x9_R1
        DCD      0x00000000

        AREA ||area_number.195||, DATA, ALIGN=2

        EXPORTAS ||area_number.195||, ||.data||
y10_R3
        DCD      0x00000000

        AREA ||area_number.196||, DATA, ALIGN=2

        EXPORTAS ||area_number.196||, ||.data||
y10_R2
        DCD      0x00000000

        AREA ||area_number.197||, DATA, ALIGN=2

        EXPORTAS ||area_number.197||, ||.data||
y10_R1
        DCD      0x00000000

        AREA ||area_number.198||, DATA, ALIGN=2

        EXPORTAS ||area_number.198||, ||.data||
x10_R3
        DCD      0x00000000

        AREA ||area_number.199||, DATA, ALIGN=2

        EXPORTAS ||area_number.199||, ||.data||
x10_R2
        DCD      0x00000000

        AREA ||area_number.200||, DATA, ALIGN=2

        EXPORTAS ||area_number.200||, ||.data||
x10_R1
        DCD      0x00000000

        AREA ||area_number.201||, DATA, ALIGN=2

        EXPORTAS ||area_number.201||, ||.data||
t_s
        DCD      0x00000000

        AREA ||area_number.202||, DATA, ALIGN=2

        EXPORTAS ||area_number.202||, ||.data||
t_e
        DCD      0x00000000

        AREA ||area_number.203||, DATA, ALIGN=2

        EXPORTAS ||area_number.203||, ||.data||
t_t
        DCD      0x00000000

        AREA ||area_number.204||, DATA, ALIGN=2

        EXPORTAS ||area_number.204||, ||.data||
sum_H
        DCD      0x00000000

        EXPORT I2S_IRQHandler [CODE]
        EXPORT filter [CODE]
        EXPORT filterInit [CODE]
        EXPORT filter_50 [CODE]
        EXPORT limiter [CODE]
        EXPORT triggerFilter [CODE]
        EXPORT t_a [DATA,SIZE=32]
        EXPORT firsr_trigger [DATA,SIZE=4]
        EXPORT filter_trigger [DATA,SIZE=4]
        EXPORT filter_srcbuf [DATA,SIZE=4]
        EXPORT filter_destbuf [DATA,SIZE=4]
        EXPORT filter_bypass [DATA,SIZE=4]
        EXPORT x1_hpL [DATA,SIZE=4]
        EXPORT x1_hpH [DATA,SIZE=4]
        EXPORT acc1_L [DATA,SIZE=4]
        EXPORT acc1_H [DATA,SIZE=4]
        EXPORT y1_hpL [DATA,SIZE=4]
        EXPORT y1_hpH [DATA,SIZE=4]
        EXPORT x2_hpL [DATA,SIZE=4]
        EXPORT x2_hpH [DATA,SIZE=4]
        EXPORT acc2_L [DATA,SIZE=4]
        EXPORT acc2_H [DATA,SIZE=4]
        EXPORT y2_hpL [DATA,SIZE=4]
        EXPORT y2_hpH [DATA,SIZE=4]
        EXPORT K1_HP [DATA,SIZE=4]
        EXPORT K2_HP [DATA,SIZE=4]
        EXPORT F_R_K11 [DATA,SIZE=4]
        EXPORT F_R_K12 [DATA,SIZE=4]
        EXPORT F_R_K13 [DATA,SIZE=4]
        EXPORT F_R_K14 [DATA,SIZE=4]
        EXPORT F_R_K15 [DATA,SIZE=4]
        EXPORT F_R_K21 [DATA,SIZE=4]
        EXPORT F_R_K22 [DATA,SIZE=4]
        EXPORT F_R_K23 [DATA,SIZE=4]
        EXPORT F_R_K24 [DATA,SIZE=4]
        EXPORT F_R_K25 [DATA,SIZE=4]
        EXPORT F_R_K31 [DATA,SIZE=4]
        EXPORT F_R_K32 [DATA,SIZE=4]
        EXPORT F_R_K33 [DATA,SIZE=4]
        EXPORT F_R_K34 [DATA,SIZE=4]
        EXPORT F_R_K35 [DATA,SIZE=4]
        EXPORT F_R_K41 [DATA,SIZE=4]
        EXPORT F_R_K42 [DATA,SIZE=4]
        EXPORT F_R_K43 [DATA,SIZE=4]
        EXPORT F_R_K44 [DATA,SIZE=4]
        EXPORT F_R_K45 [DATA,SIZE=4]
        EXPORT F_R_K51 [DATA,SIZE=4]
        EXPORT F_R_K52 [DATA,SIZE=4]
        EXPORT F_R_K53 [DATA,SIZE=4]
        EXPORT F_R_K54 [DATA,SIZE=4]
        EXPORT F_R_K55 [DATA,SIZE=4]
        EXPORT F_L_K11 [DATA,SIZE=4]
        EXPORT F_L_K12 [DATA,SIZE=4]
        EXPORT F_L_K13 [DATA,SIZE=4]
        EXPORT F_L_K14 [DATA,SIZE=4]
        EXPORT F_L_K15 [DATA,SIZE=4]
        EXPORT F_L_K21 [DATA,SIZE=4]
        EXPORT F_L_K22 [DATA,SIZE=4]
        EXPORT F_L_K23 [DATA,SIZE=4]
        EXPORT F_L_K24 [DATA,SIZE=4]
        EXPORT F_L_K25 [DATA,SIZE=4]
        EXPORT F_L_K31 [DATA,SIZE=4]
        EXPORT F_L_K32 [DATA,SIZE=4]
        EXPORT F_L_K33 [DATA,SIZE=4]
        EXPORT F_L_K34 [DATA,SIZE=4]
        EXPORT F_L_K35 [DATA,SIZE=4]
        EXPORT F_L_K4_SHIFT [DATA,SIZE=4]
        EXPORT F_L_K41 [DATA,SIZE=4]
        EXPORT F_L_K42 [DATA,SIZE=4]
        EXPORT F_L_K43 [DATA,SIZE=4]
        EXPORT F_L_K44 [DATA,SIZE=4]
        EXPORT F_L_K45 [DATA,SIZE=4]
        EXPORT F_L_K5_SHIFT [DATA,SIZE=4]
        EXPORT F_L_K51 [DATA,SIZE=4]
        EXPORT F_L_K52 [DATA,SIZE=4]
        EXPORT F_L_K53 [DATA,SIZE=4]
        EXPORT F_L_K54 [DATA,SIZE=4]
        EXPORT F_L_K55 [DATA,SIZE=4]
        EXPORT filter_rxbuf_flag [DATA,SIZE=4]
        EXPORT y1_L3 [DATA,SIZE=4]
        EXPORT y1_L2 [DATA,SIZE=4]
        EXPORT y1_L1 [DATA,SIZE=4]
        EXPORT x1_L3 [DATA,SIZE=4]
        EXPORT x1_L2 [DATA,SIZE=4]
        EXPORT x1_L1 [DATA,SIZE=4]
        EXPORT y2_L3 [DATA,SIZE=4]
        EXPORT y2_L2 [DATA,SIZE=4]
        EXPORT y2_L1 [DATA,SIZE=4]
        EXPORT x2_L3 [DATA,SIZE=4]
        EXPORT x2_L2 [DATA,SIZE=4]
        EXPORT x2_L1 [DATA,SIZE=4]
        EXPORT y3_L3 [DATA,SIZE=4]
        EXPORT y3_L2 [DATA,SIZE=4]
        EXPORT y3_L1 [DATA,SIZE=4]
        EXPORT x3_L3 [DATA,SIZE=4]
        EXPORT x3_L2 [DATA,SIZE=4]
        EXPORT x3_L1 [DATA,SIZE=4]
        EXPORT y4_L3 [DATA,SIZE=4]
        EXPORT y4_L2 [DATA,SIZE=4]
        EXPORT y4_L1 [DATA,SIZE=4]
        EXPORT x4_L3 [DATA,SIZE=4]
        EXPORT x4_L2 [DATA,SIZE=4]
        EXPORT x4_L1 [DATA,SIZE=4]
        EXPORT y5_L3 [DATA,SIZE=4]
        EXPORT y5_L2 [DATA,SIZE=4]
        EXPORT y5_L1 [DATA,SIZE=4]
        EXPORT x5_L3 [DATA,SIZE=4]
        EXPORT x5_L2 [DATA,SIZE=4]
        EXPORT x5_L1 [DATA,SIZE=4]
        EXPORT y6_L3 [DATA,SIZE=4]
        EXPORT y6_L2 [DATA,SIZE=4]
        EXPORT y6_L1 [DATA,SIZE=4]
        EXPORT x6_L3 [DATA,SIZE=4]
        EXPORT x6_L2 [DATA,SIZE=4]
        EXPORT x6_L1 [DATA,SIZE=4]
        EXPORT y7_L3 [DATA,SIZE=4]
        EXPORT y7_L2 [DATA,SIZE=4]
        EXPORT y7_L1 [DATA,SIZE=4]
        EXPORT x7_L3 [DATA,SIZE=4]
        EXPORT x7_L2 [DATA,SIZE=4]
        EXPORT x7_L1 [DATA,SIZE=4]
        EXPORT y8_L3 [DATA,SIZE=4]
        EXPORT y8_L2 [DATA,SIZE=4]
        EXPORT y8_L1 [DATA,SIZE=4]
        EXPORT x8_L3 [DATA,SIZE=4]
        EXPORT x8_L2 [DATA,SIZE=4]
        EXPORT x8_L1 [DATA,SIZE=4]
        EXPORT y9_L3 [DATA,SIZE=4]
        EXPORT y9_L2 [DATA,SIZE=4]
        EXPORT y9_L1 [DATA,SIZE=4]
        EXPORT x9_L3 [DATA,SIZE=4]
        EXPORT x9_L2 [DATA,SIZE=4]
        EXPORT x9_L1 [DATA,SIZE=4]
        EXPORT y10_L3 [DATA,SIZE=4]
        EXPORT y10_L2 [DATA,SIZE=4]
        EXPORT y10_L1 [DATA,SIZE=4]
        EXPORT x10_L3 [DATA,SIZE=4]
        EXPORT x10_L2 [DATA,SIZE=4]
        EXPORT x10_L1 [DATA,SIZE=4]
        EXPORT y1_R3 [DATA,SIZE=4]
        EXPORT y1_R2 [DATA,SIZE=4]
        EXPORT y1_R1 [DATA,SIZE=4]
        EXPORT x1_R3 [DATA,SIZE=4]
        EXPORT x1_R2 [DATA,SIZE=4]
        EXPORT x1_R1 [DATA,SIZE=4]
        EXPORT y2_R3 [DATA,SIZE=4]
        EXPORT y2_R2 [DATA,SIZE=4]
        EXPORT y2_R1 [DATA,SIZE=4]
        EXPORT x2_R3 [DATA,SIZE=4]
        EXPORT x2_R2 [DATA,SIZE=4]
        EXPORT x2_R1 [DATA,SIZE=4]
        EXPORT y3_R3 [DATA,SIZE=4]
        EXPORT y3_R2 [DATA,SIZE=4]
        EXPORT y3_R1 [DATA,SIZE=4]
        EXPORT x3_R3 [DATA,SIZE=4]
        EXPORT x3_R2 [DATA,SIZE=4]
        EXPORT x3_R1 [DATA,SIZE=4]
        EXPORT y4_R3 [DATA,SIZE=4]
        EXPORT y4_R2 [DATA,SIZE=4]
        EXPORT y4_R1 [DATA,SIZE=4]
        EXPORT x4_R3 [DATA,SIZE=4]
        EXPORT x4_R2 [DATA,SIZE=4]
        EXPORT x4_R1 [DATA,SIZE=4]
        EXPORT y5_R3 [DATA,SIZE=4]
        EXPORT y5_R2 [DATA,SIZE=4]
        EXPORT y5_R1 [DATA,SIZE=4]
        EXPORT x5_R3 [DATA,SIZE=4]
        EXPORT x5_R2 [DATA,SIZE=4]
        EXPORT x5_R1 [DATA,SIZE=4]
        EXPORT y6_R3 [DATA,SIZE=4]
        EXPORT y6_R2 [DATA,SIZE=4]
        EXPORT y6_R1 [DATA,SIZE=4]
        EXPORT x6_R3 [DATA,SIZE=4]
        EXPORT x6_R2 [DATA,SIZE=4]
        EXPORT x6_R1 [DATA,SIZE=4]
        EXPORT y7_R3 [DATA,SIZE=4]
        EXPORT y7_R2 [DATA,SIZE=4]
        EXPORT y7_R1 [DATA,SIZE=4]
        EXPORT x7_R3 [DATA,SIZE=4]
        EXPORT x7_R2 [DATA,SIZE=4]
        EXPORT x7_R1 [DATA,SIZE=4]
        EXPORT y8_R3 [DATA,SIZE=4]
        EXPORT y8_R2 [DATA,SIZE=4]
        EXPORT y8_R1 [DATA,SIZE=4]
        EXPORT x8_R3 [DATA,SIZE=4]
        EXPORT x8_R2 [DATA,SIZE=4]
        EXPORT x8_R1 [DATA,SIZE=4]
        EXPORT y9_R3 [DATA,SIZE=4]
        EXPORT y9_R2 [DATA,SIZE=4]
        EXPORT y9_R1 [DATA,SIZE=4]
        EXPORT x9_R3 [DATA,SIZE=4]
        EXPORT x9_R2 [DATA,SIZE=4]
        EXPORT x9_R1 [DATA,SIZE=4]
        EXPORT y10_R3 [DATA,SIZE=4]
        EXPORT y10_R2 [DATA,SIZE=4]
        EXPORT y10_R1 [DATA,SIZE=4]
        EXPORT x10_R3 [DATA,SIZE=4]
        EXPORT x10_R2 [DATA,SIZE=4]
        EXPORT x10_R1 [DATA,SIZE=4]
        EXPORT t_s [DATA,SIZE=4]
        EXPORT t_e [DATA,SIZE=4]
        EXPORT t_t [DATA,SIZE=4]
        EXPORT sum_H [DATA,SIZE=4]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT i2s_rxbuf [DATA]
        IMPORT i2s_txbuf [DATA]
        IMPORT i2s_pdma_rxbuf_flag [DATA]

        KEEP fsamples
        KEEP index
        KEEP fsum
        KEEP sum_LL
        KEEP sum_RL
        KEEP ||sum||
        KEEP i2s_status

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,3
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
