; generated by ARM C/C++ Compiler, 5.02 [Build 28]
; commandline ArmCC [--min_array_alignment=4 --split_sections --debug -c --asm --info=totals -o.\output\led.o --depend=.\output\led.d --cpu=Cortex-M0 --apcs=interwork -I..\CMSIS\CM0\DeviceSupport\Nuvoton\NUC123Series -I..\CMSIS\CM0\CoreSupport -I..\INC\DrvInc -I..\INC\SysInc -IC:\Keil\ARM\RV31\INC -IC:\Keil\ARM\CMSIS\Include -D__MICROLIB --omf_browse=.\output\led.crf ..\AppSrc\led.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.CHOOSE_BT_INPUT||, CODE, READONLY, ALIGN=2

CHOOSE_BT_INPUT PROC
        LDR      r1,|L1.20|
        MOVS     r0,#0
        STR      r0,[r1,#0]
        LDR      r1,|L1.20|
        MOVS     r0,#1
        SUBS     r1,r1,#0x24
        STR      r0,[r1,#0]
        SUBS     r1,r1,#4
        STR      r0,[r1,#0]
        BX       lr
        ENDP

|L1.20|
        DCD      0x50004278

        AREA ||i.DECT_DC||, CODE, READONLY, ALIGN=2

DECT_DC PROC
        LDR      r0,|L2.16|
        LDR      r0,[r0,#0]
        CMP      r0,#0
        BEQ      |L2.12|
        MOVS     r0,#0
        BX       lr
|L2.12|
        MOVS     r0,#1
        BX       lr
        ENDP

|L2.16|
        DCD      0x5000423c

        AREA ||i.GPIO_SET_MODE||, CODE, READONLY, ALIGN=1

GPIO_SET_MODE PROC
        PUSH     {r4,lr}
        LDR      r3,[r0,#0]
        LSLS     r1,r1,#1
        MOVS     r4,#3
        LSLS     r4,r4,r1
        BICS     r3,r3,r4
        LSLS     r2,r2,r1
        ORRS     r3,r3,r2
        STR      r3,[r0,#0]
        POP      {r4,pc}
        ENDP


        AREA ||i.TMR0_IRQHandler||, CODE, READONLY, ALIGN=2

TMR0_IRQHandler PROC
        PUSH     {r4-r7,lr}
        LDR      r1,|L4.108|
        LDR      r0,[r1,#8]
        MOVS     r2,#1
        ORRS     r0,r0,r2
        STR      r0,[r1,#8]
        LDR      r5,|L4.112|
        MOVS     r3,#0
        LDR      r0,[r5,#0x30]  ; ptimer
        ADDS     r0,r0,#1
        STR      r0,[r5,#0x30]  ; ptimer
        CMP      r0,#0xc8
        BLS      |L4.28|
        STR      r3,[r5,#0x30]  ; ptimer
|L4.28|
        LDR      r0,[r5,#0x24]  ; R_C
        LDR      r6,|L4.112|
        LSLS     r0,r0,#2
        ADDS     r6,r6,#0x70
        LDR      r4,[r6,r0]
        LDR      r1,[r5,#0x30]  ; ptimer
        LDR      r0,|L4.116|
        CMP      r4,r1
        BLS      |L4.50|
        STR      r3,[r0,#0]
        B        |L4.52|
|L4.50|
        STR      r2,[r0,#0]
|L4.52|
        LDR      r0,[r5,#0x28]  ; B_C
        LDR      r7,|L4.116|
        LSLS     r0,r0,#2
        LDR      r4,[r6,r0]
        LDR      r0,|L4.120|
        ADDS     r7,r7,#4
        LDRB     r0,[r0,#0]
        CMP      r4,r1
        BLS      |L4.78|
        CMP      r0,#0
        BNE      |L4.80|
        STR      r3,[r7,#0]
        B        |L4.80|
|L4.78|
        STR      r2,[r7,#0]
|L4.80|
        LDR      r4,[r5,#0x2c]  ; G_C
        LSLS     r4,r4,#2
        LDR      r5,[r6,r4]
        LDR      r4,|L4.116|
        ADDS     r4,r4,#8
        CMP      r5,r1
        BLS      |L4.102|
        CMP      r0,#0
        BNE      |L4.100|
        STR      r3,[r4,#0]
|L4.100|
        POP      {r4-r7,pc}
|L4.102|
        STR      r2,[r4,#0]
        POP      {r4-r7,pc}
        ENDP

        DCW      0x0000
|L4.108|
        DCD      0x40010000
|L4.112|
        DCD      ||.data||
|L4.116|
        DCD      0x500042c4
|L4.120|
        DCD      sleep_flag

        AREA ||i.breathingColor||, CODE, READONLY, ALIGN=2

breathingColor PROC
        PUSH     {r3-r7,lr}
        LDR      r4,|L5.236|
        LDR      r1,[r4,#0x44]  ; cc
        LDR      r0,[r4,#0x38]  ; breath_flag
        ADDS     r1,r1,#1
        STR      r1,[r4,#0x44]  ; cc
        LSLS     r1,r1,#31
        BEQ      |L5.72|
        LDR      r3,[r4,#0x34]
        MOVS     r6,#0x28
        MOVS     r7,#0xff
        ADDS     r1,r3,#1
        LDR      r2,[r4,#0x6c]
        MOVS     r5,#0
|L5.28|
        CMP      r0,#6
        BEQ      |L5.192|
        BGT      |L5.74|
        CMP      r0,#1
        BEQ      |L5.120|
        CMP      r0,#2
        BEQ      |L5.142|
        CMP      r0,#4
        BEQ      |L5.162|
        CMP      r0,#5
        BNE      |L5.72|
        STR      r5,[r4,#0x2c]  ; G_C
        STR      r1,[r4,#0x34]  ; ck
        CMP      r1,#0x13
        BLS      |L5.188|
        SUBS     r0,r6,r1
        STR      r0,[r4,#0x28]  ; B_C
        CMP      r1,#0x27
        BLS      |L5.68|
        STR      r5,[r4,#0x34]  ; ck
|L5.68|
        LDR      r0,[r4,#0x28]  ; B_C
|L5.70|
        STR      r0,[r4,#0x24]  ; R_C
|L5.72|
        POP      {r3-r7,pc}
|L5.74|
        CMP      r0,#9
        BEQ      |L5.94|
        CMP      r0,#0xaa
        BEQ      |L5.226|
        CMP      r0,#0xbb
        BNE      |L5.72|
        CMP      r3,#0
        BEQ      |L5.230|
|L5.90|
        MOV      r0,r2
        B        |L5.28|
|L5.94|
        STR      r5,[r4,#0x24]  ; R_C
        STR      r5,[r4,#0x2c]  ; G_C
        STR      r1,[r4,#0x34]  ; ck
        CMP      r1,#0x13
        BLS      |L5.110|
        SUBS     r0,r6,r1
        STR      r0,[r4,#0x28]  ; B_C
        B        |L5.112|
|L5.110|
        STR      r1,[r4,#0x28]  ; B_C
|L5.112|
        CMP      r1,#0x27
        BLS      |L5.72|
        STR      r5,[r4,#0x34]  ; ck
        POP      {r3-r7,pc}
|L5.120|
        STR      r5,[r4,#0x28]  ; B_C
        ADDS     r1,r1,#1
        STR      r5,[r4,#0x2c]  ; G_C
        STR      r1,[r4,#0x34]  ; ck
        CMP      r1,#0x13
        BLS      |L5.138|
        SUBS     r0,r6,r1
        STR      r0,[r4,#0x24]  ; R_C
        B        |L5.112|
|L5.138|
        STR      r1,[r4,#0x24]  ; R_C
        POP      {r3-r7,pc}
|L5.142|
        STR      r5,[r4,#0x28]  ; B_C
        STR      r5,[r4,#0x24]  ; R_C
        STR      r1,[r4,#0x34]  ; ck
        CMP      r1,#0x13
        BLS      |L5.158|
        SUBS     r0,r6,r1
        STR      r0,[r4,#0x2c]  ; G_C
        B        |L5.112|
|L5.158|
        STR      r1,[r4,#0x2c]  ; G_C
        POP      {r3-r7,pc}
|L5.162|
        STR      r5,[r4,#0x28]  ; B_C
        STR      r1,[r4,#0x34]  ; ck
        CMP      r1,#0x13
        BLS      |L5.184|
        SUBS     r0,r6,r1
        STR      r0,[r4,#0x2c]  ; G_C
        CMP      r1,#0x27
        BLS      |L5.180|
        STR      r5,[r4,#0x34]  ; ck
|L5.180|
        LDR      r0,[r4,#0x2c]  ; G_C
        B        |L5.70|
|L5.184|
        STR      r1,[r4,#0x2c]  ; G_C
        B        |L5.180|
|L5.188|
        STR      r1,[r4,#0x28]  ; B_C
        B        |L5.68|
|L5.192|
        STR      r1,[r4,#0x34]  ; ck
        CMP      r1,#0x13
        BLS      |L5.204|
        SUBS     r0,r6,r1
        STR      r0,[r4,#0x28]  ; B_C
        B        |L5.206|
|L5.204|
        STR      r1,[r4,#0x28]  ; B_C
|L5.206|
        CMP      r1,#0x25
        BLS      |L5.212|
        STR      r5,[r4,#0x34]  ; ck
|L5.212|
        LDR      r0,[r4,#0x28]  ; B_C
        STR      r0,[r4,#0x2c]  ; G_C
        LSLS     r0,r0,#1
        MOVS     r1,#3
        BL       __aeabi_uidivmod
        B        |L5.70|
|L5.226|
        CMP      r3,#0x14
        BNE      |L5.90|
|L5.230|
        STR      r7,[r4,#0x38]  ; breath_flag
        POP      {r3-r7,pc}
        ENDP

        DCW      0x0000
|L5.236|
        DCD      ||.data||

        AREA ||i.fadeoff||, CODE, READONLY, ALIGN=2

fadeoff PROC
        LDR      r1,|L6.16|
        MOVS     r2,#0x14
        STR      r2,[r1,#0x34]  ; ck
        STR      r0,[r1,#0x6c]  ; fade_color
        MOVS     r0,#0xbb
        STR      r0,[r1,#0x38]  ; breath_flag
        BX       lr
        ENDP

        DCW      0x0000
|L6.16|
        DCD      ||.data||

        AREA ||i.fadeon||, CODE, READONLY, ALIGN=2

fadeon PROC
        LDR      r1,|L7.16|
        MOVS     r2,#0
        STR      r2,[r1,#0x34]  ; ck
        STR      r0,[r1,#0x6c]  ; fade_color
        MOVS     r0,#0xaa
        STR      r0,[r1,#0x38]  ; breath_flag
        BX       lr
        ENDP

        DCW      0x0000
|L7.16|
        DCD      ||.data||

        AREA ||i.ledColorSet||, CODE, READONLY, ALIGN=2

ledColorSet PROC
        PUSH     {r4-r7,lr}
        MOVS     r4,#0
        MOVS     r6,#0xc
        MOVS     r7,#6
        LDR      r1,|L8.112|
        MOVS     r2,#0xf
        MOVS     r5,#0x12
        MOVS     r3,r0
        BL       __ARM_common_switch8
        DCB      0x0d,0x08,0x0a,0x0f
        DCB      0x0d,0x15,0x19,0x1d
        DCB      0x11,0x0f,0x0d,0x21
        DCB      0x25,0x2a,0x18,0x00
        STR      r4,[r1,#0x24]  ; R_C
        B        |L8.42|
        STR      r2,[r1,#0x24]  ; R_C
|L8.42|
        STR      r4,[r1,#0x2c]  ; G_C
        B        |L8.66|
        STR      r4,[r1,#0x24]  ; R_C
        B        |L8.72|
        STR      r4,[r1,#0x24]  ; R_C
        B        |L8.64|
        MOVS     r0,#0xa
        STR      r2,[r1,#0x24]  ; R_C
        STR      r0,[r1,#0x2c]  ; G_C
        B        |L8.74|
        STR      r2,[r1,#0x24]  ; R_C
|L8.64|
        STR      r2,[r1,#0x2c]  ; G_C
|L8.66|
        STR      r4,[r1,#0x28]  ; B_C
        POP      {r4-r7,pc}
        STR      r2,[r1,#0x24]  ; R_C
|L8.72|
        STR      r4,[r1,#0x2c]  ; G_C
|L8.74|
        STR      r2,[r1,#0x28]  ; B_C
        POP      {r4-r7,pc}
        STR      r5,[r1,#0x2c]  ; G_C
        STR      r6,[r1,#0x24]  ; R_C
        STR      r5,[r1,#0x28]  ; B_C
        POP      {r4-r7,pc}
        STR      r5,[r1,#0x2c]  ; G_C
        MOVS     r0,#9
        STR      r2,[r1,#0x24]  ; R_C
        B        |L8.100|
        STR      r7,[r1,#0x24]  ; R_C
        MOVS     r0,#4
        STR      r6,[r1,#0x2c]  ; G_C
|L8.100|
        STR      r0,[r1,#0x28]  ; B_C
        POP      {r4-r7,pc}
        STR      r7,[r1,#0x2c]  ; G_C
        STR      r7,[r1,#0x28]  ; B_C
        STR      r6,[r1,#0x24]  ; R_C
        POP      {r4-r7,pc}
        ENDP

|L8.112|
        DCD      ||.data||

        AREA ||i.ledInit||, CODE, READONLY, ALIGN=2

ledInit PROC
        PUSH     {r4-r6,lr}
        LDR      r0,|L9.104|
        LDR      r1,[r0,#0x14]
        MOVS     r2,#7
        LSLS     r2,r2,#8
        BICS     r1,r1,r2
        STR      r1,[r0,#0x14]
        LDR      r5,|L9.108|
        LSLS     r3,r0,#19
        MOVS     r2,#0xa
        MOVS     r1,#0x15
        MOV      r0,r5
        BL       DrvTIMER_Init
        LDR      r1,|L9.112|
        LDR      r0,[r1,#0]
        MOVS     r4,#0
        LSRS     r0,r0,#8
        LSLS     r0,r0,#8
        MOVS     r2,#0x80
        ORRS     r0,r0,r2
        STR      r0,[r1,#0]
        LSLS     r1,r1,#26
        MOV      r0,r5
        BL       DrvTIMER_EnableInt
        LDR      r1,[r5,#0]
        LSLS     r0,r5,#14
        ORRS     r1,r1,r0
        STR      r1,[r5,#0]
        LDR      r0,|L9.116|
        MOVS     r2,#1
        STR      r4,[r0,#0x2c]  ; G_C
        STR      r4,[r0,#0x28]  ; B_C
        STR      r4,[r0,#0x24]  ; R_C
        LDR      r4,|L9.120|
        MOV      r1,r2
        MOV      r0,r4
        BL       GPIO_SET_MODE
        MOVS     r2,#1
        MOVS     r1,#2
        MOV      r0,r4
        BL       GPIO_SET_MODE
        MOVS     r2,#1
        MOVS     r1,#3
        MOV      r0,r4
        BL       GPIO_SET_MODE
        POP      {r4-r6,pc}
        ENDP

        DCW      0x0000
|L9.104|
        DCD      0x50000200
|L9.108|
        DCD      0x40010000
|L9.112|
        DCD      0xe000e408
|L9.116|
        DCD      ||.data||
|L9.120|
        DCD      0x500040c0

        AREA ||i.ledTask||, CODE, READONLY, ALIGN=2

ledTask PROC
        PUSH     {r3-r7,lr}
        LDR      r0,|L10.1020|
        MOVS     r5,#1
        LDRB     r0,[r0,#0]  ; dev_state
        LDR      r6,|L10.1024|
        MOVS     r4,#0
        LDR      r7,|L10.1028|
        CMP      r0,#0
        BEQ      |L10.272|
        LDR      r0,|L10.1032|
        LDR      r0,[r0,#0]
        CMP      r0,#0
        BNE      |L10.30|
        BL       DWHP83DealMsg
|L10.30|
        LDR      r0,|L10.1036|
        LDRB     r1,[r0,#0]  ; battery_high_flag
        CMP      r1,#2
        BNE      |L10.44|
        STRB     r4,[r7,#6]
        STRB     r4,[r7,#7]
        STRB     r4,[r0,#0]
|L10.44|
        LDR      r0,|L10.1040|
        LDRB     r0,[r0,#0]  ; Core_tx_flag
        CMP      r0,#0
        BEQ      |L10.58|
        LDRB     r0,[r7,#8]  ; Core_tx_counter
        ADDS     r0,r0,#1
        STRB     r0,[r7,#8]
|L10.58|
        LDRB     r0,[r7,#8]  ; Core_tx_counter
        CMP      r0,#0x32
        BNE      |L10.68|
        BL       DWHP83Mute
|L10.68|
        LDRB     r0,[r7,#8]  ; Core_tx_counter
        CMP      r0,#0x96
        BLS      |L10.84|
        LDR      r0,|L10.1040|
        STRB     r4,[r7,#8]
        STRB     r4,[r0,#0]
        BL       DWHP83UnMute
|L10.84|
        LDR      r0,|L10.1044|
        LDRB     r0,[r0,#0]  ; change_channal_flag
        CMP      r0,#0
        LDR      r0,[r7,#0x40]  ; change_channal_counter
        BEQ      |L10.98|
        ADDS     r0,r0,#1
        STR      r0,[r7,#0x40]  ; change_channal_counter
|L10.98|
        CMP      r0,#1
        BEQ      |L10.108|
        CMP      r0,#0x32
        BEQ      |L10.120|
        B        |L10.270|
|L10.108|
        LDR      r0,|L10.1048|
        LDRB     r0,[r0,#0]  ; SB_flag
        CMP      r0,#0
        BEQ      |L10.354|
        STRB     r5,[r7,#4]
        B        |L10.354|
|L10.120|
        LDR      r0,|L10.1048|
        LDRB     r0,[r0,#0]  ; SB_flag
        CMP      r0,#0
        BEQ      |L10.268|
        LDR      r0,|L10.1052|
        LDRB     r0,[r0,#0]  ; soundbar_multiroom_flag
        CMP      r0,#0
        BEQ      |L10.142|
        BL       DWHP83Mute
        B        |L10.146|
|L10.142|
        BL       DWHP83UnMute
|L10.146|
        LDRB     r0,[r6,#0]  ; dev_input
        CMP      r0,#1
        BEQ      |L10.214|
        BL       soundbar_coco_check
        CMP      r0,#0
        BNE      |L10.180|
        BL       DWHP83toEXT_MCU
        MOVS     r0,#0x64
        BL       sysDelayMs
        BL       set_soundbar_coco
        MOVS     r0,#0x64
        BL       sysDelayMs
|L10.180|
        BL       Dwhp83CuMuDetect
        LDR      r0,|L10.1056|
        STR      r4,[r0,#0]  ; Dwhp83_flag
        LDR      r0,|L10.1060|
        LDR      r1,[r0,#0]  ; Dwhp83_CuMu
        LDR      r0,|L10.1064|
        CMP      r1,r0
        BNE      |L10.268|
        BL       DWHP83toEXT_MCU
        MOVS     r0,#0x64
        BL       sysDelayMs
        BL       Dwhp83Master
        B        |L10.268|
|L10.214|
        BL       Dwhp83CuMuDetect
        LDR      r0,|L10.1060|
        LDR      r1,[r0,#0]  ; Dwhp83_CuMu
        LDR      r0,|L10.1068|
        CMP      r1,r0
        BNE      |L10.238|
        BL       change_to_local_coco
        MOVS     r0,#0x64
        BL       sysDelayMs
|L10.238|
        BL       soundbar_coco_check
        CMP      r0,#0
        BEQ      |L10.250|
        BL       set_local_coco
|L10.250|
        LDR      r0,|L10.1056|
        STR      r4,[r0,#0]  ; Dwhp83_flag
        LDR      r0,|L10.1060|
        LDR      r1,[r0,#0]  ; Dwhp83_CuMu
        LDR      r0,|L10.1068|
        CMP      r1,r0
        BNE      |L10.268|
        BL       Dwhp83Slave
|L10.268|
        STRB     r4,[r7,#4]
|L10.270|
        B        |L10.274|
|L10.272|
        B        |L10.1944|
|L10.274|
        LDR      r0,[r7,#0x40]  ; change_channal_counter
        CMP      r0,#0xdc
        BLS      |L10.354|
        LDR      r0,|L10.1044|
        STR      r4,[r7,#0x40]  ; change_channal_counter
        STRB     r4,[r0,#0]
        LDR      r0,|L10.1052|
        LDRB     r0,[r0,#0]  ; soundbar_multiroom_flag
        CMP      r0,#0
        BEQ      |L10.354|
        LDR      r0,|L10.1072|
        STRB     r5,[r0,#0]
        BL       soundbar_coco_check
        CMP      r0,#0
        BNE      |L10.314|
        BL       isDwhp83Linked
        CMP      r0,#0
        BNE      |L10.350|
|L10.314|
        BL       change_to_local_coco
        MOVS     r0,#0x64
        BL       sysDelayMs
        BL       DWHP83Mute
        BL       set_local_coco
        MOVS     r0,#0x64
        BL       sysDelayMs
        BL       Dwhp83Slave
        BL       DWP83SpiritTask
        LDR      r0,|L10.1076|
        STRB     r5,[r0,#0]
|L10.350|
        LDR      r0,|L10.1052|
        STRB     r4,[r0,#0]
|L10.354|
        LDR      r0,|L10.1072|
        LDRB     r1,[r0,#0]  ; TX_sound_flag
        CMP      r1,#0
        BEQ      |L10.378|
        LDRB     r0,[r7,#9]  ; TX_sounder_counter
        ADDS     r0,r0,#1
        UXTB     r0,r0
        STRB     r0,[r7,#9]
        STRB     r5,[r7,#4]
        CMP      r0,#0x58
        BEQ      |L10.384|
        B        |L10.406|
|L10.378|
        STRB     r4,[r7,#4]
        STRB     r4,[r7,#9]
        B        |L10.406|
|L10.384|
        ADDS     r1,r1,#1
        LDR      r0,|L10.1072|
        UXTB     r1,r1
        STRB     r4,[r7,#9]
        STRB     r1,[r0,#0]
        CMP      r1,#0x2a
        BLS      |L10.400|
        STRB     r4,[r0,#0]
|L10.400|
        MOVS     r0,#0x30
        BL       playMusic
|L10.406|
        LDR      r0,|L10.1080|
        LDRB     r1,[r0,#0]  ; bt_amp_start_flag
        CMP      r1,#0
        LDR      r1,[r7,#0x54]  ; bt_amp_start_time
        BEQ      |L10.420|
        ADDS     r1,r1,#1
        STR      r1,[r7,#0x54]  ; bt_amp_start_time
|L10.420|
        CMP      r1,#0x14
        BCC      |L10.428|
        STR      r4,[r7,#0x54]  ; bt_amp_start_time
        STRB     r4,[r0,#0]
|L10.428|
        LDR      r0,|L10.1084|
        LDRB     r0,[r0,#0]  ; play_music_flag
        SUBS     r1,r0,#1
        CMP      r1,#0x27
        BCS      |L10.566|
        LDRB     r1,[r7,#3]  ; key_time_count
        ADDS     r1,r1,#1
        UXTB     r1,r1
        STRB     r1,[r7,#3]
        CMP      r1,#0x14
        BLS      |L10.566|
        ADDS     r0,r0,#1
        LDR      r2,|L10.1084|
        UXTB     r0,r0
        STRB     r0,[r2,#0]
        CMP      r0,#2
        BEQ      |L10.608|
        CMP      r0,#3
        BEQ      |L10.612|
        LDR      r1,|L10.1088|
        CMP      r0,#4
        BEQ      |L10.640|
        CMP      r0,#5
        BEQ      |L10.616|
        CMP      r0,#6
        BEQ      |L10.644|
        CMP      r0,#7
        BEQ      |L10.648|
        CMP      r0,#0xc
        BEQ      |L10.624|
        CMP      r0,#0xd
        BEQ      |L10.612|
        LDR      r1,|L10.1092|
        CMP      r0,#0xe
        BEQ      |L10.640|
        CMP      r0,#0xf
        BEQ      |L10.616|
        CMP      r0,#0x10
        BEQ      |L10.644|
        CMP      r0,#0x11
        BEQ      |L10.648|
        CMP      r0,#0x16
        BEQ      |L10.628|
        CMP      r0,#0x17
        BEQ      |L10.612|
        LDR      r1,|L10.1096|
        CMP      r0,#0x18
        BEQ      |L10.640|
        CMP      r0,#0x19
        BEQ      |L10.616|
        CMP      r0,#0x1a
        BEQ      |L10.644|
        CMP      r0,#0x1b
        BEQ      |L10.648|
        CMP      r0,#0x20
        BEQ      |L10.632|
        CMP      r0,#0x21
        BEQ      |L10.612|
        LDR      r1,|L10.1100|
        CMP      r0,#0x22
        BEQ      |L10.640|
        CMP      r0,#0x23
        BEQ      |L10.616|
        CMP      r0,#0x24
        BEQ      |L10.644|
        CMP      r0,#0x25
        BEQ      |L10.648|
        STRB     r4,[r2,#0]
|L10.564|
        STRB     r4,[r7,#3]
|L10.566|
        LDR      r0,|L10.1084|
        LDRB     r0,[r0,#0]  ; play_music_flag
        CMP      r0,#0x28
        BLS      |L10.676|
        LDRB     r1,[r7,#3]  ; key_time_count
        ADDS     r1,r1,#1
        UXTB     r1,r1
        STRB     r1,[r7,#3]
        CMP      r1,#0x1e
        BLS      |L10.676|
        CMP      r0,#0x82
        BEQ      |L10.652|
        CMP      r0,#0x84
        BEQ      |L10.656|
        CMP      r0,#0x88
        BEQ      |L10.660|
        CMP      r0,#0x90
        BEQ      |L10.664|
        CMP      r0,#0xc0
        BEQ      |L10.668|
        B        |L10.674|
|L10.608|
        MOVS     r0,#0x2b
        B        |L10.634|
|L10.612|
        MOVS     r0,#0x2a
        B        |L10.634|
|L10.616|
        MOVS     r0,#0x29
        B        |L10.634|
|L10.620|
        SUBS     r0,r0,#0x11
        B        |L10.634|
|L10.624|
        MOVS     r0,#0x2c
        B        |L10.634|
|L10.628|
        MOVS     r0,#0x2e
        B        |L10.634|
|L10.632|
        MOVS     r0,#0x2d
|L10.634|
        BL       playMusic
        B        |L10.564|
|L10.640|
        LDRB     r0,[r1,#0]  ; FLASH_VERSION_NUMBER
        B        |L10.620|
|L10.644|
        LDRB     r0,[r1,#2]  ; FLASH_VERSION_NUMBER
        B        |L10.620|
|L10.648|
        LDRB     r0,[r1,#3]  ; FLASH_VERSION_NUMBER
        B        |L10.620|
|L10.652|
        MOVS     r0,#0x20
        B        |L10.670|
|L10.656|
        MOVS     r0,#0x21
        B        |L10.670|
|L10.660|
        MOVS     r0,#0x22
        B        |L10.670|
|L10.664|
        MOVS     r0,#0x23
        B        |L10.670|
|L10.668|
        MOVS     r0,#0x24
|L10.670|
        BL       playMusic
|L10.674|
        STRB     r4,[r7,#3]
|L10.676|
        LDR      r0,|L10.1076|
        LDRB     r0,[r0,#0]  ; TX_flag
        CMP      r0,#1
        LDR      r0,[r7,#0x58]  ; cct
        BNE      |L10.690|
        ADDS     r0,r0,#1
        STR      r0,[r7,#0x58]  ; cct
|L10.690|
        CMP      r0,#2
        BNE      |L10.702|
        BL       MU_tell_CU_change
        BL       DWP83SpiritTask
|L10.702|
        LDR      r0,[r7,#0x58]  ; cct
        CMP      r0,#0xa0
        BNE      |L10.712|
        BL       MU_tell_CU_change
|L10.712|
        LDR      r0,[r7,#0x58]  ; cct
        CMP      r0,#0xdc
        BLS      |L10.822|
        STRB     r4,[r7,#5]
        STR      r4,[r7,#0x58]  ; cct
        BL       MU_tell_CU_change
        LDR      r0,|L10.1076|
        LDRB     r0,[r0,#0]  ; TX_flag
        CMP      r0,#1
        BNE      |L10.822|
        BL       Dwhp83CuMuDetect
        CMP      r0,#0
        BEQ      |L10.818|
        LDR      r0,|L10.1060|
        LDR      r1,[r0,#0]  ; Dwhp83_CuMu
        LDR      r0,|L10.1064|
        CMP      r1,r0
        BNE      |L10.818|
        BL       Dwhp83GetStatus
        LDR      r0,|L10.1104|
        LDRB     r0,[r0,#0]  ; dwhp83_status
        CMP      r0,#0
        BEQ      |L10.836|
        BL       isDwhp83Linked
        CMP      r0,#0
        BEQ      |L10.836|
        BL       MU_tell_CU_change
        LDR      r0,|L10.1056|
        LDR      r1,|L10.1056|
        LDR      r0,[r0,#0]  ; Dwhp83_flag
        ORRS     r0,r0,r5
        STR      r0,[r1,#0]  ; Dwhp83_flag
        BL       DWP83SpiritTask
        BL       Dwhp83Master
        MOVS     r0,#0x7d
        LSLS     r0,r0,#4
        BL       sysDelayMs
        MOVS     r0,#0x30
        BL       playMusic
        LDR      r0,|L10.1056|
        STRB     r4,[r7,#9]
        STR      r4,[r0,#0]  ; Dwhp83_flag
        BL       DWP83SpiritTask
|L10.818|
        LDR      r0,|L10.1076|
        STRB     r4,[r0,#0]
|L10.822|
        LDR      r0,[r7,#0x60]  ; ccr
        CMP      r0,#0xc8
        BLS      |L10.866|
        LDR      r0,|L10.1108|
        STR      r4,[r7,#0x60]  ; ccr
        STRB     r4,[r0,#0]
        B        |L10.878|
|L10.836|
        BL       DWP83SpiritTask
        BL       MU_tell_CU_change
        BL       Dwhp83Master
        MOVS     r0,#0x7d
        LSLS     r0,r0,#4
        BL       sysDelayMs
        MOVS     r0,#0x30
        BL       playMusic
        STRB     r4,[r7,#9]
        B        |L10.818|
|L10.866|
        LDR      r1,|L10.1108|
        LDRB     r1,[r1,#0]  ; power_first_on_flag
        CMP      r1,#0
        BEQ      |L10.878|
        ADDS     r0,r0,#1
        STR      r0,[r7,#0x60]  ; ccr
|L10.878|
        BL       callDetect
        LDRB     r2,[r7,#0]  ; state_color
        CMP      r2,#8
        BEQ      |L10.906|
        MOVS     r1,#0
|L10.890|
        TST      r0,r1
        BEQ      |L10.900|
        LDR      r0,[r7,#0x10]  ; bt_hang_up_signal
        CMP      r0,#1
        BEQ      |L10.910|
|L10.900|
        CMP      r2,#5
        BEQ      |L10.938|
        B        |L10.982|
|L10.906|
        MOVS     r1,#1
        B        |L10.890|
|L10.910|
        STR      r4,[r7,#0x10]  ; bt_hang_up_signal
        BL       isCallIn
        CMP      r0,#0
        BEQ      |L10.932|
        BL       openCall
        MOVS     r0,#0x14
        BL       sysDelayMs
        B        |L10.2428|
|L10.932|
        BL       closeCall
        B        |L10.2428|
|L10.938|
        LDR      r0,[r7,#0x68]  ; ccp
        ADDS     r0,r0,#1
        STR      r0,[r7,#0x68]  ; ccp
        CMP      r0,#0x1e
        BLS      |L10.954|
        BL       Dwhp83GetStatus
        STR      r4,[r7,#0x68]  ; ccp
|L10.954|
        LDR      r0,|L10.1104|
        LDRB     r0,[r0,#0]  ; dwhp83_status
        CMP      r0,#0
        BNE      |L10.982|
        LDR      r0,[r7,#0x5c]  ; cck
        CMP      r0,#0
        BEQ      |L10.974|
        SUBS     r0,r0,#1
        STR      r0,[r7,#0x5c]  ; cck
        B        |L10.982|
|L10.974|
        MOVS     r0,#0xa
        STR      r0,[r7,#0x5c]  ; cck
        MOVS     r0,#5
        STR      r0,[r7,#0xc]  ; led_flash
|L10.982|
        LDR      r0,[r7,#0x48]  ; soundbar_alive_counter
        CMP      r0,#0xf
        BNE      |L10.1146|
        BL       Dwhp83CuMuDetect
        LDR      r0,|L10.1060|
        LDR      r1,[r0,#0]  ; Dwhp83_CuMu
        LDR      r0,|L10.1064|
        CMP      r1,r0
        BNE      |L10.1146|
        BL       RX_SB_alive
        BL       isMute
        CMP      r0,#0
        BNE      |L10.1146|
        LDR      r0,|L10.1112|
        LDR      r0,[r0,#0]  ; amp_volume
        B        |L10.1116|
|L10.1020|
        DCD      dev_state
|L10.1024|
        DCD      dev_input
|L10.1028|
        DCD      ||.data||
|L10.1032|
        DCD      0x5000425c
|L10.1036|
        DCD      battery_high_flag
|L10.1040|
        DCD      Core_tx_flag
|L10.1044|
        DCD      change_channal_flag
|L10.1048|
        DCD      SB_flag
|L10.1052|
        DCD      soundbar_multiroom_flag
|L10.1056|
        DCD      Dwhp83_flag
|L10.1060|
        DCD      Dwhp83_CuMu
|L10.1064|
        DCD      0x0000aa55
|L10.1068|
        DCD      0x000055aa
|L10.1072|
        DCD      TX_sound_flag
|L10.1076|
        DCD      TX_flag
|L10.1080|
        DCD      bt_amp_start_flag
|L10.1084|
        DCD      play_music_flag
|L10.1088|
        DCD      MCU_VERSION_NUMBER
|L10.1092|
        DCD      BT_VERSION_NUMBER
|L10.1096|
        DCD      WL_VERSION_NUMBER
|L10.1100|
        DCD      FLASH_VERSION_NUMBER
|L10.1104|
        DCD      dwhp83_status
|L10.1108|
        DCD      power_first_on_flag
|L10.1112|
        DCD      amp_volume
|L10.1116|
        CMP      r0,#0
        BEQ      |L10.1146|
        BL       isMute
        CMP      r0,#0
        BNE      |L10.1146|
        LDR      r0,|L10.2148|
        LDR      r0,[r0,#0]  ; amp_volume
        CMP      r0,#0
        BEQ      |L10.1146|
        MOVS     r0,#0x14
        BL       sysDelayMs
        BL       SB_rx_volume_2_SUB
|L10.1146|
        LDR      r0,|L10.2152|
        LDRB     r0,[r0,#0]  ; SB_flag
        CMP      r0,#0
        BEQ      |L10.1206|
        LDR      r0,[r7,#0x48]  ; soundbar_alive_counter
        ADDS     r0,r0,#1
        STR      r0,[r7,#0x48]  ; soundbar_alive_counter
        CMP      r0,#0x1e
        BLS      |L10.1206|
        LDR      r0,|L10.2156|
        LDRB     r0,[r0,#0]  ; dev_state
        CMP      r0,#2
        BEQ      |L10.1206|
        STR      r4,[r7,#0x48]  ; soundbar_alive_counter
        BL       Dwhp83CuMuDetect
        LDR      r0,|L10.2160|
        LDR      r2,[r0,#0]  ; Dwhp83_CuMu
        LDR      r1,|L10.2164|
        CMP      r2,r1
        BNE      |L10.1194|
        BL       RX_SB_alive
        B        |L10.1206|
|L10.1194|
        LDR      r1,[r0,#0]  ; Dwhp83_CuMu
        LDR      r0,|L10.2168|
        CMP      r1,r0
        BNE      |L10.1206|
        BL       TX_SB_alive
|L10.1206|
        LDRB     r0,[r7,#0]  ; state_color
        CMP      r0,#9
        BEQ      |L10.1286|
        LDR      r0,|L10.2156|
        LDRB     r0,[r0,#0]  ; dev_state
        CMP      r0,#2
        BEQ      |L10.1446|
        BL       callDetect
        CMP      r0,#0
        BEQ      |L10.1448|
        LDRB     r0,[r7,#0]  ; state_color
        CMP      r0,#8
        BEQ      |L10.1448|
        MOVS     r0,#8
        STR      r4,[r7,#0x20]  ; bt_call_hold
        STRB     r0,[r7,#0]
        BL       ledColorSet
        MOVS     r0,#1
        BL       seW58SetBypass
        BL       seW58sendCmd
        MOVS     r0,#5
        BL       sysDelayMs
        STRB     r4,[r6,#0]
        MOVS     r0,#2
        STR      r0,[r7,#0x50]  ; BT_CALL_FLAG
        LDR      r0,|L10.2148|
        LDR      r1,|L10.2172|
        LDR      r2,[r0,#0]  ; amp_volume
        STR      r2,[r1,#0]  ; w3d_volume_back
        MOVS     r1,#0x14
        STR      r1,[r0,#0]  ; amp_volume
        MOVS     r0,#1
        BL       changeInputVolumeDown
        B        |L10.1806|
|L10.1286|
        BL       callDetect
        CMP      r0,#0
        BEQ      |L10.1368|
        LDR      r0,[r7,#0x50]  ; BT_CALL_FLAG
        CMP      r0,#0
        BNE      |L10.1368|
        MOVS     r0,#8
        STRB     r0,[r7,#0]
        BL       ledColorSet
        BL       mute
        MOVS     r0,#0xc8
        BL       sysDelayMs
        LDR      r0,|L10.2176|
        STR      r5,[r0,#0]
        LDR      r0,|L10.2176|
        SUBS     r0,r0,#0x24
        STR      r4,[r0,#0]
        SUBS     r0,r0,#4
        STR      r5,[r0,#0]
        BL       callOnMode
        MOVS     r0,#0xc8
        BL       sysDelayMs
        BL       unMute
        LDR      r0,|L10.2148|
        STR      r5,[r7,#0x50]  ; BT_CALL_FLAG
        STR      r4,[r7,#0x20]  ; bt_call_hold
        LDR      r1,|L10.2172|
        LDR      r2,[r0,#0]  ; amp_volume
        STR      r2,[r1,#0]  ; w3d_volume_back
        MOVS     r1,#0x14
        STR      r1,[r0,#0]  ; amp_volume
        MOVS     r0,#9
        BL       changeInputVolumeDown
|L10.1368|
        LDR      r0,[r7,#0x1c]  ; volume_key_delay
        CMP      r0,#0
        BEQ      |L10.1394|
        SUBS     r0,r0,#1
        STR      r0,[r7,#0x1c]  ; volume_key_delay
        BL       isBtPaired
        CMP      r0,#0
        BEQ      |L10.1624|
        LDR      r0,[r7,#0x18]  ; BT_MATCH_FLAG
        CMP      r0,#0
        BEQ      |L10.1586|
        B        |L10.1624|
|L10.1394|
        BL       isBtPaired
        CMP      r0,#0
        BEQ      |L10.1412|
        STR      r4,[r7,#0x68]  ; ccp
        LDR      r0,[r7,#0x18]  ; BT_MATCH_FLAG
        CMP      r0,#0
        BEQ      |L10.1554|
        B        |L10.1582|
|L10.1412|
        LDR      r0,[r7,#0x4c]  ; bt_match_times
        CMP      r0,#0
        BEQ      |L10.1424|
        SUBS     r0,r0,#1
        STR      r0,[r7,#0x4c]  ; bt_match_times
        B        |L10.1432|
|L10.1424|
        MOVS     r0,#8
        STR      r0,[r7,#0x4c]  ; bt_match_times
        MOVS     r0,#5
        STR      r0,[r7,#0xc]  ; led_flash
|L10.1432|
        LDR      r0,[r7,#0x18]  ; BT_MATCH_FLAG
        CMP      r0,#0
        BEQ      |L10.1450|
        MOVS     r0,#5
        BL       playMusic
        B        |L10.1484|
|L10.1446|
        B        |L10.1780|
|L10.1448|
        B        |L10.1696|
|L10.1450|
        LDR      r0,[r7,#0x5c]  ; cck
        ADDS     r0,r0,#1
        STR      r0,[r7,#0x5c]  ; cck
        CMP      r0,#0x7d
        BLS      |L10.1484|
        LDR      r0,[r7,#0x3c]  ; cc_blue_p
        CMP      r0,#0
        BEQ      |L10.1484|
        SUBS     r0,r0,#1
        STR      r0,[r7,#0x3c]  ; cc_blue_p
        LDR      r0,|L10.2180|
        LDRB     r0,[r0,#0]  ; bt_change_name_mode
        CMP      r0,#0
        BNE      |L10.1482|
        BL       isBtPaired
|L10.1482|
        STR      r4,[r7,#0x5c]  ; cck
|L10.1484|
        STR      r4,[r7,#0x18]  ; BT_MATCH_FLAG
        LDR      r1,[r7,#0x68]  ; ccp
        MOV      r0,r1
        SUBS     r0,r0,#0xff
        SUBS     r0,r0,#0x2d
        BNE      |L10.1510|
        BL       btPairing
        MOVS     r0,#0x14
        BL       sysDelayMs
        LDR      r0,|L10.2184|
        STRB     r4,[r0,#0]
|L10.1510|
        LDR      r1,|L10.2188|
        LDR      r0,[r7,#0x68]  ; ccp
        CMP      r0,r1
        BLS      |L10.1540|
        LDR      r0,|L10.2192|
        LDRB     r0,[r0,#0]  ; bt_lost_flag
        CMP      r0,#1
        BNE      |L10.1538|
        LDR      r0,|L10.2196|
        LDRB     r0,[r0,#0]  ; bt_paring_flag
        CMP      r0,#0
        BNE      |L10.1538|
        BL       btReconnect
|L10.1538|
        STR      r4,[r7,#0x68]  ; ccp
|L10.1540|
        LDR      r0,[r7,#0x60]  ; ccr
        CMP      r0,#0
        BNE      |L10.1624|
        LDR      r0,[r7,#0x68]  ; ccp
        ADDS     r0,r0,#1
        STR      r0,[r7,#0x68]  ; ccp
        B        |L10.1624|
|L10.1554|
        MOVS     r0,#4
        BL       playMusic
        MOVS     r0,#0xff
        ADDS     r0,r0,#0xf5
        BL       sysDelayMs
        MOVS     r0,#0x2d
        STR      r4,[r7,#0x60]  ; ccr
        STR      r0,[r7,#0x3c]  ; cc_blue_p
        LDR      r0,|L10.2196|
        STRB     r4,[r0,#0]
        LDR      r0,|L10.2192|
        STRB     r4,[r0,#0]
|L10.1582|
        STR      r5,[r7,#0x18]  ; BT_MATCH_FLAG
        B        |L10.1624|
|L10.1586|
        MOVS     r0,#4
        BL       playMusic
        MOVS     r0,#0xff
        ADDS     r0,r0,#0xf5
        BL       sysDelayMs
        MOVS     r0,#0x2d
        STR      r0,[r7,#0x3c]  ; cc_blue_p
        LDR      r0,|L10.2184|
        STRB     r4,[r0,#0]
        LDR      r0,|L10.2196|
        STRB     r4,[r0,#0]
        LDR      r0,|L10.2200|
        STR      r5,[r7,#0x18]  ; BT_MATCH_FLAG
        STRB     r4,[r0,#0]
        LDR      r0,|L10.2192|
        STR      r4,[r7,#0x60]  ; ccr
        STRB     r4,[r0,#0]
|L10.1624|
        LDR      r0,|L10.2176|
        SUBS     r0,r0,#0x10
        LDR      r0,[r0,#0]
        CMP      r0,#0
        BEQ      |L10.1806|
        LDRB     r0,[r7,#2]  ; NFC_decting_flag
        CMP      r0,#0
        BNE      |L10.1806|
        MOVS     r0,#0x2d
        STR      r0,[r7,#0x3c]  ; cc_blue_p
        LDR      r0,|L10.2184|
        STRB     r5,[r7,#2]
        STRB     r5,[r0,#0]
        LDR      r0,|L10.2204|
        STRB     r4,[r0,#0]
        BL       bt_dis_last_connect
        MOVS     r0,#0x14
        BL       sysDelayMs
        BL       btPairing
        LDR      r0,|L10.2152|
        LDRB     r0,[r0,#0]  ; SB_flag
        CMP      r0,#0
        BEQ      |L10.1686|
        LDR      r0,|L10.2208|
        STRB     r5,[r0,#0]
        LDR      r0,|L10.2212|
        STRB     r4,[r7,#9]
        STRB     r4,[r0,#0]
|L10.1686|
        MOVS     r0,#0x14
        STR      r4,[r7,#0x40]  ; change_channal_counter
        BL       sysDelayMs
        B        |L10.1806|
|L10.1696|
        LDR      r0,|L10.2176|
        SUBS     r0,r0,#0x10
        LDR      r0,[r0,#0]
        CMP      r0,#0
        BEQ      |L10.1806|
        LDR      r0,|L10.2200|
        STRB     r5,[r0,#0]
        STRB     r4,[r6,#0]
        MOVS     r0,#0x2d
        STR      r0,[r7,#0x3c]  ; cc_blue_p
        LDR      r0,|L10.2204|
        STRB     r4,[r0,#0]
        MOVS     r0,#0x1e
        BL       sysDelayMs
        LDR      r0,|L10.2176|
        SUBS     r0,r0,#0x44
        STR      r5,[r0,#0]
        BL       btStartUp
        BL       CHOOSE_BT_INPUT
        BL       cs8422SRCSourceSDIN
        MOVS     r0,#0xc8
        BL       sysDelayMs
        LDR      r0,|L10.2216|
        LDRB     r1,[r6,#0]  ; dev_input
        LDRB     r0,[r0,r1]
        STRB     r0,[r7,#0]
        LDR      r0,|L10.2152|
        LDRB     r0,[r0,#0]  ; SB_flag
        CMP      r0,#0
        BEQ      |L10.1776|
        LDR      r0,|L10.2208|
        STRB     r5,[r0,#0]
        LDR      r0,|L10.2212|
        STRB     r4,[r7,#9]
        STRB     r4,[r0,#0]
|L10.1776|
        STR      r4,[r7,#0x40]  ; change_channal_counter
        B        |L10.1806|
|L10.1780|
        LDR      r0,|L10.2176|
        SUBS     r0,r0,#0x10
        LDR      r0,[r0,#0]
        CMP      r0,#0
        BEQ      |L10.1806|
        LDR      r0,|L10.2200|
        STRB     r5,[r0,#0]
        MOVS     r0,#0x1e
        BL       sysDelayMs
        STRB     r4,[r6,#0]
        BL       outStandby
|L10.1806|
        LDR      r0,|L10.2176|
        SUBS     r0,r0,#0x10
        LDR      r0,[r0,#0]
        CMP      r0,#0
        BNE      |L10.1818|
        STRB     r4,[r7,#2]
|L10.1818|
        LDR      r0,[r7,#0x50]  ; BT_CALL_FLAG
        CMP      r0,#0
        BEQ      |L10.1872|
        BL       callDetect
        CMP      r0,#0
        BNE      |L10.1872|
        LDR      r0,[r7,#0x50]  ; BT_CALL_FLAG
        CMP      r0,#2
        BEQ      |L10.1900|
        MOVS     r0,#9
        STRB     r0,[r7,#0]
        BL       CHOOSE_BT_INPUT
        BL       callOffMode
        LDRB     r0,[r7,#0]  ; state_color
        BL       ledColorSet
        LDR      r0,|L10.2172|
        LDR      r1,[r0,#0]  ; w3d_volume_back
        LDR      r0,|L10.2148|
        STR      r1,[r0,#0]  ; amp_volume
        MOVS     r0,#7
|L10.1866|
        BL       changeInputVolumeDown
        STR      r4,[r7,#0x50]  ; BT_CALL_FLAG
|L10.1872|
        LDR      r0,[r7,#0x14]  ; BAT_STATE_DECT_DELAY_COUNT
        ADDS     r0,r0,#1
        STR      r0,[r7,#0x14]  ; BAT_STATE_DECT_DELAY_COUNT
        CMP      r0,#0x82
        BLS      |L10.2080|
        LDR      r0,|L10.2220|
        LDR      r1,|L10.2224|
        LDRB     r0,[r0,#0]  ; battery_state
        LDR      r2,|L10.2228|
        CMP      r0,#1
        BEQ      |L10.2052|
        CMP      r0,#2
        BNE      |L10.2080|
        B        |L10.1916|
|L10.1900|
        MOVS     r0,#2
        STRB     r0,[r6,#0]
        LDR      r0,|L10.2172|
        LDR      r1,[r0,#0]  ; w3d_volume_back
        LDR      r0,|L10.2148|
        STR      r1,[r0,#0]  ; amp_volume
        MOVS     r0,#1
        B        |L10.1866|
|L10.1916|
        LDR      r0,[r1,#0]  ; systick_counter
        CMP      r0,r2
        BCC      |L10.2080|
        BL       DECT_DC
        CMP      r0,#0
        BEQ      |L10.1946|
        LDR      r0,|L10.2216|
        LDRB     r1,[r6,#0]  ; dev_input
        LDRB     r0,[r0,r1]
        STRB     r0,[r7,#0]
        BL       ledColorSet
        STRB     r4,[r7,#7]
|L10.1944|
        B        |L10.2080|
|L10.1946|
        LDR      r0,|L10.2232|
        LDRB     r0,[r0,#0]  ; power_first_on_flag
        CMP      r0,#0
        BNE      |L10.2144|
        LDRB     r0,[r7,#7]  ; batterry_low_play_flag
        CMP      r0,#0
        BEQ      |L10.1974|
        CMP      r0,#1
        BEQ      |L10.1992|
        CMP      r0,#2
        BEQ      |L10.2010|
        CMP      r0,#3
        BEQ      |L10.2028|
        B        |L10.2238|
|L10.1974|
        MOVS     r0,#6
        BL       playMusic
        MOVS     r0,#0xff
        ADDS     r0,r0,#0x2d
        BL       sysDelayMs
        STRB     r5,[r7,#7]
        B        |L10.2238|
|L10.1992|
        MOVS     r0,#6
        BL       playMusic
        MOVS     r0,#0xff
        ADDS     r0,r0,#0x2d
        BL       sysDelayMs
        MOVS     r0,#2
        B        |L10.2048|
|L10.2010|
        MOVS     r0,#6
        BL       playMusic
        MOVS     r0,#0xff
        ADDS     r0,r0,#0x2d
        BL       sysDelayMs
        MOVS     r0,#3
        B        |L10.2048|
|L10.2028|
        MOVS     r0,#6
        BL       playMusic
        BL       setConfig
        MOVS     r0,#0xff
        ADDS     r0,r0,#0x2d
        BL       sysDelayMs
        MOVS     r0,#4
|L10.2048|
        STRB     r0,[r7,#7]
        B        |L10.2238|
|L10.2052|
        LDR      r0,[r1,#0]  ; systick_counter
        CMP      r0,r2
        BCC      |L10.2080|
        BL       DECT_DC
        CMP      r0,#0
        BEQ      |L10.2090|
        LDR      r0,|L10.2216|
        LDRB     r1,[r6,#0]  ; dev_input
        LDRB     r0,[r0,r1]
        STRB     r0,[r7,#0]
        BL       ledColorSet
        STRB     r4,[r7,#6]
|L10.2080|
        BL       callDetect
        CMP      r0,#0
        BEQ      |L10.2242|
        B        |L10.2246|
|L10.2090|
        LDR      r0,|L10.2232|
        LDRB     r0,[r0,#0]  ; power_first_on_flag
        CMP      r0,#0
        BNE      |L10.2144|
        LDRB     r0,[r7,#6]  ; batterry_middle_play_flag
        CMP      r0,#0
        BEQ      |L10.2110|
        CMP      r0,#1
        BEQ      |L10.2126|
        B        |L10.2238|
|L10.2110|
        MOVS     r0,#6
        BL       playMusic
        MOVS     r0,#0xff
        ADDS     r0,r0,#0x2d
        BL       sysDelayMs
        STRB     r5,[r7,#6]
|L10.2126|
        MOVS     r0,#6
        BL       playMusic
        MOVS     r0,#0xff
        ADDS     r0,r0,#0x2d
        BL       sysDelayMs
        MOVS     r0,#2
        B        |L10.2236|
|L10.2144|
        B        |L10.2338|
        DCW      0x0000
|L10.2148|
        DCD      amp_volume
|L10.2152|
        DCD      SB_flag
|L10.2156|
        DCD      dev_state
|L10.2160|
        DCD      Dwhp83_CuMu
|L10.2164|
        DCD      0x0000aa55
|L10.2168|
        DCD      0x000055aa
|L10.2172|
        DCD      w3d_volume_back
|L10.2176|
        DCD      0x50004278
|L10.2180|
        DCD      bt_change_name_mode
|L10.2184|
        DCD      bt_reconnect_flag
|L10.2188|
        DCD      0x00000226
|L10.2192|
        DCD      bt_lost_flag
|L10.2196|
        DCD      bt_paring_flag
|L10.2200|
        DCD      NFC_flag
|L10.2204|
        DCD      bt_power_flag
|L10.2208|
        DCD      change_channal_flag
|L10.2212|
        DCD      TX_sound_flag
|L10.2216|
        DCD      input_channel_color
|L10.2220|
        DCD      battery_state
|L10.2224|
        DCD      systick_counter
|L10.2228|
        DCD      0x00001388
|L10.2232|
        DCD      power_first_on_flag
|L10.2236|
        STRB     r0,[r7,#6]
|L10.2238|
        STR      r5,[r7,#0x38]  ; breath_flag
        B        |L10.2274|
|L10.2242|
        LDR      r0,|L10.2444|
        STRB     r4,[r0,#0]
|L10.2246|
        BL       callDetect
        CMP      r0,#0
        BEQ      |L10.2280|
        LDR      r0,|L10.2444|
        LDRB     r0,[r0,#0]  ; mic_mute_flag
        CMP      r0,#1
        BNE      |L10.2280|
        LDR      r0,|L10.2448|
        LDRB     r0,[r0,#0]  ; dev_state
        CMP      r0,#2
        BEQ      |L10.2280|
        MOVS     r0,#2
        STR      r0,[r7,#0x38]  ; breath_flag
|L10.2274|
        BL       breathingColor
        B        |L10.2408|
|L10.2280|
        BL       isMute
        CMP      r0,#0
        BNE      |L10.2296|
        LDR      r0,|L10.2452|
        LDR      r0,[r0,#0]  ; amp_volume
        CMP      r0,#0
        BNE      |L10.2340|
|L10.2296|
        LDR      r0,|L10.2448|
        LDRB     r0,[r0,#0]  ; dev_state
        CMP      r0,#2
        BEQ      |L10.2340|
        LDRB     r0,[r7,#0]  ; state_color
        STR      r0,[r7,#0x38]  ; breath_flag
        BL       breathingColor
        LDR      r0,[r7,#0x64]  ; ccm
        CMP      r0,#0
        BNE      |L10.2408|
        LDR      r0,|L10.2456|
        LDRB     r0,[r0,#0]  ; SB_flag
        CMP      r0,#0
        BEQ      |L10.2408|
        LDRB     r0,[r6,#0]  ; dev_input
        CMP      r0,#1
        BNE      |L10.2408|
        BL       SB_volume_mute
        STR      r5,[r7,#0x64]  ; ccm
|L10.2338|
        B        |L10.2408|
|L10.2340|
        LDR      r0,[r7,#0x64]  ; ccm
        CMP      r0,#0
        BEQ      |L10.2366|
        LDR      r0,|L10.2456|
        LDRB     r0,[r0,#0]  ; SB_flag
        CMP      r0,#0
        BEQ      |L10.2364|
        LDRB     r0,[r6,#0]  ; dev_input
        CMP      r0,#1
        BNE      |L10.2364|
        BL       SB_volume_unmute
|L10.2364|
        STR      r4,[r7,#0x64]  ; ccm
|L10.2366|
        LDR      r0,[r7,#0xc]  ; led_flash
        CMP      r0,#0
        BEQ      |L10.2394|
        LDR      r0,|L10.2448|
        LDRB     r0,[r0,#0]  ; dev_state
        CMP      r0,#2
        BEQ      |L10.2394|
        MOVS     r0,#0
        BL       ledColorSet
        LDR      r0,[r7,#0xc]  ; led_flash
        SUBS     r0,r0,#1
        STR      r0,[r7,#0xc]  ; led_flash
        B        |L10.2408|
|L10.2394|
        LDR      r0,|L10.2460|
        LDRB     r0,[r0,#0]  ; factory_mode_flag
        CMP      r0,#0
        BNE      |L10.2408|
        LDRB     r0,[r7,#0]  ; state_color
        BL       ledColorSet
|L10.2408|
        LDR      r0,|L10.2448|
        LDRB     r0,[r0,#0]  ; dev_state
        CMP      r0,#2
        BNE      |L10.2428|
        BL       DECT_DC
        CMP      r0,#0
        BNE      |L10.2428|
        BL       doPowerOff
|L10.2428|
        LDR      r3,|L10.2464|
        MOVS     r2,#0
        MOVS     r1,#0x1e
        LDRB     r0,[r7,#1]  ; led_task
        BL       startATask
        POP      {r3-r7,pc}
        ENDP

        DCW      0x0000
|L10.2444|
        DCD      mic_mute_flag
|L10.2448|
        DCD      dev_state
|L10.2452|
        DCD      amp_volume
|L10.2456|
        DCD      SB_flag
|L10.2460|
        DCD      factory_mode_flag
|L10.2464|
        DCD      ledTask

        AREA ||i.ledTaskInit||, CODE, READONLY, ALIGN=2

ledTaskInit PROC
        PUSH     {r4,lr}
        BL       getATask
        LDR      r1,|L11.28|
        CMP      r0,#0xff
        STRB     r0,[r1,#1]
        BEQ      |L11.24|
        LDR      r3,|L11.32|
        MOVS     r2,#0
        MOVS     r1,#0x1e
        BL       startATask
|L11.24|
        POP      {r4,pc}
        ENDP

        DCW      0x0000
|L11.28|
        DCD      ||.data||
|L11.32|
        DCD      ledTask

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.data||, DATA, ALIGN=2

state_color
        DCB      0x09
led_task
        DCB      0xff
NFC_decting_flag
        DCB      0x00
key_time_count
        DCB      0x00
sb_change_source_mute_flag
        DCB      0x00
tx_linked_flag
        DCB      0x00
batterry_middle_play_flag
        DCB      0x00
batterry_low_play_flag
        DCB      0x00
Core_tx_counter
        DCB      0x00
TX_sounder_counter
        DCB      0x00,0x00,0x00
led_flash
        DCD      0x00000000
bt_hang_up_signal
        DCD      0x00000000
BAT_STATE_DECT_DELAY_COUNT
        DCD      0x00000000
BT_MATCH_FLAG
        DCD      0x00000000
volume_key_delay
        DCD      0x0000001e
bt_call_hold
        DCD      0x00000000
||R_C||
        DCD      0x00000000
B_C
        DCD      0x00000000
G_C
        DCD      0x00000000
ptimer
        DCD      0x00000000
||ck||
        DCD      0x00000000
breath_flag
        DCD      0x000000ff
cc_blue_p
        DCD      0x0000002d
change_channal_counter
        DCD      0x00000000
||cc||
        DCD      0x00000000
soundbar_alive_counter
        DCD      0x00000000
bt_match_times
        DCD      0x00000000
BT_CALL_FLAG
        DCD      0x00000000
bt_amp_start_time
        DCD      0x00000000
||cct||
        DCD      0x00000000
||cck||
        DCD      0x00000000
||ccr||
        DCD      0x00000000
||ccm||
        DCD      0x00000000
||ccp||
        DCD      0x00000000
fade_color
        DCD      0x00000000
pwtable
        DCD      0x00000001
        DCD      0x00000002
        DCD      0x00000003
        DCD      0x00000004
        DCD      0x00000006
        DCD      0x00000009
        DCD      0x0000000c
        DCD      0x0000000f
        DCD      0x00000012
        DCD      0x00000018
        DCD      0x0000001e
        DCD      0x00000027
        DCD      0x00000030
        DCD      0x0000003e
        DCD      0x0000004e
        DCD      0x0000005f
        DCD      0x00000074
        DCD      0x00000083
        DCD      0x00000096
        DCD      0x000000aa
        DCD      0x000000c8

        AREA ||area_number.15||, DATA, ALIGN=1

        EXPORTAS ||area_number.15||, ||.data||
color_pwm_clc
        DCW      0x03e8,0x03e8
        DCB      0x0c,0x04,0x01,0x00

        AREA ||area_number.16||, DATA, ALIGN=2

        EXPORTAS ||area_number.16||, ||.data||
RGB_brightness
        DCW      0x03e8,0x0384
        DCW      0x0320,0x02bc
        DCW      0x0258,0x01f4
        DCW      0x0190,0x012c
        DCW      0x00c8,0x0064
        DCW      0x0000

        AREA ||area_number.17||, DATA, ALIGN=2

        EXPORTAS ||area_number.17||, ||.data||
|symbol_number.124|
        DCD      0x00000000

        AREA ||i.__ARM_common_switch8||, COMGROUP=__ARM_common_switch8, CODE, READONLY, ALIGN=1

__ARM_common_switch8 PROC
        PUSH     {r4,r5}
        MOV      r4,lr
        SUBS     r4,r4,#1
        LDRB     r5,[r4,#0]
        ADDS     r4,r4,#1
        CMP      r3,r5
        BCS      |L76.16|
        MOV      r5,r3
|L76.16|
        LDRB     r3,[r4,r5]
        LSLS     r3,r3,#1
        ADDS     r3,r4,r3
        POP      {r4,r5}
        BX       r3
        ENDP


        EXPORT TMR0_IRQHandler [CODE]
        EXPORT breathingColor [CODE]
        EXPORT fadeoff [CODE]
        EXPORT fadeon [CODE]
        EXPORT ledColorSet [CODE]
        EXPORT ledInit [CODE]
        EXPORT ledTask [CODE]
        EXPORT ledTaskInit [CODE]
        EXPORT state_color [DATA,SIZE=1]
        EXPORT led_task [DATA,SIZE=1]
        EXPORT NFC_decting_flag [DATA,SIZE=1]
        EXPORT key_time_count [DATA,SIZE=1]
        EXPORT sb_change_source_mute_flag [DATA,SIZE=1]
        EXPORT tx_linked_flag [DATA,SIZE=1]
        EXPORT led_flash [DATA,SIZE=4]
        EXPORT bt_hang_up_signal [DATA,SIZE=4]
        EXPORT BAT_STATE_DECT_DELAY_COUNT [DATA,SIZE=4]
        EXPORT BT_MATCH_FLAG [DATA,SIZE=4]
        EXPORT volume_key_delay [DATA,SIZE=4]
        EXPORT bt_call_hold [DATA,SIZE=4]
        EXPORT ||R_C|| [DATA,SIZE=4]
        EXPORT B_C [DATA,SIZE=4]
        EXPORT G_C [DATA,SIZE=4]
        EXPORT ptimer [DATA,SIZE=4]
        EXPORT breath_flag [DATA,SIZE=4]
        EXPORT cc_blue_p [DATA,SIZE=4]
        EXPORT change_channal_counter [DATA,SIZE=4]
        EXPORT pwtable [DATA,SIZE=84]
        EXPORT color_pwm_clc [DATA,SIZE=8]
        EXPORT RGB_brightness [DATA,SIZE=22]
        EXPORTAS |symbol_number.124|, ||ccp||
        EXPORT |symbol_number.124| [DATA,SIZE=4]
        EXPORT __ARM_common_switch8 [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT DrvTIMER_Init [CODE]
        IMPORT DrvTIMER_EnableInt [CODE]
        IMPORT sleep_flag [DATA]
        IMPORT __aeabi_uidivmod [CODE]
        IMPORT DWHP83DealMsg [CODE]
        IMPORT DWHP83Mute [CODE]
        IMPORT DWHP83UnMute [CODE]
        IMPORT soundbar_coco_check [CODE]
        IMPORT DWHP83toEXT_MCU [CODE]
        IMPORT sysDelayMs [CODE]
        IMPORT set_soundbar_coco [CODE]
        IMPORT Dwhp83CuMuDetect [CODE]
        IMPORT Dwhp83Master [CODE]
        IMPORT change_to_local_coco [CODE]
        IMPORT set_local_coco [CODE]
        IMPORT Dwhp83Slave [CODE]
        IMPORT isDwhp83Linked [CODE]
        IMPORT DWP83SpiritTask [CODE]
        IMPORT playMusic [CODE]
        IMPORT MU_tell_CU_change [CODE]
        IMPORT Dwhp83GetStatus [CODE]
        IMPORT callDetect [CODE]
        IMPORT isCallIn [CODE]
        IMPORT openCall [CODE]
        IMPORT closeCall [CODE]
        IMPORT startATask [CODE]
        IMPORT RX_SB_alive [CODE]
        IMPORT isMute [CODE]
        IMPORT SB_rx_volume_2_SUB [CODE]
        IMPORT TX_SB_alive [CODE]
        IMPORT mute [CODE]
        IMPORT callOnMode [CODE]
        IMPORT unMute [CODE]
        IMPORT changeInputVolumeDown [CODE]
        IMPORT isBtPaired [CODE]
        IMPORT btPairing [CODE]
        IMPORT btReconnect [CODE]
        IMPORT bt_dis_last_connect [CODE]
        IMPORT seW58SetBypass [CODE]
        IMPORT seW58sendCmd [CODE]
        IMPORT btStartUp [CODE]
        IMPORT cs8422SRCSourceSDIN [CODE]
        IMPORT outStandby [CODE]
        IMPORT callOffMode [CODE]
        IMPORT setConfig [CODE]
        IMPORT SB_volume_mute [CODE]
        IMPORT SB_volume_unmute [CODE]
        IMPORT doPowerOff [CODE]
        IMPORT dev_state [DATA]
        IMPORT dev_input [DATA]
        IMPORT battery_high_flag [DATA]
        IMPORT Core_tx_flag [DATA]
        IMPORT change_channal_flag [DATA]
        IMPORT SB_flag [DATA]
        IMPORT soundbar_multiroom_flag [DATA]
        IMPORT Dwhp83_flag [DATA]
        IMPORT Dwhp83_CuMu [DATA]
        IMPORT TX_sound_flag [DATA]
        IMPORT TX_flag [DATA]
        IMPORT bt_amp_start_flag [DATA]
        IMPORT play_music_flag [DATA]
        IMPORT MCU_VERSION_NUMBER [DATA]
        IMPORT BT_VERSION_NUMBER [DATA]
        IMPORT WL_VERSION_NUMBER [DATA]
        IMPORT FLASH_VERSION_NUMBER [DATA]
        IMPORT dwhp83_status [DATA]
        IMPORT power_first_on_flag [DATA]
        IMPORT amp_volume [DATA]
        IMPORT w3d_volume_back [DATA]
        IMPORT bt_change_name_mode [DATA]
        IMPORT bt_reconnect_flag [DATA]
        IMPORT bt_lost_flag [DATA]
        IMPORT bt_paring_flag [DATA]
        IMPORT NFC_flag [DATA]
        IMPORT bt_power_flag [DATA]
        IMPORT input_channel_color [DATA]
        IMPORT battery_state [DATA]
        IMPORT systick_counter [DATA]
        IMPORT mic_mute_flag [DATA]
        IMPORT factory_mode_flag [DATA]
        IMPORT getATask [CODE]

        KEEP CHOOSE_BT_INPUT
        KEEP DECT_DC
        KEEP GPIO_SET_MODE
        KEEP batterry_middle_play_flag
        KEEP batterry_low_play_flag
        KEEP Core_tx_counter
        KEEP TX_sounder_counter
        KEEP ||ck||
        KEEP ||cc||
        KEEP soundbar_alive_counter
        KEEP bt_match_times
        KEEP BT_CALL_FLAG
        KEEP bt_amp_start_time
        KEEP ||cct||
        KEEP ||cck||
        KEEP ||ccr||
        KEEP ||ccm||
        KEEP ||ccp||
        KEEP fade_color

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,3
        ATTR SETSTRING Tag_conformance,"2.06"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
